// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tri-state *bool in Go (nil defaults to true). optional preserves that.
	TmuxVimKeys   *bool `protobuf:"varint,1,opt,name=tmux_vim_keys,json=tmuxVimKeys,proto3,oneof" json:"tmux_vim_keys,omitempty"`
	ShowHelpText  *bool `protobuf:"varint,2,opt,name=show_help_text,json=showHelpText,proto3,oneof" json:"show_help_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralSettings) Reset() {
	*x = GeneralSettings{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralSettings) ProtoMessage() {}

func (x *GeneralSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralSettings.ProtoReflect.Descriptor instead.
func (*GeneralSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralSettings) GetTmuxVimKeys() bool {
	if x != nil && x.TmuxVimKeys != nil {
		return *x.TmuxVimKeys
	}
	return false
}

func (x *GeneralSettings) GetShowHelpText() bool {
	if x != nil && x.ShowHelpText != nil {
		return *x.ShowHelpText
	}
	return false
}

type AgentSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String enum in Go (e.g. "claude"); kept a plain string to avoid coupling the
	// contract to the agent-tool list, which the server validates against its own
	// allowlist (DefaultConfig forces "claude" when unknown/empty).
	ToolSelection string `protobuf:"bytes,1,opt,name=tool_selection,json=toolSelection,proto3" json:"tool_selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSettings) Reset() {
	*x = AgentSettings{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSettings) ProtoMessage() {}

func (x *AgentSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSettings.ProtoReflect.Descriptor instead.
func (*AgentSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *AgentSettings) GetToolSelection() string {
	if x != nil {
		return x.ToolSelection
	}
	return ""
}

type DotfilesSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AutoInstall   bool                   `protobuf:"varint,1,opt,name=auto_install,json=autoInstall,proto3" json:"auto_install,omitempty"`
	Repo          *string                `protobuf:"bytes,2,opt,name=repo,proto3,oneof" json:"repo,omitempty"`
	InstallScript *string                `protobuf:"bytes,3,opt,name=install_script,json=installScript,proto3,oneof" json:"install_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DotfilesSettings) Reset() {
	*x = DotfilesSettings{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DotfilesSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotfilesSettings) ProtoMessage() {}

func (x *DotfilesSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotfilesSettings.ProtoReflect.Descriptor instead.
func (*DotfilesSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *DotfilesSettings) GetAutoInstall() bool {
	if x != nil {
		return x.AutoInstall
	}
	return false
}

func (x *DotfilesSettings) GetRepo() string {
	if x != nil && x.Repo != nil {
		return *x.Repo
	}
	return ""
}

func (x *DotfilesSettings) GetInstallScript() string {
	if x != nil && x.InstallScript != nil {
		return *x.InstallScript
	}
	return ""
}

// CoderParameter mirrors internal/state.CoderParameter — one Coder template
// parameter binding. name+value are always present; the remaining fields are
// template-derived metadata (JSON `,omitempty`) and so are optional.
type CoderParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // may contain ${GIT_URL}, ${GIT_BRANCH}, ${INSTANCE_NAME}
	DefaultValue  *string                `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	DisplayName   *string                `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Type          *string                `protobuf:"bytes,6,opt,name=type,proto3,oneof" json:"type,omitempty"` // "string", "number"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoderParameter) Reset() {
	*x = CoderParameter{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoderParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoderParameter) ProtoMessage() {}

func (x *CoderParameter) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoderParameter.ProtoReflect.Descriptor instead.
func (*CoderParameter) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *CoderParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CoderParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CoderParameter) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *CoderParameter) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CoderParameter) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CoderParameter) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type CoderSettings struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Template *string                `protobuf:"bytes,1,opt,name=template,proto3,oneof" json:"template,omitempty"`
	Preset   *string                `protobuf:"bytes,2,opt,name=preset,proto3,oneof" json:"preset,omitempty"`
	// Mirrors []CoderParameter — a rich list (value + template metadata), NOT a
	// name->value map: the TUI re-renders default/display/description/type after a
	// fetch, so those must round-trip through SetConfig without loss.
	Parameters    []*CoderParameter `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoderSettings) Reset() {
	*x = CoderSettings{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoderSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoderSettings) ProtoMessage() {}

func (x *CoderSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoderSettings.ProtoReflect.Descriptor instead.
func (*CoderSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *CoderSettings) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *CoderSettings) GetPreset() string {
	if x != nil && x.Preset != nil {
		return *x.Preset
	}
	return ""
}

func (x *CoderSettings) GetParameters() []*CoderParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CodespacesSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Machine          *string                `protobuf:"bytes,1,opt,name=machine,proto3,oneof" json:"machine,omitempty"`
	IdleTimeout      *string                `protobuf:"bytes,2,opt,name=idle_timeout,json=idleTimeout,proto3,oneof" json:"idle_timeout,omitempty"`
	DevcontainerPath *string                `protobuf:"bytes,3,opt,name=devcontainer_path,json=devcontainerPath,proto3,oneof" json:"devcontainer_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CodespacesSettings) Reset() {
	*x = CodespacesSettings{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodespacesSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodespacesSettings) ProtoMessage() {}

func (x *CodespacesSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodespacesSettings.ProtoReflect.Descriptor instead.
func (*CodespacesSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *CodespacesSettings) GetMachine() string {
	if x != nil && x.Machine != nil {
		return *x.Machine
	}
	return ""
}

func (x *CodespacesSettings) GetIdleTimeout() string {
	if x != nil && x.IdleTimeout != nil {
		return *x.IdleTimeout
	}
	return ""
}

func (x *CodespacesSettings) GetDevcontainerPath() string {
	if x != nil && x.DevcontainerPath != nil {
		return *x.DevcontainerPath
	}
	return ""
}

// BrowserSettings mirrors internal/state.BrowserSettings. Both fields are
// *bool tri-states in Go (nil defaults to false), so optional preserves the
// nil-vs-explicit-false distinction the profile-layout / prompt-suppression
// logic branches on.
type BrowserSettings struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MultipleBrowsersPerFleet *bool                  `protobuf:"varint,1,opt,name=multiple_browsers_per_fleet,json=multipleBrowsersPerFleet,proto3,oneof" json:"multiple_browsers_per_fleet,omitempty"`
	AutoSwitch               *bool                  `protobuf:"varint,2,opt,name=auto_switch,json=autoSwitch,proto3,oneof" json:"auto_switch,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BrowserSettings) Reset() {
	*x = BrowserSettings{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserSettings) ProtoMessage() {}

func (x *BrowserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserSettings.ProtoReflect.Descriptor instead.
func (*BrowserSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *BrowserSettings) GetMultipleBrowsersPerFleet() bool {
	if x != nil && x.MultipleBrowsersPerFleet != nil {
		return *x.MultipleBrowsersPerFleet
	}
	return false
}

func (x *BrowserSettings) GetAutoSwitch() bool {
	if x != nil && x.AutoSwitch != nil {
		return *x.AutoSwitch
	}
	return false
}

// RemoteMcpSettings mirrors internal/state.RemoteMcpSettings — the user's intent
// to expose this daemon's local MCP server (enabled) and/or its gRPC control
// surface (fleet_enabled) to the internet through a remote fleet gateway. Both
// ride the SAME tunnel to the same gateway_url; the two toggles are independent,
// so a user can expose MCP, remote control, or both.
//
// The COMPUTED "Public MCP URL" / "Public GRPC URL" the gateway assigns on
// connect are deliberately NOT in Config — they are runtime state owned by the
// server and pushed to the TUI via the Watch RemoteMcpStatus event (watch.proto).
// Keeping them out of Config is what prevents the SetConfig-replaces-everything
// contract from clobbering them.
type RemoteMcpSettings struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Enabled    bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	GatewayUrl string                 `protobuf:"bytes,2,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	// fleet_enabled gates the gateway gRPC endpoint ("Enable Remote Fleet"): when
	// false fleetd does not negotiate the grpc tunnel feature, so the gateway
	// rejects any remote `fleet` control RPCs aimed at this daemon.
	FleetEnabled bool `protobuf:"varint,3,opt,name=fleet_enabled,json=fleetEnabled,proto3" json:"fleet_enabled,omitempty"`
	// webhook_enabled gates the gateway webhook endpoint ("Enable Webhook"): when
	// false fleetd does not negotiate the webhook tunnel feature, so the gateway
	// does not serve <session-url>/webhook/<name> for this daemon. Independent of
	// enabled/fleet_enabled — all three ride the SAME outbound tunnel.
	WebhookEnabled bool `protobuf:"varint,4,opt,name=webhook_enabled,json=webhookEnabled,proto3" json:"webhook_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoteMcpSettings) Reset() {
	*x = RemoteMcpSettings{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMcpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMcpSettings) ProtoMessage() {}

func (x *RemoteMcpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMcpSettings.ProtoReflect.Descriptor instead.
func (*RemoteMcpSettings) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteMcpSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RemoteMcpSettings) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

func (x *RemoteMcpSettings) GetFleetEnabled() bool {
	if x != nil {
		return x.FleetEnabled
	}
	return false
}

func (x *RemoteMcpSettings) GetWebhookEnabled() bool {
	if x != nil {
		return x.WebhookEnabled
	}
	return false
}

type Config struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	General    *GeneralSettings       `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
	Agent      *AgentSettings         `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Dotfiles   *DotfilesSettings      `protobuf:"bytes,3,opt,name=dotfiles,proto3" json:"dotfiles,omitempty"`
	Coder      *CoderSettings         `protobuf:"bytes,4,opt,name=coder,proto3" json:"coder,omitempty"`
	Codespaces *CodespacesSettings    `protobuf:"bytes,5,opt,name=codespaces,proto3" json:"codespaces,omitempty"`
	Browser    *BrowserSettings       `protobuf:"bytes,6,opt,name=browser,proto3" json:"browser,omitempty"`
	// Feeds CreateInstanceRequest's UNSPECIFIED-backend resolution. UNSPECIFIED
	// means "no default recorded" (-> DEVCONTAINER).
	DefaultBackend BackendType        `protobuf:"varint,7,opt,name=default_backend,json=defaultBackend,proto3,enum=fleetgrpc.BackendType" json:"default_backend,omitempty"`
	RemoteMcp      *RemoteMcpSettings `protobuf:"bytes,8,opt,name=remote_mcp,json=remoteMcp,proto3" json:"remote_mcp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Config) GetGeneral() *GeneralSettings {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *Config) GetAgent() *AgentSettings {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Config) GetDotfiles() *DotfilesSettings {
	if x != nil {
		return x.Dotfiles
	}
	return nil
}

func (x *Config) GetCoder() *CoderSettings {
	if x != nil {
		return x.Coder
	}
	return nil
}

func (x *Config) GetCodespaces() *CodespacesSettings {
	if x != nil {
		return x.Codespaces
	}
	return nil
}

func (x *Config) GetBrowser() *BrowserSettings {
	if x != nil {
		return x.Browser
	}
	return nil
}

func (x *Config) GetDefaultBackend() BackendType {
	if x != nil {
		return x.DefaultBackend
	}
	return BackendType_BACKEND_TYPE_UNSPECIFIED
}

func (x *Config) GetRemoteMcp() *RemoteMcpSettings {
	if x != nil {
		return x.RemoteMcp
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

type GetConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigReply) Reset() {
	*x = GetConfigReply{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReply) ProtoMessage() {}

func (x *GetConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReply.ProtoReflect.Descriptor instead.
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *GetConfigReply) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// SetConfig replaces the whole Config (the settings page sends the full edited
// Config). Returns the post-mutation Config so the caller stays consistent.
type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *SetConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigReply) Reset() {
	*x = SetConfigReply{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigReply) ProtoMessage() {}

func (x *SetConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigReply.ProtoReflect.Descriptor instead.
func (*SetConfigReply) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *SetConfigReply) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\tfleetgrpc\x1a\fdomain.proto\"\x8a\x01\n" +
	"\x0fGeneralSettings\x12'\n" +
	"\rtmux_vim_keys\x18\x01 \x01(\bH\x00R\vtmuxVimKeys\x88\x01\x01\x12)\n" +
	"\x0eshow_help_text\x18\x02 \x01(\bH\x01R\fshowHelpText\x88\x01\x01B\x10\n" +
	"\x0e_tmux_vim_keysB\x11\n" +
	"\x0f_show_help_text\"6\n" +
	"\rAgentSettings\x12%\n" +
	"\x0etool_selection\x18\x01 \x01(\tR\rtoolSelection\"\x96\x01\n" +
	"\x10DotfilesSettings\x12!\n" +
	"\fauto_install\x18\x01 \x01(\bR\vautoInstall\x12\x17\n" +
	"\x04repo\x18\x02 \x01(\tH\x00R\x04repo\x88\x01\x01\x12*\n" +
	"\x0einstall_script\x18\x03 \x01(\tH\x01R\rinstallScript\x88\x01\x01B\a\n" +
	"\x05_repoB\x11\n" +
	"\x0f_install_script\"\x88\x02\n" +
	"\x0eCoderParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12(\n" +
	"\rdefault_value\x18\x03 \x01(\tH\x00R\fdefaultValue\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x06 \x01(\tH\x03R\x04type\x88\x01\x01B\x10\n" +
	"\x0e_default_valueB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_type\"\xa0\x01\n" +
	"\rCoderSettings\x12\x1f\n" +
	"\btemplate\x18\x01 \x01(\tH\x00R\btemplate\x88\x01\x01\x12\x1b\n" +
	"\x06preset\x18\x02 \x01(\tH\x01R\x06preset\x88\x01\x01\x129\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\x19.fleetgrpc.CoderParameterR\n" +
	"parametersB\v\n" +
	"\t_templateB\t\n" +
	"\a_preset\"\xc0\x01\n" +
	"\x12CodespacesSettings\x12\x1d\n" +
	"\amachine\x18\x01 \x01(\tH\x00R\amachine\x88\x01\x01\x12&\n" +
	"\fidle_timeout\x18\x02 \x01(\tH\x01R\vidleTimeout\x88\x01\x01\x120\n" +
	"\x11devcontainer_path\x18\x03 \x01(\tH\x02R\x10devcontainerPath\x88\x01\x01B\n" +
	"\n" +
	"\b_machineB\x0f\n" +
	"\r_idle_timeoutB\x14\n" +
	"\x12_devcontainer_path\"\xab\x01\n" +
	"\x0fBrowserSettings\x12B\n" +
	"\x1bmultiple_browsers_per_fleet\x18\x01 \x01(\bH\x00R\x18multipleBrowsersPerFleet\x88\x01\x01\x12$\n" +
	"\vauto_switch\x18\x02 \x01(\bH\x01R\n" +
	"autoSwitch\x88\x01\x01B\x1e\n" +
	"\x1c_multiple_browsers_per_fleetB\x0e\n" +
	"\f_auto_switch\"\x9c\x01\n" +
	"\x11RemoteMcpSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vgateway_url\x18\x02 \x01(\tR\n" +
	"gatewayUrl\x12#\n" +
	"\rfleet_enabled\x18\x03 \x01(\bR\ffleetEnabled\x12'\n" +
	"\x0fwebhook_enabled\x18\x04 \x01(\bR\x0ewebhookEnabled\"\xd0\x03\n" +
	"\x06Config\x124\n" +
	"\ageneral\x18\x01 \x01(\v2\x1a.fleetgrpc.GeneralSettingsR\ageneral\x12.\n" +
	"\x05agent\x18\x02 \x01(\v2\x18.fleetgrpc.AgentSettingsR\x05agent\x127\n" +
	"\bdotfiles\x18\x03 \x01(\v2\x1b.fleetgrpc.DotfilesSettingsR\bdotfiles\x12.\n" +
	"\x05coder\x18\x04 \x01(\v2\x18.fleetgrpc.CoderSettingsR\x05coder\x12=\n" +
	"\n" +
	"codespaces\x18\x05 \x01(\v2\x1d.fleetgrpc.CodespacesSettingsR\n" +
	"codespaces\x124\n" +
	"\abrowser\x18\x06 \x01(\v2\x1a.fleetgrpc.BrowserSettingsR\abrowser\x12?\n" +
	"\x0fdefault_backend\x18\a \x01(\x0e2\x16.fleetgrpc.BackendTypeR\x0edefaultBackend\x12;\n" +
	"\n" +
	"remote_mcp\x18\b \x01(\v2\x1c.fleetgrpc.RemoteMcpSettingsR\tremoteMcpJ\x04\b\t\x10\x15\"\x12\n" +
	"\x10GetConfigRequest\";\n" +
	"\x0eGetConfigReply\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.fleetgrpc.ConfigR\x06config\"=\n" +
	"\x10SetConfigRequest\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.fleetgrpc.ConfigR\x06config\";\n" +
	"\x0eSetConfigReply\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.fleetgrpc.ConfigR\x06configB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_config_proto_goTypes = []any{
	(*GeneralSettings)(nil),    // 0: fleetgrpc.GeneralSettings
	(*AgentSettings)(nil),      // 1: fleetgrpc.AgentSettings
	(*DotfilesSettings)(nil),   // 2: fleetgrpc.DotfilesSettings
	(*CoderParameter)(nil),     // 3: fleetgrpc.CoderParameter
	(*CoderSettings)(nil),      // 4: fleetgrpc.CoderSettings
	(*CodespacesSettings)(nil), // 5: fleetgrpc.CodespacesSettings
	(*BrowserSettings)(nil),    // 6: fleetgrpc.BrowserSettings
	(*RemoteMcpSettings)(nil),  // 7: fleetgrpc.RemoteMcpSettings
	(*Config)(nil),             // 8: fleetgrpc.Config
	(*GetConfigRequest)(nil),   // 9: fleetgrpc.GetConfigRequest
	(*GetConfigReply)(nil),     // 10: fleetgrpc.GetConfigReply
	(*SetConfigRequest)(nil),   // 11: fleetgrpc.SetConfigRequest
	(*SetConfigReply)(nil),     // 12: fleetgrpc.SetConfigReply
	(BackendType)(0),           // 13: fleetgrpc.BackendType
}
var file_config_proto_depIdxs = []int32{
	3,  // 0: fleetgrpc.CoderSettings.parameters:type_name -> fleetgrpc.CoderParameter
	0,  // 1: fleetgrpc.Config.general:type_name -> fleetgrpc.GeneralSettings
	1,  // 2: fleetgrpc.Config.agent:type_name -> fleetgrpc.AgentSettings
	2,  // 3: fleetgrpc.Config.dotfiles:type_name -> fleetgrpc.DotfilesSettings
	4,  // 4: fleetgrpc.Config.coder:type_name -> fleetgrpc.CoderSettings
	5,  // 5: fleetgrpc.Config.codespaces:type_name -> fleetgrpc.CodespacesSettings
	6,  // 6: fleetgrpc.Config.browser:type_name -> fleetgrpc.BrowserSettings
	13, // 7: fleetgrpc.Config.default_backend:type_name -> fleetgrpc.BackendType
	7,  // 8: fleetgrpc.Config.remote_mcp:type_name -> fleetgrpc.RemoteMcpSettings
	8,  // 9: fleetgrpc.GetConfigReply.config:type_name -> fleetgrpc.Config
	8,  // 10: fleetgrpc.SetConfigRequest.config:type_name -> fleetgrpc.Config
	8,  // 11: fleetgrpc.SetConfigReply.config:type_name -> fleetgrpc.Config
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_domain_proto_init()
	file_config_proto_msgTypes[0].OneofWrappers = []any{}
	file_config_proto_msgTypes[2].OneofWrappers = []any{}
	file_config_proto_msgTypes[3].OneofWrappers = []any{}
	file_config_proto_msgTypes[4].OneofWrappers = []any{}
	file_config_proto_msgTypes[5].OneofWrappers = []any{}
	file_config_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
