// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: exec.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Exec is a bidi stream for running a command inside an instance's container and
// piping stdin/stdout/stderr. The FIRST ExecIn MUST carry `start`; subsequent
// ExecIn carry stdin bytes (or resize). The server replies with ExecOut frames
// and a terminal `exit`.
//
// TTY CARVE-OUT: for interactive TTY attach (`fleet shell`, the TUI's tea.Exec),
// piping a full PTY over gRPC for a LOCAL user is wasteful — the terminal is on
// the client. For those, use ResolveExecCommand: the SERVER returns the
// ready-to-exec argv and the CLIENT execs it locally to inherit the user's TTY.
// Client-local exec for TTY attach is a PERMITTED client-host action, NOT a
// boundary violation.
type ExecIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecIn_Start
	//	*ExecIn_Stdin
	//	*ExecIn_Resize
	Msg           isExecIn_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecIn) Reset() {
	*x = ExecIn{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecIn) ProtoMessage() {}

func (x *ExecIn) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecIn.ProtoReflect.Descriptor instead.
func (*ExecIn) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecIn) GetMsg() isExecIn_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecIn) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecIn) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecIn) GetResize() *ExecResize {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecIn_Msg interface {
	isExecIn_Msg()
}

type ExecIn_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecIn_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecIn_Resize struct {
	Resize *ExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ExecIn_Start) isExecIn_Msg() {}

func (*ExecIn_Stdin) isExecIn_Msg() {}

func (*ExecIn_Resize) isExecIn_Msg() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Argv          []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecStart) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ExecStart) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ExecStart) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ExecOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecOut_Stdout
	//	*ExecOut_Stderr
	//	*ExecOut_Exit
	Msg           isExecOut_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOut) Reset() {
	*x = ExecOut{}
	mi := &file_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOut) ProtoMessage() {}

func (x *ExecOut) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOut.ProtoReflect.Descriptor instead.
func (*ExecOut) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{3}
}

func (x *ExecOut) GetMsg() isExecOut_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecOut) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecOut) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecOut) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecOut_Msg interface {
	isExecOut_Msg()
}

type ExecOut_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecOut_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecOut_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecOut_Stdout) isExecOut_Msg() {}

func (*ExecOut_Stderr) isExecOut_Msg() {}

func (*ExecOut_Exit) isExecOut_Msg() {}

type ExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{4}
}

func (x *ExecExit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExecExit) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ResolveExecCommand returns the argv the server would exec to reach the instance
// interactively, so the CLIENT can exec it locally and inherit the user's TTY.
type ResolveExecCommandRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// command to run inside; empty means "interactive login shell".
	Argv          []string `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveExecCommandRequest) Reset() {
	*x = ResolveExecCommandRequest{}
	mi := &file_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveExecCommandRequest) ProtoMessage() {}

func (x *ResolveExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ResolveExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveExecCommandRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ResolveExecCommandRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ResolveExecCommandRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type ResolveExecCommandReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv[0] is the program (e.g. devcontainer/docker/ssh); the client execs this
	// directly with inherited stdio.
	Argv          []string          `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	Env           map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveExecCommandReply) Reset() {
	*x = ResolveExecCommandReply{}
	mi := &file_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveExecCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveExecCommandReply) ProtoMessage() {}

func (x *ResolveExecCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveExecCommandReply.ProtoReflect.Descriptor instead.
func (*ResolveExecCommandReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveExecCommandReply) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ResolveExecCommandReply) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          *int32                 `protobuf:"varint,4,opt,name=tail,proto3,oneof" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{7}
}

func (x *LogsRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *LogsRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil && x.Tail != nil {
		return *x.Tail
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_exec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{8}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// PortForward returns a host-side command descriptor for forwarding a port; the
// client runs it. A descriptor RPC (not a data-plane proxy) to match the existing
// backend.PortForwardCommand idiom.
type PortForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardRequest) Reset() {
	*x = PortForwardRequest{}
	mi := &file_exec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRequest) ProtoMessage() {}

func (x *PortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardRequest.ProtoReflect.Descriptor instead.
func (*PortForwardRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{9}
}

func (x *PortForwardRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *PortForwardRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *PortForwardRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PortForwardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argv          []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardReply) Reset() {
	*x = PortForwardReply{}
	mi := &file_exec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardReply) ProtoMessage() {}

func (x *PortForwardReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardReply.ProtoReflect.Descriptor instead.
func (*PortForwardReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{10}
}

func (x *PortForwardReply) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\tfleetgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\x06ExecIn\x12,\n" +
	"\x05start\x18\x01 \x01(\v2\x14.fleetgrpc.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12/\n" +
	"\x06resize\x18\x03 \x01(\v2\x15.fleetgrpc.ExecResizeH\x00R\x06resizeB\x05\n" +
	"\x03msg\"\xcc\x01\n" +
	"\tExecStart\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.fleetgrpc.ExecStart.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"o\n" +
	"\aExecOut\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12)\n" +
	"\x04exit\x18\x03 \x01(\v2\x13.fleetgrpc.ExecExitH\x00R\x04exitB\x05\n" +
	"\x03msg\"C\n" +
	"\bExecExit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"a\n" +
	"\x19ResolveExecCommandRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\"\xa4\x01\n" +
	"\x17ResolveExecCommandReply\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12=\n" +
	"\x03env\x18\x02 \x03(\v2+.fleetgrpc.ResolveExecCommandReply.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\vLogsRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x17\n" +
	"\x04tail\x18\x04 \x01(\x05H\x00R\x04tail\x88\x01\x01B\a\n" +
	"\x05_tail\"I\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"Z\n" +
	"\x12PortForwardRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"&\n" +
	"\x10PortForwardReply\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argvB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_exec_proto_goTypes = []any{
	(*ExecIn)(nil),                    // 0: fleetgrpc.ExecIn
	(*ExecStart)(nil),                 // 1: fleetgrpc.ExecStart
	(*ExecResize)(nil),                // 2: fleetgrpc.ExecResize
	(*ExecOut)(nil),                   // 3: fleetgrpc.ExecOut
	(*ExecExit)(nil),                  // 4: fleetgrpc.ExecExit
	(*ResolveExecCommandRequest)(nil), // 5: fleetgrpc.ResolveExecCommandRequest
	(*ResolveExecCommandReply)(nil),   // 6: fleetgrpc.ResolveExecCommandReply
	(*LogsRequest)(nil),               // 7: fleetgrpc.LogsRequest
	(*LogLine)(nil),                   // 8: fleetgrpc.LogLine
	(*PortForwardRequest)(nil),        // 9: fleetgrpc.PortForwardRequest
	(*PortForwardReply)(nil),          // 10: fleetgrpc.PortForwardReply
	nil,                               // 11: fleetgrpc.ExecStart.EnvEntry
	nil,                               // 12: fleetgrpc.ResolveExecCommandReply.EnvEntry
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_exec_proto_depIdxs = []int32{
	1,  // 0: fleetgrpc.ExecIn.start:type_name -> fleetgrpc.ExecStart
	2,  // 1: fleetgrpc.ExecIn.resize:type_name -> fleetgrpc.ExecResize
	11, // 2: fleetgrpc.ExecStart.env:type_name -> fleetgrpc.ExecStart.EnvEntry
	4,  // 3: fleetgrpc.ExecOut.exit:type_name -> fleetgrpc.ExecExit
	12, // 4: fleetgrpc.ResolveExecCommandReply.env:type_name -> fleetgrpc.ResolveExecCommandReply.EnvEntry
	13, // 5: fleetgrpc.LogLine.at:type_name -> google.protobuf.Timestamp
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	file_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecIn_Start)(nil),
		(*ExecIn_Stdin)(nil),
		(*ExecIn_Resize)(nil),
	}
	file_exec_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecOut_Stdout)(nil),
		(*ExecOut_Stderr)(nil),
		(*ExecOut_Exit)(nil),
	}
	file_exec_proto_msgTypes[4].OneofWrappers = []any{}
	file_exec_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
