// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exec.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Exec is a bidi stream for running a command inside an instance's container and
// piping stdin/stdout/stderr. The FIRST ExecIn MUST carry `start`; subsequent
// ExecIn carry stdin bytes (or resize). The server replies with ExecOut frames
// and a terminal `exit`.
//
// TTY CARVE-OUT: for interactive TTY attach (`fleet shell`, the TUI's tea.Exec),
// piping a full PTY over gRPC for a LOCAL user is wasteful — the terminal is on
// the client. For those, use ResolveExecCommand: the SERVER returns the
// ready-to-exec argv and the CLIENT execs it locally to inherit the user's TTY.
// Client-local exec for TTY attach is a PERMITTED client-host action, NOT a
// boundary violation.
type ExecIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecIn_Start
	//	*ExecIn_Stdin
	//	*ExecIn_Resize
	Msg           isExecIn_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecIn) Reset() {
	*x = ExecIn{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecIn) ProtoMessage() {}

func (x *ExecIn) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecIn.ProtoReflect.Descriptor instead.
func (*ExecIn) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecIn) GetMsg() isExecIn_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecIn) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecIn) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecIn) GetResize() *ExecResize {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecIn_Msg interface {
	isExecIn_Msg()
}

type ExecIn_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecIn_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecIn_Resize struct {
	Resize *ExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ExecIn_Start) isExecIn_Msg() {}

func (*ExecIn_Stdin) isExecIn_Msg() {}

func (*ExecIn_Resize) isExecIn_Msg() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Argv          []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecStart) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ExecStart) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ExecStart) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ExecOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecOut_Stdout
	//	*ExecOut_Stderr
	//	*ExecOut_Exit
	Msg           isExecOut_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOut) Reset() {
	*x = ExecOut{}
	mi := &file_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOut) ProtoMessage() {}

func (x *ExecOut) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOut.ProtoReflect.Descriptor instead.
func (*ExecOut) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{3}
}

func (x *ExecOut) GetMsg() isExecOut_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecOut) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecOut) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecOut) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecOut_Msg interface {
	isExecOut_Msg()
}

type ExecOut_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecOut_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecOut_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecOut_Stdout) isExecOut_Msg() {}

func (*ExecOut_Stderr) isExecOut_Msg() {}

func (*ExecOut_Exit) isExecOut_Msg() {}

type ExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{4}
}

func (x *ExecExit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExecExit) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ResolveExecCommand returns the argv the server would exec to reach the instance
// interactively, so the CLIENT can exec it locally and inherit the user's TTY.
type ResolveExecCommandRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// command to run inside; empty means "interactive login shell".
	Argv          []string `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveExecCommandRequest) Reset() {
	*x = ResolveExecCommandRequest{}
	mi := &file_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveExecCommandRequest) ProtoMessage() {}

func (x *ResolveExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ResolveExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveExecCommandRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ResolveExecCommandRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ResolveExecCommandRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type ResolveExecCommandReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv[0] is the program (e.g. devcontainer/docker/ssh); the client execs this
	// directly with inherited stdio.
	Argv          []string          `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	Env           map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveExecCommandReply) Reset() {
	*x = ResolveExecCommandReply{}
	mi := &file_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveExecCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveExecCommandReply) ProtoMessage() {}

func (x *ResolveExecCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveExecCommandReply.ProtoReflect.Descriptor instead.
func (*ResolveExecCommandReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveExecCommandReply) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ResolveExecCommandReply) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          *int32                 `protobuf:"varint,4,opt,name=tail,proto3,oneof" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{7}
}

func (x *LogsRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *LogsRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil && x.Tail != nil {
		return *x.Tail
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_exec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{8}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// Forward is the port-forward DATA PLANE: one bidi stream per accepted TCP
// connection. The CLIENT owns the listen half (an in-process TCP proxy on
// local_port); the SERVER owns the bridge into the container; this stream is
// the pipe between them — so forwarding holds even when the server is remote
// (the old PortForward descriptor RPC assumed client host == server host).
//
// The FIRST client frame MUST carry `open` (fleet, instance, remote_port);
// every subsequent frame (both directions) carries raw bytes in `data`.
// Half-close maps naturally: the client ends its upload by closing its send
// side (CloseSend); the server signals remote EOF by ending the stream.
type ForwardChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ForwardChunk_Open
	//	*ForwardChunk_Data
	Msg           isForwardChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardChunk) Reset() {
	*x = ForwardChunk{}
	mi := &file_exec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardChunk) ProtoMessage() {}

func (x *ForwardChunk) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardChunk.ProtoReflect.Descriptor instead.
func (*ForwardChunk) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardChunk) GetMsg() isForwardChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ForwardChunk) GetOpen() *ForwardOpen {
	if x != nil {
		if x, ok := x.Msg.(*ForwardChunk_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ForwardChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ForwardChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isForwardChunk_Msg interface {
	isForwardChunk_Msg()
}

type ForwardChunk_Open struct {
	Open *ForwardOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ForwardChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ForwardChunk_Open) isForwardChunk_Msg() {}

func (*ForwardChunk_Data) isForwardChunk_Msg() {}

// ForwardOpen is the setup header for one forwarded connection: which
// instance to bridge into and the port to reach inside it. There is no
// local_port — the listen side is entirely the client's business.
type ForwardOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	RemotePort    int32                  `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardOpen) Reset() {
	*x = ForwardOpen{}
	mi := &file_exec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOpen) ProtoMessage() {}

func (x *ForwardOpen) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOpen.ProtoReflect.Descriptor instead.
func (*ForwardOpen) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{10}
}

func (x *ForwardOpen) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ForwardOpen) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ForwardOpen) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

// CopyFile streams a file OR directory out of an instance to the client (the
// `fleet copy` / in-instance `fc` feature). The server reads through the backend
// (a tar pipe over container exec) and streams it back: the FIRST chunk carries
// `meta`, every following chunk carries `data`. For a file the data is the raw
// bytes; for a directory (meta.is_dir) it is a tar the client extracts in Go.
// Works unchanged over the remote gateway, which is the headline use case:
// pulling a built binary out of a fully remote deployment onto the local machine.
type CopyFileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// path of the file inside the instance. A relative path resolves against the
	// workspace folder (the backend exec working directory).
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_exec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{11}
}

func (x *CopyFileRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *CopyFileRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CopyFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CopyFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CopyFileChunk_Meta
	//	*CopyFileChunk_Data
	Msg           isCopyFileChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileChunk) Reset() {
	*x = CopyFileChunk{}
	mi := &file_exec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileChunk) ProtoMessage() {}

func (x *CopyFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileChunk.ProtoReflect.Descriptor instead.
func (*CopyFileChunk) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{12}
}

func (x *CopyFileChunk) GetMsg() isCopyFileChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CopyFileChunk) GetMeta() *CopyFileMeta {
	if x != nil {
		if x, ok := x.Msg.(*CopyFileChunk_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *CopyFileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*CopyFileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isCopyFileChunk_Msg interface {
	isCopyFileChunk_Msg()
}

type CopyFileChunk_Meta struct {
	Meta *CopyFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type CopyFileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CopyFileChunk_Meta) isCopyFileChunk_Msg() {}

func (*CopyFileChunk_Data) isCopyFileChunk_Msg() {}

type CopyFileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the source's basename — the default local name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// mode is the source file's permission bits (so an executable stays runnable).
	// Unused when is_dir.
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// size is the file's byte count. Unused when is_dir.
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// is_dir marks a recursive directory copy: the data frames then carry a tar of
	// the directory (`tar -C <path> -cf - .`) instead of raw file bytes, and the
	// client extracts it in Go — skipping symlinks/special files and the `./` root
	// entry, sanitizing entry names. mode/size are unused.
	IsDir         bool `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileMeta) Reset() {
	*x = CopyFileMeta{}
	mi := &file_exec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileMeta) ProtoMessage() {}

func (x *CopyFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileMeta.ProtoReflect.Descriptor instead.
func (*CopyFileMeta) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{13}
}

func (x *CopyFileMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CopyFileMeta) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyFileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CopyFileMeta) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

// CopyInto streams a file OR directory INTO an instance — the reverse of
// CopyFile, the other half of scp-style `fleet copy`. It is CLIENT-streaming: the
// FIRST chunk MUST carry `open` (which instance, the destination, and the
// source's name/mode/size or is_dir); every following chunk carries `data`. The
// server resolves the destination inside the container and writes through the
// backend with a `tar -xf -` exec. For a file the data is the raw bytes (written
// atomically via a temp name + rename); for a directory (open.is_dir) it is a tar
// of the directory's contents extracted in place. Works unchanged over the remote
// gateway: pushing a local file or tree into a fully remote deployment.
type CopyIntoChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CopyIntoChunk_Open
	//	*CopyIntoChunk_Data
	Msg           isCopyIntoChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyIntoChunk) Reset() {
	*x = CopyIntoChunk{}
	mi := &file_exec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyIntoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyIntoChunk) ProtoMessage() {}

func (x *CopyIntoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyIntoChunk.ProtoReflect.Descriptor instead.
func (*CopyIntoChunk) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{14}
}

func (x *CopyIntoChunk) GetMsg() isCopyIntoChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CopyIntoChunk) GetOpen() *CopyIntoOpen {
	if x != nil {
		if x, ok := x.Msg.(*CopyIntoChunk_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *CopyIntoChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*CopyIntoChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isCopyIntoChunk_Msg interface {
	isCopyIntoChunk_Msg()
}

type CopyIntoChunk_Open struct {
	Open *CopyIntoOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type CopyIntoChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CopyIntoChunk_Open) isCopyIntoChunk_Msg() {}

func (*CopyIntoChunk_Data) isCopyIntoChunk_Msg() {}

type CopyIntoOpen struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// dest is the destination path inside the instance. A relative path resolves
	// against the workspace folder (the backend exec working directory). When it
	// names (or is) an existing directory the file keeps `name`; otherwise dest is
	// the full target path. Empty means the workspace folder.
	Dest string `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	// name is the source file's basename — used when dest resolves to a directory.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// mode is the file's permission bits to set on the written file (the perm bits
	// are honoured; a 0 mode defaults to 0644). setuid/setgid/sticky are stripped.
	// Unused when is_dir.
	Mode uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	// size is the source file's byte count — needed up front for the tar header,
	// and enforced as a hard cap so a truncated or oversized stream fails cleanly
	// rather than leaving a partial file. Unused when is_dir.
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// is_dir marks a recursive directory copy: the data frames then carry a tar of
	// the directory's CONTENTS (entries relative to the dir root, no symlinks or
	// special files, built by the client in Go), and the server resolves a target
	// directory and extracts it there with `tar -xf -` (an in-place merge, like
	// `cp -r`). mode/size are unused. NOT supported on the codespaces backend (its
	// exec PTY can silently corrupt a binary tar) — a FailedPrecondition there.
	IsDir         bool `protobuf:"varint,7,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyIntoOpen) Reset() {
	*x = CopyIntoOpen{}
	mi := &file_exec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyIntoOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyIntoOpen) ProtoMessage() {}

func (x *CopyIntoOpen) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyIntoOpen.ProtoReflect.Descriptor instead.
func (*CopyIntoOpen) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{15}
}

func (x *CopyIntoOpen) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *CopyIntoOpen) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CopyIntoOpen) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *CopyIntoOpen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CopyIntoOpen) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyIntoOpen) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CopyIntoOpen) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type CopyIntoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the final absolute path written inside the instance.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// written is the number of file bytes received and written.
	Written       int64 `protobuf:"varint,2,opt,name=written,proto3" json:"written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyIntoReply) Reset() {
	*x = CopyIntoReply{}
	mi := &file_exec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyIntoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyIntoReply) ProtoMessage() {}

func (x *CopyIntoReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyIntoReply.ProtoReflect.Descriptor instead.
func (*CopyIntoReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{16}
}

func (x *CopyIntoReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyIntoReply) GetWritten() int64 {
	if x != nil {
		return x.Written
	}
	return 0
}

// ResolveLogsCommand returns the host-side command argv the server would run to
// show an instance's container runtime logs. The client embeds it in its own
// pager script (cat the creation log, then the runtime logs) and runs it
// locally — the analog of ResolveExecCommand for the `l` logs view.
type ResolveLogsCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLogsCommandRequest) Reset() {
	*x = ResolveLogsCommandRequest{}
	mi := &file_exec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLogsCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLogsCommandRequest) ProtoMessage() {}

func (x *ResolveLogsCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLogsCommandRequest.ProtoReflect.Descriptor instead.
func (*ResolveLogsCommandRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveLogsCommandRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ResolveLogsCommandRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type ResolveLogsCommandReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argv          []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLogsCommandReply) Reset() {
	*x = ResolveLogsCommandReply{}
	mi := &file_exec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLogsCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLogsCommandReply) ProtoMessage() {}

func (x *ResolveLogsCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLogsCommandReply.ProtoReflect.Descriptor instead.
func (*ResolveLogsCommandReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveLogsCommandReply) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

// TriggerLogs reads back an automation trigger's recorded event logs. Each time
// a trigger fires, the daemon writes the firing's payload (the webhook body, or
// the schedule fire-time) to a per-trigger log directory, keeping the most
// recent 100. This returns them concatenated (oldest first), so a client can
// inspect what fired an automation after the fact — the TUI's 'L' pager, the
// `fleet trigger logs` CLI, and the fleet_trigger_logs MCP tool all read here.
// A trigger that has never fired returns empty logs with count 0 (not an error).
type TriggerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLogsRequest) Reset() {
	*x = TriggerLogsRequest{}
	mi := &file_exec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLogsRequest) ProtoMessage() {}

func (x *TriggerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLogsRequest.ProtoReflect.Descriptor instead.
func (*TriggerLogsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{19}
}

func (x *TriggerLogsRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *TriggerLogsRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type TriggerLogsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// logs is every recorded event log concatenated (oldest first), each preceded
	// by a "===== event-<timestamp>.log =====" separator. Empty when none recorded.
	Logs string `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	// count is how many event logs were concatenated.
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLogsReply) Reset() {
	*x = TriggerLogsReply{}
	mi := &file_exec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLogsReply) ProtoMessage() {}

func (x *TriggerLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLogsReply.ProtoReflect.Descriptor instead.
func (*TriggerLogsReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{20}
}

func (x *TriggerLogsReply) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *TriggerLogsReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetCoderTemplateParams fetches a Coder template's active-version rich
// parameters + preset names (the TUI's coder settings dialog used to call the
// coder backend's REST helpers directly). The server owns backend access.
type GetCoderTemplateParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoderTemplateParamsRequest) Reset() {
	*x = GetCoderTemplateParamsRequest{}
	mi := &file_exec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoderTemplateParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoderTemplateParamsRequest) ProtoMessage() {}

func (x *GetCoderTemplateParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoderTemplateParamsRequest.ProtoReflect.Descriptor instead.
func (*GetCoderTemplateParamsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{21}
}

func (x *GetCoderTemplateParamsRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

// CoderRichParameter is the subset of a Coder rich parameter the TUI renders /
// stores (mirrors internal/backend/coder.RichParameter, minus options/required/
// mutable which the settings dialog doesn't use).
type CoderRichParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoderRichParameter) Reset() {
	*x = CoderRichParameter{}
	mi := &file_exec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoderRichParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoderRichParameter) ProtoMessage() {}

func (x *CoderRichParameter) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoderRichParameter.ProtoReflect.Descriptor instead.
func (*CoderRichParameter) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{22}
}

func (x *CoderRichParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CoderRichParameter) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CoderRichParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CoderRichParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CoderRichParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type GetCoderTemplateParamsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*CoderRichParameter  `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Presets       []string               `protobuf:"bytes,2,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoderTemplateParamsReply) Reset() {
	*x = GetCoderTemplateParamsReply{}
	mi := &file_exec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoderTemplateParamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoderTemplateParamsReply) ProtoMessage() {}

func (x *GetCoderTemplateParamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoderTemplateParamsReply.ProtoReflect.Descriptor instead.
func (*GetCoderTemplateParamsReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{23}
}

func (x *GetCoderTemplateParamsReply) GetParameters() []*CoderRichParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GetCoderTemplateParamsReply) GetPresets() []string {
	if x != nil {
		return x.Presets
	}
	return nil
}

// GetBrowserConfig reads the workspace's devcontainer.json fleet customization
// so the TUI can decide whether to show the launch chooser (both an initial URL
// and a landing page are configured).
type GetBrowserConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrowserConfigRequest) Reset() {
	*x = GetBrowserConfigRequest{}
	mi := &file_exec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrowserConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserConfigRequest) ProtoMessage() {}

func (x *GetBrowserConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBrowserConfigRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{24}
}

func (x *GetBrowserConfigRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *GetBrowserConfigRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type GetBrowserConfigReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// initial_url is customizations.fleet.browser.initialUrl ("" if unset).
	InitialUrl string `protobuf:"bytes,1,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
	// has_landing is true when a Fleet Launch landing page is configured.
	HasLanding    bool `protobuf:"varint,2,opt,name=has_landing,json=hasLanding,proto3" json:"has_landing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrowserConfigReply) Reset() {
	*x = GetBrowserConfigReply{}
	mi := &file_exec_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrowserConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserConfigReply) ProtoMessage() {}

func (x *GetBrowserConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserConfigReply.ProtoReflect.Descriptor instead.
func (*GetBrowserConfigReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{25}
}

func (x *GetBrowserConfigReply) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

func (x *GetBrowserConfigReply) GetHasLanding() bool {
	if x != nil {
		return x.HasLanding
	}
	return false
}

// PrepareBrowser does all the container-side work for a browser open: ensure the
// privoxy proxy is installed + running, then resolve the page to open —
// honouring an explicit target_url, else the devcontainer.json initialUrl /
// Fleet Launch landing page (starting the landing-page server when chosen) /
// the default. It returns the URL the client's browser should open.
type PrepareBrowserRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// prefer_fleet_launch is the fleet's resolved PreferFleetLaunch setting (the
	// tie-breaker when both an initial URL and a landing page are configured).
	PreferFleetLaunch bool `protobuf:"varint,3,opt,name=prefer_fleet_launch,json=preferFleetLaunch,proto3" json:"prefer_fleet_launch,omitempty"`
	// target_url, when set, is used verbatim (a control-socket browser.open
	// request already chose the URL) and config/landing resolution is skipped.
	TargetUrl     *string `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3,oneof" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareBrowserRequest) Reset() {
	*x = PrepareBrowserRequest{}
	mi := &file_exec_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBrowserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBrowserRequest) ProtoMessage() {}

func (x *PrepareBrowserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBrowserRequest.ProtoReflect.Descriptor instead.
func (*PrepareBrowserRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{26}
}

func (x *PrepareBrowserRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *PrepareBrowserRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *PrepareBrowserRequest) GetPreferFleetLaunch() bool {
	if x != nil {
		return x.PreferFleetLaunch
	}
	return false
}

func (x *PrepareBrowserRequest) GetTargetUrl() string {
	if x != nil && x.TargetUrl != nil {
		return *x.TargetUrl
	}
	return ""
}

type PrepareBrowserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialUrl    string                 `protobuf:"bytes,1,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareBrowserReply) Reset() {
	*x = PrepareBrowserReply{}
	mi := &file_exec_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBrowserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBrowserReply) ProtoMessage() {}

func (x *PrepareBrowserReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBrowserReply.ProtoReflect.Descriptor instead.
func (*PrepareBrowserReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{27}
}

func (x *PrepareBrowserReply) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\tfleetgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\x06ExecIn\x12,\n" +
	"\x05start\x18\x01 \x01(\v2\x14.fleetgrpc.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12/\n" +
	"\x06resize\x18\x03 \x01(\v2\x15.fleetgrpc.ExecResizeH\x00R\x06resizeB\x05\n" +
	"\x03msg\"\xcc\x01\n" +
	"\tExecStart\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.fleetgrpc.ExecStart.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"o\n" +
	"\aExecOut\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12)\n" +
	"\x04exit\x18\x03 \x01(\v2\x13.fleetgrpc.ExecExitH\x00R\x04exitB\x05\n" +
	"\x03msg\"C\n" +
	"\bExecExit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"a\n" +
	"\x19ResolveExecCommandRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\"\xa4\x01\n" +
	"\x17ResolveExecCommandReply\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12=\n" +
	"\x03env\x18\x02 \x03(\v2+.fleetgrpc.ResolveExecCommandReply.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\vLogsRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x17\n" +
	"\x04tail\x18\x04 \x01(\x05H\x00R\x04tail\x88\x01\x01B\a\n" +
	"\x05_tail\"I\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"Y\n" +
	"\fForwardChunk\x12,\n" +
	"\x04open\x18\x01 \x01(\v2\x16.fleetgrpc.ForwardOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"`\n" +
	"\vForwardOpen\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\x05R\n" +
	"remotePort\"W\n" +
	"\x0fCopyFileRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"[\n" +
	"\rCopyFileChunk\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x17.fleetgrpc.CopyFileMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"a\n" +
	"\fCopyFileMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\"[\n" +
	"\rCopyIntoChunk\x12-\n" +
	"\x04open\x18\x01 \x01(\v2\x17.fleetgrpc.CopyIntoOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"\xa7\x01\n" +
	"\fCopyIntoOpen\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\tR\x04dest\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\a \x01(\bR\x05isDir\"=\n" +
	"\rCopyIntoReply\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\awritten\x18\x02 \x01(\x03R\awritten\"M\n" +
	"\x19ResolveLogsCommandRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"-\n" +
	"\x17ResolveLogsCommandReply\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\"D\n" +
	"\x12TriggerLogsRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\"<\n" +
	"\x10TriggerLogsReply\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\";\n" +
	"\x1dGetCoderTemplateParamsRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\"\xa6\x01\n" +
	"\x12CoderRichParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\"v\n" +
	"\x1bGetCoderTemplateParamsReply\x12=\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1d.fleetgrpc.CoderRichParameterR\n" +
	"parameters\x12\x18\n" +
	"\apresets\x18\x02 \x03(\tR\apresets\"K\n" +
	"\x17GetBrowserConfigRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"Y\n" +
	"\x15GetBrowserConfigReply\x12\x1f\n" +
	"\vinitial_url\x18\x01 \x01(\tR\n" +
	"initialUrl\x12\x1f\n" +
	"\vhas_landing\x18\x02 \x01(\bR\n" +
	"hasLanding\"\xac\x01\n" +
	"\x15PrepareBrowserRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12.\n" +
	"\x13prefer_fleet_launch\x18\x03 \x01(\bR\x11preferFleetLaunch\x12\"\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tH\x00R\ttargetUrl\x88\x01\x01B\r\n" +
	"\v_target_url\"6\n" +
	"\x13PrepareBrowserReply\x12\x1f\n" +
	"\vinitial_url\x18\x01 \x01(\tR\n" +
	"initialUrlB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_exec_proto_goTypes = []any{
	(*ExecIn)(nil),                        // 0: fleetgrpc.ExecIn
	(*ExecStart)(nil),                     // 1: fleetgrpc.ExecStart
	(*ExecResize)(nil),                    // 2: fleetgrpc.ExecResize
	(*ExecOut)(nil),                       // 3: fleetgrpc.ExecOut
	(*ExecExit)(nil),                      // 4: fleetgrpc.ExecExit
	(*ResolveExecCommandRequest)(nil),     // 5: fleetgrpc.ResolveExecCommandRequest
	(*ResolveExecCommandReply)(nil),       // 6: fleetgrpc.ResolveExecCommandReply
	(*LogsRequest)(nil),                   // 7: fleetgrpc.LogsRequest
	(*LogLine)(nil),                       // 8: fleetgrpc.LogLine
	(*ForwardChunk)(nil),                  // 9: fleetgrpc.ForwardChunk
	(*ForwardOpen)(nil),                   // 10: fleetgrpc.ForwardOpen
	(*CopyFileRequest)(nil),               // 11: fleetgrpc.CopyFileRequest
	(*CopyFileChunk)(nil),                 // 12: fleetgrpc.CopyFileChunk
	(*CopyFileMeta)(nil),                  // 13: fleetgrpc.CopyFileMeta
	(*CopyIntoChunk)(nil),                 // 14: fleetgrpc.CopyIntoChunk
	(*CopyIntoOpen)(nil),                  // 15: fleetgrpc.CopyIntoOpen
	(*CopyIntoReply)(nil),                 // 16: fleetgrpc.CopyIntoReply
	(*ResolveLogsCommandRequest)(nil),     // 17: fleetgrpc.ResolveLogsCommandRequest
	(*ResolveLogsCommandReply)(nil),       // 18: fleetgrpc.ResolveLogsCommandReply
	(*TriggerLogsRequest)(nil),            // 19: fleetgrpc.TriggerLogsRequest
	(*TriggerLogsReply)(nil),              // 20: fleetgrpc.TriggerLogsReply
	(*GetCoderTemplateParamsRequest)(nil), // 21: fleetgrpc.GetCoderTemplateParamsRequest
	(*CoderRichParameter)(nil),            // 22: fleetgrpc.CoderRichParameter
	(*GetCoderTemplateParamsReply)(nil),   // 23: fleetgrpc.GetCoderTemplateParamsReply
	(*GetBrowserConfigRequest)(nil),       // 24: fleetgrpc.GetBrowserConfigRequest
	(*GetBrowserConfigReply)(nil),         // 25: fleetgrpc.GetBrowserConfigReply
	(*PrepareBrowserRequest)(nil),         // 26: fleetgrpc.PrepareBrowserRequest
	(*PrepareBrowserReply)(nil),           // 27: fleetgrpc.PrepareBrowserReply
	nil,                                   // 28: fleetgrpc.ExecStart.EnvEntry
	nil,                                   // 29: fleetgrpc.ResolveExecCommandReply.EnvEntry
	(*timestamppb.Timestamp)(nil),         // 30: google.protobuf.Timestamp
}
var file_exec_proto_depIdxs = []int32{
	1,  // 0: fleetgrpc.ExecIn.start:type_name -> fleetgrpc.ExecStart
	2,  // 1: fleetgrpc.ExecIn.resize:type_name -> fleetgrpc.ExecResize
	28, // 2: fleetgrpc.ExecStart.env:type_name -> fleetgrpc.ExecStart.EnvEntry
	4,  // 3: fleetgrpc.ExecOut.exit:type_name -> fleetgrpc.ExecExit
	29, // 4: fleetgrpc.ResolveExecCommandReply.env:type_name -> fleetgrpc.ResolveExecCommandReply.EnvEntry
	30, // 5: fleetgrpc.LogLine.at:type_name -> google.protobuf.Timestamp
	10, // 6: fleetgrpc.ForwardChunk.open:type_name -> fleetgrpc.ForwardOpen
	13, // 7: fleetgrpc.CopyFileChunk.meta:type_name -> fleetgrpc.CopyFileMeta
	15, // 8: fleetgrpc.CopyIntoChunk.open:type_name -> fleetgrpc.CopyIntoOpen
	22, // 9: fleetgrpc.GetCoderTemplateParamsReply.parameters:type_name -> fleetgrpc.CoderRichParameter
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	file_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecIn_Start)(nil),
		(*ExecIn_Stdin)(nil),
		(*ExecIn_Resize)(nil),
	}
	file_exec_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecOut_Stdout)(nil),
		(*ExecOut_Stderr)(nil),
		(*ExecOut_Exit)(nil),
	}
	file_exec_proto_msgTypes[4].OneofWrappers = []any{}
	file_exec_proto_msgTypes[7].OneofWrappers = []any{}
	file_exec_proto_msgTypes[9].OneofWrappers = []any{
		(*ForwardChunk_Open)(nil),
		(*ForwardChunk_Data)(nil),
	}
	file_exec_proto_msgTypes[12].OneofWrappers = []any{
		(*CopyFileChunk_Meta)(nil),
		(*CopyFileChunk_Data)(nil),
	}
	file_exec_proto_msgTypes[14].OneofWrappers = []any{
		(*CopyIntoChunk_Open)(nil),
		(*CopyIntoChunk_Data)(nil),
	}
	file_exec_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
