// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exec.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Exec is a bidi stream for running a command inside an instance's container and
// piping stdin/stdout/stderr. The FIRST ExecIn MUST carry `start`; subsequent
// ExecIn carry stdin bytes (or resize). The server replies with ExecOut frames
// and a terminal `exit`.
//
// TTY CARVE-OUT: for interactive TTY attach (`fleet shell`, the TUI's tea.Exec),
// piping a full PTY over gRPC for a LOCAL user is wasteful — the terminal is on
// the client. For those, use ResolveExecCommand: the SERVER returns the
// ready-to-exec argv and the CLIENT execs it locally to inherit the user's TTY.
// Client-local exec for TTY attach is a PERMITTED client-host action, NOT a
// boundary violation.
type ExecIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecIn_Start
	//	*ExecIn_Stdin
	//	*ExecIn_Resize
	Msg           isExecIn_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecIn) Reset() {
	*x = ExecIn{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecIn) ProtoMessage() {}

func (x *ExecIn) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecIn.ProtoReflect.Descriptor instead.
func (*ExecIn) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecIn) GetMsg() isExecIn_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecIn) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecIn) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecIn) GetResize() *ExecResize {
	if x != nil {
		if x, ok := x.Msg.(*ExecIn_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecIn_Msg interface {
	isExecIn_Msg()
}

type ExecIn_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecIn_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecIn_Resize struct {
	Resize *ExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ExecIn_Start) isExecIn_Msg() {}

func (*ExecIn_Stdin) isExecIn_Msg() {}

func (*ExecIn_Resize) isExecIn_Msg() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Argv          []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecStart) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ExecStart) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ExecStart) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{2}
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ExecOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExecOut_Stdout
	//	*ExecOut_Stderr
	//	*ExecOut_Exit
	Msg           isExecOut_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOut) Reset() {
	*x = ExecOut{}
	mi := &file_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOut) ProtoMessage() {}

func (x *ExecOut) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOut.ProtoReflect.Descriptor instead.
func (*ExecOut) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{3}
}

func (x *ExecOut) GetMsg() isExecOut_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExecOut) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecOut) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecOut) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Msg.(*ExecOut_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecOut_Msg interface {
	isExecOut_Msg()
}

type ExecOut_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecOut_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecOut_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecOut_Stdout) isExecOut_Msg() {}

func (*ExecOut_Stderr) isExecOut_Msg() {}

func (*ExecOut_Exit) isExecOut_Msg() {}

type ExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{4}
}

func (x *ExecExit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExecExit) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ResolveExecCommand returns the argv the server would exec to reach the instance
// interactively, so the CLIENT can exec it locally and inherit the user's TTY.
type ResolveExecCommandRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// command to run inside; empty means "interactive login shell".
	Argv          []string `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveExecCommandRequest) Reset() {
	*x = ResolveExecCommandRequest{}
	mi := &file_exec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveExecCommandRequest) ProtoMessage() {}

func (x *ResolveExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ResolveExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveExecCommandRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ResolveExecCommandRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ResolveExecCommandRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

type ResolveExecCommandReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv[0] is the program (e.g. devcontainer/docker/ssh); the client execs this
	// directly with inherited stdio.
	Argv          []string          `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	Env           map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveExecCommandReply) Reset() {
	*x = ResolveExecCommandReply{}
	mi := &file_exec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveExecCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveExecCommandReply) ProtoMessage() {}

func (x *ResolveExecCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveExecCommandReply.ProtoReflect.Descriptor instead.
func (*ResolveExecCommandReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveExecCommandReply) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ResolveExecCommandReply) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          *int32                 `protobuf:"varint,4,opt,name=tail,proto3,oneof" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_exec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{7}
}

func (x *LogsRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *LogsRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil && x.Tail != nil {
		return *x.Tail
	}
	return 0
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_exec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{8}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// Forward is the port-forward DATA PLANE: one bidi stream per accepted TCP
// connection. The CLIENT owns the listen half (an in-process TCP proxy on
// local_port); the SERVER owns the bridge into the container; this stream is
// the pipe between them — so forwarding holds even when the server is remote
// (the old PortForward descriptor RPC assumed client host == server host).
//
// The FIRST client frame MUST carry `open` (fleet, instance, remote_port);
// every subsequent frame (both directions) carries raw bytes in `data`.
// Half-close maps naturally: the client ends its upload by closing its send
// side (CloseSend); the server signals remote EOF by ending the stream.
type ForwardChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ForwardChunk_Open
	//	*ForwardChunk_Data
	Msg           isForwardChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardChunk) Reset() {
	*x = ForwardChunk{}
	mi := &file_exec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardChunk) ProtoMessage() {}

func (x *ForwardChunk) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardChunk.ProtoReflect.Descriptor instead.
func (*ForwardChunk) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardChunk) GetMsg() isForwardChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ForwardChunk) GetOpen() *ForwardOpen {
	if x != nil {
		if x, ok := x.Msg.(*ForwardChunk_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ForwardChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ForwardChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isForwardChunk_Msg interface {
	isForwardChunk_Msg()
}

type ForwardChunk_Open struct {
	Open *ForwardOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ForwardChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ForwardChunk_Open) isForwardChunk_Msg() {}

func (*ForwardChunk_Data) isForwardChunk_Msg() {}

// ForwardOpen is the setup header for one forwarded connection: which
// instance to bridge into and the port to reach inside it. There is no
// local_port — the listen side is entirely the client's business.
type ForwardOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	RemotePort    int32                  `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardOpen) Reset() {
	*x = ForwardOpen{}
	mi := &file_exec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOpen) ProtoMessage() {}

func (x *ForwardOpen) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOpen.ProtoReflect.Descriptor instead.
func (*ForwardOpen) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{10}
}

func (x *ForwardOpen) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ForwardOpen) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ForwardOpen) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

// Mic is the virtual-microphone DATA PLANE: one bidi stream per microphone-
// providing client (a TUI on the machine the human — and their mic — sits at).
// The CLIENT owns capture; the SERVER owns the per-instance sinks that feed each
// instance's virtual audio source. Because the audio rides this stream, the mic
// follows the client even when the server is remote, exactly like Forward.
//
// Capture is ON DEMAND: the server tells the client when something inside an
// instance starts/stops recording (MicDemand) and the client only opens the
// real microphone while demand is active — the mic is never streamed idle.
//
// The FIRST client frame MUST carry `open`; every later client frame carries
// raw PCM in `audio`, in the format the open header declared.
type MicUp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MicUp_Open
	//	*MicUp_Audio
	Msg           isMicUp_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicUp) Reset() {
	*x = MicUp{}
	mi := &file_exec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicUp) ProtoMessage() {}

func (x *MicUp) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicUp.ProtoReflect.Descriptor instead.
func (*MicUp) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{11}
}

func (x *MicUp) GetMsg() isMicUp_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MicUp) GetOpen() *MicOpen {
	if x != nil {
		if x, ok := x.Msg.(*MicUp_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *MicUp) GetAudio() []byte {
	if x != nil {
		if x, ok := x.Msg.(*MicUp_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isMicUp_Msg interface {
	isMicUp_Msg()
}

type MicUp_Open struct {
	Open *MicOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type MicUp_Audio struct {
	Audio []byte `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

func (*MicUp_Open) isMicUp_Msg() {}

func (*MicUp_Audio) isMicUp_Msg() {}

// MicOpen declares the PCM format the client will send. Samples are always
// signed 16-bit little-endian; the server currently accepts exactly 16 kHz mono
// (the in-instance source's native format) and rejects anything else, so a
// future format change fails loudly rather than playing back as noise.
type MicOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRate    uint32                 `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      uint32                 `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicOpen) Reset() {
	*x = MicOpen{}
	mi := &file_exec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicOpen) ProtoMessage() {}

func (x *MicOpen) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicOpen.ProtoReflect.Descriptor instead.
func (*MicOpen) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{12}
}

func (x *MicOpen) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *MicOpen) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type MicDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MicDown_Demand
	Msg           isMicDown_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicDown) Reset() {
	*x = MicDown{}
	mi := &file_exec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicDown) ProtoMessage() {}

func (x *MicDown) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicDown.ProtoReflect.Descriptor instead.
func (*MicDown) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{13}
}

func (x *MicDown) GetMsg() isMicDown_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MicDown) GetDemand() *MicDemand {
	if x != nil {
		if x, ok := x.Msg.(*MicDown_Demand); ok {
			return x.Demand
		}
	}
	return nil
}

type isMicDown_Msg interface {
	isMicDown_Msg()
}

type MicDown_Demand struct {
	Demand *MicDemand `protobuf:"bytes,1,opt,name=demand,proto3,oneof"`
}

func (*MicDown_Demand) isMicDown_Msg() {}

// MicDemand is the server's start/stop signal. active=true means at least one
// instance has a recorder attached to its virtual microphone; `instances` names
// them ("<fleet>/<instance>") so the client can show WHO is listening. A stream
// that has been superseded by a newer provider gets a final active=false.
type MicDemand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Active    bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Instances []string               `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	// device is the capture device chosen in Settings (MicSettings.device; empty
	// = system default), pushed with every demand so a provider never has to ask:
	// the daemon owns the config, and a lookup at capture start would sit on the
	// one path where every millisecond is clipped off the user's sentence. A
	// device-only change republishes the demand, so it reaches a running provider
	// at once rather than at its next recording. It is an id from SOME client's
	// enumeration — the provider validates it against its own machine.
	Device        string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicDemand) Reset() {
	*x = MicDemand{}
	mi := &file_exec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicDemand) ProtoMessage() {}

func (x *MicDemand) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicDemand.ProtoReflect.Descriptor instead.
func (*MicDemand) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{14}
}

func (x *MicDemand) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MicDemand) GetInstances() []string {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *MicDemand) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

// SSHAgent is the SSH-agent forwarding DATA PLANE: one bidi stream per
// agent-providing client (a TUI or CLI on the machine where the human's
// ssh-agent runs). The SERVER owns the agent sockets processes on its host use
// (its own git clone, and one per devcontainer instance); every connection to
// one of them is relayed over this stream to a provider, which splices it onto
// its local SSH_AUTH_SOCK. Because the bytes ride this stream, the keys follow
// the client even when the server is remote — like `ssh -A`, but for
// everything the daemon runs — and they are gone the moment the client leaves.
//
// A connection goes to the newest attached provider that can serve it —
// non-yielding ones before yielding ones, skipping any that stopped answering
// pings (one whose machine has no reachable agent answers `close` with an
// error and the next one is tried); if none can, to the agent the daemon
// itself was started with. Only listing keys and signing reach the agent
// (plus the session-bind / query extensions); every other request (add/remove
// keys, lock, loading PKCS#11 or security-key providers) is answered with a
// failure without the agent seeing it, because a relayed connection reaches
// the agent as a LOCAL client and would otherwise get more than an `ssh -A`
// connection does. The provider also binds each connection as forwarded
// (session-bind@openssh.com, is_forwarding) so the agent applies its own
// remote-client rules and destination constraints.
//
// The FIRST client frame MUST carry `hello`. Connections are multiplexed by
// conn_id, which the server assigns: it announces each with `open`, the
// client answers `ready` once it has dialed its agent (or `close` with an
// error if it cannot), and from then on both sides exchange `data`. The
// server's `close` means the connection has sent its last request (possibly
// only a half-close): the provider still answers every request it received,
// then sends its own `close`. The provider's `close` ends the connection: the
// server delivers the replies already sent and closes it.
type SSHAgentUp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SSHAgentUp_Hello
	//	*SSHAgentUp_Ready
	//	*SSHAgentUp_Data
	//	*SSHAgentUp_Close
	//	*SSHAgentUp_Pong
	Msg           isSSHAgentUp_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentUp) Reset() {
	*x = SSHAgentUp{}
	mi := &file_exec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentUp) ProtoMessage() {}

func (x *SSHAgentUp) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentUp.ProtoReflect.Descriptor instead.
func (*SSHAgentUp) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{15}
}

func (x *SSHAgentUp) GetMsg() isSSHAgentUp_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SSHAgentUp) GetHello() *SSHAgentHello {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentUp_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *SSHAgentUp) GetReady() *SSHAgentReady {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentUp_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *SSHAgentUp) GetData() *SSHAgentData {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentUp_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *SSHAgentUp) GetClose() *SSHAgentClose {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentUp_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *SSHAgentUp) GetPong() *SSHAgentPong {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentUp_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isSSHAgentUp_Msg interface {
	isSSHAgentUp_Msg()
}

type SSHAgentUp_Hello struct {
	Hello *SSHAgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type SSHAgentUp_Ready struct {
	Ready *SSHAgentReady `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type SSHAgentUp_Data struct {
	Data *SSHAgentData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type SSHAgentUp_Close struct {
	Close *SSHAgentClose `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

type SSHAgentUp_Pong struct {
	Pong *SSHAgentPong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

func (*SSHAgentUp_Hello) isSSHAgentUp_Msg() {}

func (*SSHAgentUp_Ready) isSSHAgentUp_Msg() {}

func (*SSHAgentUp_Data) isSSHAgentUp_Msg() {}

func (*SSHAgentUp_Close) isSSHAgentUp_Msg() {}

func (*SSHAgentUp_Pong) isSSHAgentUp_Msg() {}

// SSHAgentHello registers the stream as a provider. client is a human label
// (the provider's hostname and role) for the daemon's log. yield marks a
// provider that should only be used when no non-yielding one can serve (a
// CLI command's, behind the TUI that may have started it): it is queued
// behind every non-yielding provider instead of becoming the newest.
type SSHAgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Yield         bool                   `protobuf:"varint,2,opt,name=yield,proto3" json:"yield,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentHello) Reset() {
	*x = SSHAgentHello{}
	mi := &file_exec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentHello) ProtoMessage() {}

func (x *SSHAgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentHello.ProtoReflect.Descriptor instead.
func (*SSHAgentHello) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{16}
}

func (x *SSHAgentHello) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *SSHAgentHello) GetYield() bool {
	if x != nil {
		return x.Yield
	}
	return false
}

// SSHAgentReady: the provider dialed its local agent for conn_id; the server
// may start relaying.
type SSHAgentReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentReady) Reset() {
	*x = SSHAgentReady{}
	mi := &file_exec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentReady) ProtoMessage() {}

func (x *SSHAgentReady) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentReady.ProtoReflect.Descriptor instead.
func (*SSHAgentReady) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{17}
}

func (x *SSHAgentReady) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

// SSHAgentPong answers an SSHAgentPing with its seq.
type SSHAgentPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentPong) Reset() {
	*x = SSHAgentPong{}
	mi := &file_exec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentPong) ProtoMessage() {}

func (x *SSHAgentPong) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentPong.ProtoReflect.Descriptor instead.
func (*SSHAgentPong) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{18}
}

func (x *SSHAgentPong) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SSHAgentDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SSHAgentDown_Open
	//	*SSHAgentDown_Data
	//	*SSHAgentDown_Close
	//	*SSHAgentDown_Status
	//	*SSHAgentDown_Ping
	Msg           isSSHAgentDown_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentDown) Reset() {
	*x = SSHAgentDown{}
	mi := &file_exec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentDown) ProtoMessage() {}

func (x *SSHAgentDown) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentDown.ProtoReflect.Descriptor instead.
func (*SSHAgentDown) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{19}
}

func (x *SSHAgentDown) GetMsg() isSSHAgentDown_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SSHAgentDown) GetOpen() *SSHAgentOpen {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentDown_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *SSHAgentDown) GetData() *SSHAgentData {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentDown_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *SSHAgentDown) GetClose() *SSHAgentClose {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentDown_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *SSHAgentDown) GetStatus() *SSHAgentStatus {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentDown_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *SSHAgentDown) GetPing() *SSHAgentPing {
	if x != nil {
		if x, ok := x.Msg.(*SSHAgentDown_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isSSHAgentDown_Msg interface {
	isSSHAgentDown_Msg()
}

type SSHAgentDown_Open struct {
	Open *SSHAgentOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type SSHAgentDown_Data struct {
	Data *SSHAgentData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type SSHAgentDown_Close struct {
	Close *SSHAgentClose `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

type SSHAgentDown_Status struct {
	Status *SSHAgentStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type SSHAgentDown_Ping struct {
	Ping *SSHAgentPing `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*SSHAgentDown_Open) isSSHAgentDown_Msg() {}

func (*SSHAgentDown_Data) isSSHAgentDown_Msg() {}

func (*SSHAgentDown_Close) isSSHAgentDown_Msg() {}

func (*SSHAgentDown_Status) isSSHAgentDown_Msg() {}

func (*SSHAgentDown_Ping) isSSHAgentDown_Msg() {}

// SSHAgentOpen announces a new agent connection. origin says who opened it:
// "<fleet>/<instance>" for a process inside an instance, "" for the daemon's
// own host-side work (a git clone).
type SSHAgentOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentOpen) Reset() {
	*x = SSHAgentOpen{}
	mi := &file_exec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentOpen) ProtoMessage() {}

func (x *SSHAgentOpen) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentOpen.ProtoReflect.Descriptor instead.
func (*SSHAgentOpen) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{20}
}

func (x *SSHAgentOpen) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *SSHAgentOpen) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

// SSHAgentData carries raw agent-protocol bytes for one connection.
type SSHAgentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentData) Reset() {
	*x = SSHAgentData{}
	mi := &file_exec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentData) ProtoMessage() {}

func (x *SSHAgentData) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentData.ProtoReflect.Descriptor instead.
func (*SSHAgentData) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{21}
}

func (x *SSHAgentData) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *SSHAgentData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// SSHAgentClose ends one side of a connection. error is set when the
// provider could not serve it at all (no reachable agent), so the server can
// try the next provider or its own agent rather than fail.
type SSHAgentClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentClose) Reset() {
	*x = SSHAgentClose{}
	mi := &file_exec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentClose) ProtoMessage() {}

func (x *SSHAgentClose) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentClose.ProtoReflect.Descriptor instead.
func (*SSHAgentClose) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{22}
}

func (x *SSHAgentClose) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *SSHAgentClose) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SSHAgentStatus tells a provider whether it is the newest one (tried first)
// or standing by behind a newer provider. Sent on attach and on changes.
type SSHAgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentStatus) Reset() {
	*x = SSHAgentStatus{}
	mi := &file_exec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentStatus) ProtoMessage() {}

func (x *SSHAgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentStatus.ProtoReflect.Descriptor instead.
func (*SSHAgentStatus) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{23}
}

func (x *SSHAgentStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// SSHAgentPing is the server's liveness probe: a provider that does not answer
// with a pong is skipped (a laptop that went to sleep must not stall every
// agent use on the host until TCP gives up) until it answers again.
type SSHAgentPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHAgentPing) Reset() {
	*x = SSHAgentPing{}
	mi := &file_exec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAgentPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAgentPing) ProtoMessage() {}

func (x *SSHAgentPing) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAgentPing.ProtoReflect.Descriptor instead.
func (*SSHAgentPing) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{24}
}

func (x *SSHAgentPing) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// CopyFile streams a file OR directory out of an instance to the client (the
// `fleet copy` / in-instance `fc` feature). The server reads through the backend
// (a tar pipe over container exec) and streams it back: the FIRST chunk carries
// `meta`, every following chunk carries `data`. For a file the data is the raw
// bytes; for a directory (meta.is_dir) it is a tar the client extracts in Go.
// Works unchanged over the remote gateway, which is the headline use case:
// pulling a built binary out of a fully remote deployment onto the local machine.
type CopyFileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// path of the file inside the instance. A relative path resolves against the
	// workspace folder (the backend exec working directory).
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_exec_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{25}
}

func (x *CopyFileRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *CopyFileRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CopyFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CopyFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CopyFileChunk_Meta
	//	*CopyFileChunk_Data
	Msg           isCopyFileChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileChunk) Reset() {
	*x = CopyFileChunk{}
	mi := &file_exec_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileChunk) ProtoMessage() {}

func (x *CopyFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileChunk.ProtoReflect.Descriptor instead.
func (*CopyFileChunk) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{26}
}

func (x *CopyFileChunk) GetMsg() isCopyFileChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CopyFileChunk) GetMeta() *CopyFileMeta {
	if x != nil {
		if x, ok := x.Msg.(*CopyFileChunk_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *CopyFileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*CopyFileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isCopyFileChunk_Msg interface {
	isCopyFileChunk_Msg()
}

type CopyFileChunk_Meta struct {
	Meta *CopyFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type CopyFileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CopyFileChunk_Meta) isCopyFileChunk_Msg() {}

func (*CopyFileChunk_Data) isCopyFileChunk_Msg() {}

type CopyFileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the source's basename — the default local name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// mode is the source file's permission bits (so an executable stays runnable).
	// Unused when is_dir.
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// size is the file's byte count. Unused when is_dir.
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// is_dir marks a recursive directory copy: the data frames then carry a tar of
	// the directory (`tar -C <path> -cf - .`) instead of raw file bytes, and the
	// client extracts it in Go — skipping symlinks/special files and the `./` root
	// entry, sanitizing entry names. mode/size are unused.
	IsDir         bool `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileMeta) Reset() {
	*x = CopyFileMeta{}
	mi := &file_exec_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileMeta) ProtoMessage() {}

func (x *CopyFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileMeta.ProtoReflect.Descriptor instead.
func (*CopyFileMeta) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{27}
}

func (x *CopyFileMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CopyFileMeta) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyFileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CopyFileMeta) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

// CopyInto streams a file OR directory INTO an instance — the reverse of
// CopyFile, the other half of scp-style `fleet copy`. It is CLIENT-streaming: the
// FIRST chunk MUST carry `open` (which instance, the destination, and the
// source's name/mode/size or is_dir); every following chunk carries `data`. The
// server resolves the destination inside the container and writes through the
// backend with a `tar -xf -` exec. For a file the data is the raw bytes (written
// atomically via a temp name + rename); for a directory (open.is_dir) it is a tar
// of the directory's contents extracted in place. Works unchanged over the remote
// gateway: pushing a local file or tree into a fully remote deployment.
type CopyIntoChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CopyIntoChunk_Open
	//	*CopyIntoChunk_Data
	Msg           isCopyIntoChunk_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyIntoChunk) Reset() {
	*x = CopyIntoChunk{}
	mi := &file_exec_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyIntoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyIntoChunk) ProtoMessage() {}

func (x *CopyIntoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyIntoChunk.ProtoReflect.Descriptor instead.
func (*CopyIntoChunk) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{28}
}

func (x *CopyIntoChunk) GetMsg() isCopyIntoChunk_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CopyIntoChunk) GetOpen() *CopyIntoOpen {
	if x != nil {
		if x, ok := x.Msg.(*CopyIntoChunk_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *CopyIntoChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*CopyIntoChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isCopyIntoChunk_Msg interface {
	isCopyIntoChunk_Msg()
}

type CopyIntoChunk_Open struct {
	Open *CopyIntoOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type CopyIntoChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CopyIntoChunk_Open) isCopyIntoChunk_Msg() {}

func (*CopyIntoChunk_Data) isCopyIntoChunk_Msg() {}

type CopyIntoOpen struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// dest is the destination path inside the instance. A relative path resolves
	// against the workspace folder (the backend exec working directory). When it
	// names (or is) an existing directory the file keeps `name`; otherwise dest is
	// the full target path. Empty means the workspace folder.
	Dest string `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`
	// name is the source file's basename — used when dest resolves to a directory.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// mode is the file's permission bits to set on the written file (the perm bits
	// are honoured; a 0 mode defaults to 0644). setuid/setgid/sticky are stripped.
	// Unused when is_dir.
	Mode uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	// size is the source file's byte count — needed up front for the tar header,
	// and enforced as a hard cap so a truncated or oversized stream fails cleanly
	// rather than leaving a partial file. Unused when is_dir.
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// is_dir marks a recursive directory copy: the data frames then carry a tar of
	// the directory's CONTENTS (entries relative to the dir root, no symlinks or
	// special files, built by the client in Go), and the server resolves a target
	// directory and extracts it there with `tar -xf -` (an in-place merge, like
	// `cp -r`). mode/size are unused. NOT supported on the codespaces backend (its
	// exec PTY can silently corrupt a binary tar) — a FailedPrecondition there.
	IsDir         bool `protobuf:"varint,7,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyIntoOpen) Reset() {
	*x = CopyIntoOpen{}
	mi := &file_exec_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyIntoOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyIntoOpen) ProtoMessage() {}

func (x *CopyIntoOpen) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyIntoOpen.ProtoReflect.Descriptor instead.
func (*CopyIntoOpen) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{29}
}

func (x *CopyIntoOpen) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *CopyIntoOpen) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *CopyIntoOpen) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *CopyIntoOpen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CopyIntoOpen) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyIntoOpen) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CopyIntoOpen) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type CopyIntoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the final absolute path written inside the instance.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// written is the number of file bytes received and written.
	Written       int64 `protobuf:"varint,2,opt,name=written,proto3" json:"written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyIntoReply) Reset() {
	*x = CopyIntoReply{}
	mi := &file_exec_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyIntoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyIntoReply) ProtoMessage() {}

func (x *CopyIntoReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyIntoReply.ProtoReflect.Descriptor instead.
func (*CopyIntoReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{30}
}

func (x *CopyIntoReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyIntoReply) GetWritten() int64 {
	if x != nil {
		return x.Written
	}
	return 0
}

// ResolveLogsCommand returns the host-side command argv the server would run to
// show an instance's container runtime logs. The client embeds it in its own
// pager script (cat the creation log, then the runtime logs) and runs it
// locally — the analog of ResolveExecCommand for the `l` logs view.
type ResolveLogsCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLogsCommandRequest) Reset() {
	*x = ResolveLogsCommandRequest{}
	mi := &file_exec_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLogsCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLogsCommandRequest) ProtoMessage() {}

func (x *ResolveLogsCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLogsCommandRequest.ProtoReflect.Descriptor instead.
func (*ResolveLogsCommandRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{31}
}

func (x *ResolveLogsCommandRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *ResolveLogsCommandRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type ResolveLogsCommandReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argv          []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLogsCommandReply) Reset() {
	*x = ResolveLogsCommandReply{}
	mi := &file_exec_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLogsCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLogsCommandReply) ProtoMessage() {}

func (x *ResolveLogsCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLogsCommandReply.ProtoReflect.Descriptor instead.
func (*ResolveLogsCommandReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{32}
}

func (x *ResolveLogsCommandReply) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

// TriggerLogs reads back an automation trigger's recorded event logs. Each time
// a trigger fires, the daemon writes the firing's payload (the webhook body, or
// the schedule fire-time) to a per-trigger log directory, keeping the most
// recent 100. This returns them concatenated (oldest first), so a client can
// inspect what fired an automation after the fact — the TUI's 'L' pager, the
// `fleet trigger logs` CLI, and the fleet_trigger_logs MCP tool all read here.
// A trigger that has never fired returns empty logs with count 0 (not an error).
type TriggerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLogsRequest) Reset() {
	*x = TriggerLogsRequest{}
	mi := &file_exec_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLogsRequest) ProtoMessage() {}

func (x *TriggerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLogsRequest.ProtoReflect.Descriptor instead.
func (*TriggerLogsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{33}
}

func (x *TriggerLogsRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *TriggerLogsRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type TriggerLogsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// logs is every recorded event log concatenated (oldest first), each preceded
	// by a "===== event-<timestamp>.log =====" separator. Empty when none recorded.
	Logs string `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	// count is how many event logs were concatenated.
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLogsReply) Reset() {
	*x = TriggerLogsReply{}
	mi := &file_exec_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLogsReply) ProtoMessage() {}

func (x *TriggerLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLogsReply.ProtoReflect.Descriptor instead.
func (*TriggerLogsReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{34}
}

func (x *TriggerLogsReply) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *TriggerLogsReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetCoderTemplateParams fetches a Coder template's active-version rich
// parameters + preset names (the TUI's coder settings dialog used to call the
// coder backend's REST helpers directly). The server owns backend access.
type GetCoderTemplateParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoderTemplateParamsRequest) Reset() {
	*x = GetCoderTemplateParamsRequest{}
	mi := &file_exec_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoderTemplateParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoderTemplateParamsRequest) ProtoMessage() {}

func (x *GetCoderTemplateParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoderTemplateParamsRequest.ProtoReflect.Descriptor instead.
func (*GetCoderTemplateParamsRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{35}
}

func (x *GetCoderTemplateParamsRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

// CoderRichParameter is the subset of a Coder rich parameter the TUI renders /
// stores (mirrors internal/backend/coder.RichParameter, minus options/required/
// mutable which the settings dialog doesn't use).
type CoderRichParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoderRichParameter) Reset() {
	*x = CoderRichParameter{}
	mi := &file_exec_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoderRichParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoderRichParameter) ProtoMessage() {}

func (x *CoderRichParameter) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoderRichParameter.ProtoReflect.Descriptor instead.
func (*CoderRichParameter) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{36}
}

func (x *CoderRichParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CoderRichParameter) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CoderRichParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CoderRichParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CoderRichParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type GetCoderTemplateParamsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*CoderRichParameter  `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Presets       []string               `protobuf:"bytes,2,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoderTemplateParamsReply) Reset() {
	*x = GetCoderTemplateParamsReply{}
	mi := &file_exec_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoderTemplateParamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoderTemplateParamsReply) ProtoMessage() {}

func (x *GetCoderTemplateParamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoderTemplateParamsReply.ProtoReflect.Descriptor instead.
func (*GetCoderTemplateParamsReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{37}
}

func (x *GetCoderTemplateParamsReply) GetParameters() []*CoderRichParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GetCoderTemplateParamsReply) GetPresets() []string {
	if x != nil {
		return x.Presets
	}
	return nil
}

// GetBrowserConfig reads the workspace's devcontainer.json fleet customization
// so the TUI can decide whether to show the launch chooser (both an initial URL
// and a landing page are configured).
type GetBrowserConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fleet         string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrowserConfigRequest) Reset() {
	*x = GetBrowserConfigRequest{}
	mi := &file_exec_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrowserConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserConfigRequest) ProtoMessage() {}

func (x *GetBrowserConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBrowserConfigRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{38}
}

func (x *GetBrowserConfigRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *GetBrowserConfigRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type GetBrowserConfigReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// initial_url is customizations.fleet.browser.initialUrl ("" if unset).
	InitialUrl string `protobuf:"bytes,1,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
	// has_landing is true when a Fleet Launch landing page is configured.
	HasLanding    bool `protobuf:"varint,2,opt,name=has_landing,json=hasLanding,proto3" json:"has_landing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrowserConfigReply) Reset() {
	*x = GetBrowserConfigReply{}
	mi := &file_exec_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrowserConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserConfigReply) ProtoMessage() {}

func (x *GetBrowserConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserConfigReply.ProtoReflect.Descriptor instead.
func (*GetBrowserConfigReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{39}
}

func (x *GetBrowserConfigReply) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

func (x *GetBrowserConfigReply) GetHasLanding() bool {
	if x != nil {
		return x.HasLanding
	}
	return false
}

// PrepareBrowser does all the container-side work for a browser open: ensure the
// privoxy proxy is installed + running, then resolve the page to open —
// honouring an explicit target_url, else the devcontainer.json initialUrl /
// Fleet Launch landing page (starting the landing-page server when chosen) /
// the default. It returns the URL the client's browser should open.
type PrepareBrowserRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// prefer_fleet_launch is the fleet's resolved PreferFleetLaunch setting (the
	// tie-breaker when both an initial URL and a landing page are configured).
	PreferFleetLaunch bool `protobuf:"varint,3,opt,name=prefer_fleet_launch,json=preferFleetLaunch,proto3" json:"prefer_fleet_launch,omitempty"`
	// target_url, when set, is used verbatim (a control-socket browser.open
	// request already chose the URL) and config/landing resolution is skipped.
	TargetUrl     *string `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3,oneof" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareBrowserRequest) Reset() {
	*x = PrepareBrowserRequest{}
	mi := &file_exec_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBrowserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBrowserRequest) ProtoMessage() {}

func (x *PrepareBrowserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBrowserRequest.ProtoReflect.Descriptor instead.
func (*PrepareBrowserRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{40}
}

func (x *PrepareBrowserRequest) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *PrepareBrowserRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *PrepareBrowserRequest) GetPreferFleetLaunch() bool {
	if x != nil {
		return x.PreferFleetLaunch
	}
	return false
}

func (x *PrepareBrowserRequest) GetTargetUrl() string {
	if x != nil && x.TargetUrl != nil {
		return *x.TargetUrl
	}
	return ""
}

type PrepareBrowserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialUrl    string                 `protobuf:"bytes,1,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareBrowserReply) Reset() {
	*x = PrepareBrowserReply{}
	mi := &file_exec_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBrowserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBrowserReply) ProtoMessage() {}

func (x *PrepareBrowserReply) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBrowserReply.ProtoReflect.Descriptor instead.
func (*PrepareBrowserReply) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{41}
}

func (x *PrepareBrowserReply) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\tfleetgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\x06ExecIn\x12,\n" +
	"\x05start\x18\x01 \x01(\v2\x14.fleetgrpc.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12/\n" +
	"\x06resize\x18\x03 \x01(\v2\x15.fleetgrpc.ExecResizeH\x00R\x06resizeB\x05\n" +
	"\x03msg\"\xcc\x01\n" +
	"\tExecStart\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.fleetgrpc.ExecStart.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"o\n" +
	"\aExecOut\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12)\n" +
	"\x04exit\x18\x03 \x01(\v2\x13.fleetgrpc.ExecExitH\x00R\x04exitB\x05\n" +
	"\x03msg\"C\n" +
	"\bExecExit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"a\n" +
	"\x19ResolveExecCommandRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\"\xa4\x01\n" +
	"\x17ResolveExecCommandReply\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12=\n" +
	"\x03env\x18\x02 \x03(\v2+.fleetgrpc.ResolveExecCommandReply.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\vLogsRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x17\n" +
	"\x04tail\x18\x04 \x01(\x05H\x00R\x04tail\x88\x01\x01B\a\n" +
	"\x05_tail\"I\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"Y\n" +
	"\fForwardChunk\x12,\n" +
	"\x04open\x18\x01 \x01(\v2\x16.fleetgrpc.ForwardOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"`\n" +
	"\vForwardOpen\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\x05R\n" +
	"remotePort\"P\n" +
	"\x05MicUp\x12(\n" +
	"\x04open\x18\x01 \x01(\v2\x12.fleetgrpc.MicOpenH\x00R\x04open\x12\x16\n" +
	"\x05audio\x18\x02 \x01(\fH\x00R\x05audioB\x05\n" +
	"\x03msg\"F\n" +
	"\aMicOpen\x12\x1f\n" +
	"\vsample_rate\x18\x01 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\rR\bchannels\"@\n" +
	"\aMicDown\x12.\n" +
	"\x06demand\x18\x01 \x01(\v2\x14.fleetgrpc.MicDemandH\x00R\x06demandB\x05\n" +
	"\x03msg\"Y\n" +
	"\tMicDemand\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1c\n" +
	"\tinstances\x18\x02 \x03(\tR\tinstances\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"\x87\x02\n" +
	"\n" +
	"SSHAgentUp\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.fleetgrpc.SSHAgentHelloH\x00R\x05hello\x120\n" +
	"\x05ready\x18\x02 \x01(\v2\x18.fleetgrpc.SSHAgentReadyH\x00R\x05ready\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x17.fleetgrpc.SSHAgentDataH\x00R\x04data\x120\n" +
	"\x05close\x18\x04 \x01(\v2\x18.fleetgrpc.SSHAgentCloseH\x00R\x05close\x12-\n" +
	"\x04pong\x18\x05 \x01(\v2\x17.fleetgrpc.SSHAgentPongH\x00R\x04pongB\x05\n" +
	"\x03msg\"=\n" +
	"\rSSHAgentHello\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x14\n" +
	"\x05yield\x18\x02 \x01(\bR\x05yield\"(\n" +
	"\rSSHAgentReady\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\" \n" +
	"\fSSHAgentPong\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\x89\x02\n" +
	"\fSSHAgentDown\x12-\n" +
	"\x04open\x18\x01 \x01(\v2\x17.fleetgrpc.SSHAgentOpenH\x00R\x04open\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x17.fleetgrpc.SSHAgentDataH\x00R\x04data\x120\n" +
	"\x05close\x18\x03 \x01(\v2\x18.fleetgrpc.SSHAgentCloseH\x00R\x05close\x123\n" +
	"\x06status\x18\x04 \x01(\v2\x19.fleetgrpc.SSHAgentStatusH\x00R\x06status\x12-\n" +
	"\x04ping\x18\x05 \x01(\v2\x17.fleetgrpc.SSHAgentPingH\x00R\x04pingB\x05\n" +
	"\x03msg\"?\n" +
	"\fSSHAgentOpen\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\";\n" +
	"\fSSHAgentData\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\">\n" +
	"\rSSHAgentClose\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x0eSSHAgentStatus\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\" \n" +
	"\fSSHAgentPing\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"W\n" +
	"\x0fCopyFileRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"[\n" +
	"\rCopyFileChunk\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x17.fleetgrpc.CopyFileMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"a\n" +
	"\fCopyFileMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\"[\n" +
	"\rCopyIntoChunk\x12-\n" +
	"\x04open\x18\x01 \x01(\v2\x17.fleetgrpc.CopyIntoOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"\xa7\x01\n" +
	"\fCopyIntoOpen\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\tR\x04dest\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\a \x01(\bR\x05isDir\"=\n" +
	"\rCopyIntoReply\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\awritten\x18\x02 \x01(\x03R\awritten\"M\n" +
	"\x19ResolveLogsCommandRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"-\n" +
	"\x17ResolveLogsCommandReply\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\"D\n" +
	"\x12TriggerLogsRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\"<\n" +
	"\x10TriggerLogsReply\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\";\n" +
	"\x1dGetCoderTemplateParamsRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\"\xa6\x01\n" +
	"\x12CoderRichParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\"v\n" +
	"\x1bGetCoderTemplateParamsReply\x12=\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1d.fleetgrpc.CoderRichParameterR\n" +
	"parameters\x12\x18\n" +
	"\apresets\x18\x02 \x03(\tR\apresets\"K\n" +
	"\x17GetBrowserConfigRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"Y\n" +
	"\x15GetBrowserConfigReply\x12\x1f\n" +
	"\vinitial_url\x18\x01 \x01(\tR\n" +
	"initialUrl\x12\x1f\n" +
	"\vhas_landing\x18\x02 \x01(\bR\n" +
	"hasLanding\"\xac\x01\n" +
	"\x15PrepareBrowserRequest\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12.\n" +
	"\x13prefer_fleet_launch\x18\x03 \x01(\bR\x11preferFleetLaunch\x12\"\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tH\x00R\ttargetUrl\x88\x01\x01B\r\n" +
	"\v_target_url\"6\n" +
	"\x13PrepareBrowserReply\x12\x1f\n" +
	"\vinitial_url\x18\x01 \x01(\tR\n" +
	"initialUrlB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_exec_proto_goTypes = []any{
	(*ExecIn)(nil),                        // 0: fleetgrpc.ExecIn
	(*ExecStart)(nil),                     // 1: fleetgrpc.ExecStart
	(*ExecResize)(nil),                    // 2: fleetgrpc.ExecResize
	(*ExecOut)(nil),                       // 3: fleetgrpc.ExecOut
	(*ExecExit)(nil),                      // 4: fleetgrpc.ExecExit
	(*ResolveExecCommandRequest)(nil),     // 5: fleetgrpc.ResolveExecCommandRequest
	(*ResolveExecCommandReply)(nil),       // 6: fleetgrpc.ResolveExecCommandReply
	(*LogsRequest)(nil),                   // 7: fleetgrpc.LogsRequest
	(*LogLine)(nil),                       // 8: fleetgrpc.LogLine
	(*ForwardChunk)(nil),                  // 9: fleetgrpc.ForwardChunk
	(*ForwardOpen)(nil),                   // 10: fleetgrpc.ForwardOpen
	(*MicUp)(nil),                         // 11: fleetgrpc.MicUp
	(*MicOpen)(nil),                       // 12: fleetgrpc.MicOpen
	(*MicDown)(nil),                       // 13: fleetgrpc.MicDown
	(*MicDemand)(nil),                     // 14: fleetgrpc.MicDemand
	(*SSHAgentUp)(nil),                    // 15: fleetgrpc.SSHAgentUp
	(*SSHAgentHello)(nil),                 // 16: fleetgrpc.SSHAgentHello
	(*SSHAgentReady)(nil),                 // 17: fleetgrpc.SSHAgentReady
	(*SSHAgentPong)(nil),                  // 18: fleetgrpc.SSHAgentPong
	(*SSHAgentDown)(nil),                  // 19: fleetgrpc.SSHAgentDown
	(*SSHAgentOpen)(nil),                  // 20: fleetgrpc.SSHAgentOpen
	(*SSHAgentData)(nil),                  // 21: fleetgrpc.SSHAgentData
	(*SSHAgentClose)(nil),                 // 22: fleetgrpc.SSHAgentClose
	(*SSHAgentStatus)(nil),                // 23: fleetgrpc.SSHAgentStatus
	(*SSHAgentPing)(nil),                  // 24: fleetgrpc.SSHAgentPing
	(*CopyFileRequest)(nil),               // 25: fleetgrpc.CopyFileRequest
	(*CopyFileChunk)(nil),                 // 26: fleetgrpc.CopyFileChunk
	(*CopyFileMeta)(nil),                  // 27: fleetgrpc.CopyFileMeta
	(*CopyIntoChunk)(nil),                 // 28: fleetgrpc.CopyIntoChunk
	(*CopyIntoOpen)(nil),                  // 29: fleetgrpc.CopyIntoOpen
	(*CopyIntoReply)(nil),                 // 30: fleetgrpc.CopyIntoReply
	(*ResolveLogsCommandRequest)(nil),     // 31: fleetgrpc.ResolveLogsCommandRequest
	(*ResolveLogsCommandReply)(nil),       // 32: fleetgrpc.ResolveLogsCommandReply
	(*TriggerLogsRequest)(nil),            // 33: fleetgrpc.TriggerLogsRequest
	(*TriggerLogsReply)(nil),              // 34: fleetgrpc.TriggerLogsReply
	(*GetCoderTemplateParamsRequest)(nil), // 35: fleetgrpc.GetCoderTemplateParamsRequest
	(*CoderRichParameter)(nil),            // 36: fleetgrpc.CoderRichParameter
	(*GetCoderTemplateParamsReply)(nil),   // 37: fleetgrpc.GetCoderTemplateParamsReply
	(*GetBrowserConfigRequest)(nil),       // 38: fleetgrpc.GetBrowserConfigRequest
	(*GetBrowserConfigReply)(nil),         // 39: fleetgrpc.GetBrowserConfigReply
	(*PrepareBrowserRequest)(nil),         // 40: fleetgrpc.PrepareBrowserRequest
	(*PrepareBrowserReply)(nil),           // 41: fleetgrpc.PrepareBrowserReply
	nil,                                   // 42: fleetgrpc.ExecStart.EnvEntry
	nil,                                   // 43: fleetgrpc.ResolveExecCommandReply.EnvEntry
	(*timestamppb.Timestamp)(nil),         // 44: google.protobuf.Timestamp
}
var file_exec_proto_depIdxs = []int32{
	1,  // 0: fleetgrpc.ExecIn.start:type_name -> fleetgrpc.ExecStart
	2,  // 1: fleetgrpc.ExecIn.resize:type_name -> fleetgrpc.ExecResize
	42, // 2: fleetgrpc.ExecStart.env:type_name -> fleetgrpc.ExecStart.EnvEntry
	4,  // 3: fleetgrpc.ExecOut.exit:type_name -> fleetgrpc.ExecExit
	43, // 4: fleetgrpc.ResolveExecCommandReply.env:type_name -> fleetgrpc.ResolveExecCommandReply.EnvEntry
	44, // 5: fleetgrpc.LogLine.at:type_name -> google.protobuf.Timestamp
	10, // 6: fleetgrpc.ForwardChunk.open:type_name -> fleetgrpc.ForwardOpen
	12, // 7: fleetgrpc.MicUp.open:type_name -> fleetgrpc.MicOpen
	14, // 8: fleetgrpc.MicDown.demand:type_name -> fleetgrpc.MicDemand
	16, // 9: fleetgrpc.SSHAgentUp.hello:type_name -> fleetgrpc.SSHAgentHello
	17, // 10: fleetgrpc.SSHAgentUp.ready:type_name -> fleetgrpc.SSHAgentReady
	21, // 11: fleetgrpc.SSHAgentUp.data:type_name -> fleetgrpc.SSHAgentData
	22, // 12: fleetgrpc.SSHAgentUp.close:type_name -> fleetgrpc.SSHAgentClose
	18, // 13: fleetgrpc.SSHAgentUp.pong:type_name -> fleetgrpc.SSHAgentPong
	20, // 14: fleetgrpc.SSHAgentDown.open:type_name -> fleetgrpc.SSHAgentOpen
	21, // 15: fleetgrpc.SSHAgentDown.data:type_name -> fleetgrpc.SSHAgentData
	22, // 16: fleetgrpc.SSHAgentDown.close:type_name -> fleetgrpc.SSHAgentClose
	23, // 17: fleetgrpc.SSHAgentDown.status:type_name -> fleetgrpc.SSHAgentStatus
	24, // 18: fleetgrpc.SSHAgentDown.ping:type_name -> fleetgrpc.SSHAgentPing
	27, // 19: fleetgrpc.CopyFileChunk.meta:type_name -> fleetgrpc.CopyFileMeta
	29, // 20: fleetgrpc.CopyIntoChunk.open:type_name -> fleetgrpc.CopyIntoOpen
	36, // 21: fleetgrpc.GetCoderTemplateParamsReply.parameters:type_name -> fleetgrpc.CoderRichParameter
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	file_exec_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecIn_Start)(nil),
		(*ExecIn_Stdin)(nil),
		(*ExecIn_Resize)(nil),
	}
	file_exec_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecOut_Stdout)(nil),
		(*ExecOut_Stderr)(nil),
		(*ExecOut_Exit)(nil),
	}
	file_exec_proto_msgTypes[4].OneofWrappers = []any{}
	file_exec_proto_msgTypes[7].OneofWrappers = []any{}
	file_exec_proto_msgTypes[9].OneofWrappers = []any{
		(*ForwardChunk_Open)(nil),
		(*ForwardChunk_Data)(nil),
	}
	file_exec_proto_msgTypes[11].OneofWrappers = []any{
		(*MicUp_Open)(nil),
		(*MicUp_Audio)(nil),
	}
	file_exec_proto_msgTypes[13].OneofWrappers = []any{
		(*MicDown_Demand)(nil),
	}
	file_exec_proto_msgTypes[15].OneofWrappers = []any{
		(*SSHAgentUp_Hello)(nil),
		(*SSHAgentUp_Ready)(nil),
		(*SSHAgentUp_Data)(nil),
		(*SSHAgentUp_Close)(nil),
		(*SSHAgentUp_Pong)(nil),
	}
	file_exec_proto_msgTypes[19].OneofWrappers = []any{
		(*SSHAgentDown_Open)(nil),
		(*SSHAgentDown_Data)(nil),
		(*SSHAgentDown_Close)(nil),
		(*SSHAgentDown_Status)(nil),
		(*SSHAgentDown_Ping)(nil),
	}
	file_exec_proto_msgTypes[26].OneofWrappers = []any{
		(*CopyFileChunk_Meta)(nil),
		(*CopyFileChunk_Data)(nil),
	}
	file_exec_proto_msgTypes[28].OneofWrappers = []any{
		(*CopyIntoChunk_Open)(nil),
		(*CopyIntoChunk_Data)(nil),
	}
	file_exec_proto_msgTypes[40].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
