// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inspect.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectRepoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// remote_url is the git remote to shallow-clone for inspection.
	RemoteUrl string `protobuf:"bytes,1,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	// branch optionally pins the branch to inspect (repo default when empty).
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	// detect_home_dir additionally runs container home-dir detection, which may
	// pull the devcontainer image (slow). Devcontainer presence is always
	// checked.
	DetectHomeDir bool `protobuf:"varint,3,opt,name=detect_home_dir,json=detectHomeDir,proto3" json:"detect_home_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRepoRequest) Reset() {
	*x = InspectRepoRequest{}
	mi := &file_inspect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRepoRequest) ProtoMessage() {}

func (x *InspectRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRepoRequest.ProtoReflect.Descriptor instead.
func (*InspectRepoRequest) Descriptor() ([]byte, []int) {
	return file_inspect_proto_rawDescGZIP(), []int{0}
}

func (x *InspectRepoRequest) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

func (x *InspectRepoRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *InspectRepoRequest) GetDetectHomeDir() bool {
	if x != nil {
		return x.DetectHomeDir
	}
	return false
}

type InspectRepoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// has_devcontainer reports whether the repo declares a devcontainer.json in
	// any location the devcontainer CLI recognises.
	HasDevcontainer bool `protobuf:"varint,1,opt,name=has_devcontainer,json=hasDevcontainer,proto3" json:"has_devcontainer,omitempty"`
	// home_dir is the detected container home directory (e.g. "/home/vscode").
	// Empty when detection was not requested or produced no user hint — the
	// caller falls back to manual entry.
	HomeDir       string `protobuf:"bytes,2,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRepoReply) Reset() {
	*x = InspectRepoReply{}
	mi := &file_inspect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRepoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRepoReply) ProtoMessage() {}

func (x *InspectRepoReply) ProtoReflect() protoreflect.Message {
	mi := &file_inspect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRepoReply.ProtoReflect.Descriptor instead.
func (*InspectRepoReply) Descriptor() ([]byte, []int) {
	return file_inspect_proto_rawDescGZIP(), []int{1}
}

func (x *InspectRepoReply) GetHasDevcontainer() bool {
	if x != nil {
		return x.HasDevcontainer
	}
	return false
}

func (x *InspectRepoReply) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

var File_inspect_proto protoreflect.FileDescriptor

const file_inspect_proto_rawDesc = "" +
	"\n" +
	"\rinspect.proto\x12\tfleetgrpc\"s\n" +
	"\x12InspectRepoRequest\x12\x1d\n" +
	"\n" +
	"remote_url\x18\x01 \x01(\tR\tremoteUrl\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12&\n" +
	"\x0fdetect_home_dir\x18\x03 \x01(\bR\rdetectHomeDir\"X\n" +
	"\x10InspectRepoReply\x12)\n" +
	"\x10has_devcontainer\x18\x01 \x01(\bR\x0fhasDevcontainer\x12\x19\n" +
	"\bhome_dir\x18\x02 \x01(\tR\ahomeDirB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_inspect_proto_rawDescOnce sync.Once
	file_inspect_proto_rawDescData []byte
)

func file_inspect_proto_rawDescGZIP() []byte {
	file_inspect_proto_rawDescOnce.Do(func() {
		file_inspect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inspect_proto_rawDesc), len(file_inspect_proto_rawDesc)))
	})
	return file_inspect_proto_rawDescData
}

var file_inspect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inspect_proto_goTypes = []any{
	(*InspectRepoRequest)(nil), // 0: fleetgrpc.InspectRepoRequest
	(*InspectRepoReply)(nil),   // 1: fleetgrpc.InspectRepoReply
}
var file_inspect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inspect_proto_init() }
func file_inspect_proto_init() {
	if File_inspect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inspect_proto_rawDesc), len(file_inspect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inspect_proto_goTypes,
		DependencyIndexes: file_inspect_proto_depIdxs,
		MessageInfos:      file_inspect_proto_msgTypes,
	}.Build()
	File_inspect_proto = out.File
	file_inspect_proto_goTypes = nil
	file_inspect_proto_depIdxs = nil
}
