// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LiveContainerStatus mirrors internal/backend.LiveStatus — the raw result of a
// live backend probe (docker inspect / coder / codespaces). Distinct from the
// persisted InstanceStatus: the server reconciles only RUNNING<->STOPPED into
// the persisted status, but the raw probe (incl. MISSING/UNKNOWN) is richer and
// surfaced here so the TUI can show "missing"/"probe failed" without forcing a
// persisted status flip.
type LiveContainerStatus int32

const (
	LiveContainerStatus_LIVE_CONTAINER_STATUS_UNSPECIFIED LiveContainerStatus = 0 // not yet probed
	LiveContainerStatus_LIVE_CONTAINER_STATUS_RUNNING     LiveContainerStatus = 1
	LiveContainerStatus_LIVE_CONTAINER_STATUS_STOPPED     LiveContainerStatus = 2
	LiveContainerStatus_LIVE_CONTAINER_STATUS_MISSING     LiveContainerStatus = 3 // deleted out-of-band
	LiveContainerStatus_LIVE_CONTAINER_STATUS_UNKNOWN     LiveContainerStatus = 4 // transient probe failure (preserve persisted)
)

// Enum value maps for LiveContainerStatus.
var (
	LiveContainerStatus_name = map[int32]string{
		0: "LIVE_CONTAINER_STATUS_UNSPECIFIED",
		1: "LIVE_CONTAINER_STATUS_RUNNING",
		2: "LIVE_CONTAINER_STATUS_STOPPED",
		3: "LIVE_CONTAINER_STATUS_MISSING",
		4: "LIVE_CONTAINER_STATUS_UNKNOWN",
	}
	LiveContainerStatus_value = map[string]int32{
		"LIVE_CONTAINER_STATUS_UNSPECIFIED": 0,
		"LIVE_CONTAINER_STATUS_RUNNING":     1,
		"LIVE_CONTAINER_STATUS_STOPPED":     2,
		"LIVE_CONTAINER_STATUS_MISSING":     3,
		"LIVE_CONTAINER_STATUS_UNKNOWN":     4,
	}
)

func (x LiveContainerStatus) Enum() *LiveContainerStatus {
	p := new(LiveContainerStatus)
	*p = x
	return p
}

func (x LiveContainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveContainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[0].Descriptor()
}

func (LiveContainerStatus) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[0]
}

func (x LiveContainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveContainerStatus.Descriptor instead.
func (LiveContainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

// AgentTool identifies which coding agent the server detected running inside the
// instance (backend.AgentToolProbe / internal/agentdetect). NONE means a probe
// ran and found no agent; UNSPECIFIED means not-yet-probed.
type AgentTool int32

const (
	AgentTool_AGENT_TOOL_UNSPECIFIED AgentTool = 0
	AgentTool_AGENT_TOOL_NONE        AgentTool = 1
	AgentTool_AGENT_TOOL_CLAUDE      AgentTool = 2
	AgentTool_AGENT_TOOL_CODEX       AgentTool = 3
	AgentTool_AGENT_TOOL_GEMINI      AgentTool = 4
	AgentTool_AGENT_TOOL_COPILOT     AgentTool = 5
	AgentTool_AGENT_TOOL_AUGGIE      AgentTool = 6
)

// Enum value maps for AgentTool.
var (
	AgentTool_name = map[int32]string{
		0: "AGENT_TOOL_UNSPECIFIED",
		1: "AGENT_TOOL_NONE",
		2: "AGENT_TOOL_CLAUDE",
		3: "AGENT_TOOL_CODEX",
		4: "AGENT_TOOL_GEMINI",
		5: "AGENT_TOOL_COPILOT",
		6: "AGENT_TOOL_AUGGIE",
	}
	AgentTool_value = map[string]int32{
		"AGENT_TOOL_UNSPECIFIED": 0,
		"AGENT_TOOL_NONE":        1,
		"AGENT_TOOL_CLAUDE":      2,
		"AGENT_TOOL_CODEX":       3,
		"AGENT_TOOL_GEMINI":      4,
		"AGENT_TOOL_COPILOT":     5,
		"AGENT_TOOL_AUGGIE":      6,
	}
)

func (x AgentTool) Enum() *AgentTool {
	p := new(AgentTool)
	*p = x
	return p
}

func (x AgentTool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentTool) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[1].Descriptor()
}

func (AgentTool) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[1]
}

func (x AgentTool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentTool.Descriptor instead.
func (AgentTool) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

// AgentActivity mirrors internal/agentdetect.State — the three-state activity
// indicator (the throbber) for a detected agent.
type AgentActivity int32

const (
	AgentActivity_AGENT_ACTIVITY_UNSPECIFIED AgentActivity = 0 // not yet determined
	AgentActivity_AGENT_ACTIVITY_NOT_RUNNING AgentActivity = 1 // no agent process detected
	AgentActivity_AGENT_ACTIVITY_WORKING     AgentActivity = 2 // actively producing output
	AgentActivity_AGENT_ACTIVITY_WAITING     AgentActivity = 3 // alive but idle / awaiting input
)

// Enum value maps for AgentActivity.
var (
	AgentActivity_name = map[int32]string{
		0: "AGENT_ACTIVITY_UNSPECIFIED",
		1: "AGENT_ACTIVITY_NOT_RUNNING",
		2: "AGENT_ACTIVITY_WORKING",
		3: "AGENT_ACTIVITY_WAITING",
	}
	AgentActivity_value = map[string]int32{
		"AGENT_ACTIVITY_UNSPECIFIED": 0,
		"AGENT_ACTIVITY_NOT_RUNNING": 1,
		"AGENT_ACTIVITY_WORKING":     2,
		"AGENT_ACTIVITY_WAITING":     3,
	}
)

func (x AgentActivity) Enum() *AgentActivity {
	p := new(AgentActivity)
	*p = x
	return p
}

func (x AgentActivity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentActivity) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[2].Descriptor()
}

func (AgentActivity) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[2]
}

func (x AgentActivity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentActivity.Descriptor instead.
func (AgentActivity) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

// PrSignal is the three-state colour shared by the auto-tag indicators:
// green = good, yellow = in-progress/neutral, red = needs attention.
type PrSignal int32

const (
	PrSignal_PR_SIGNAL_UNSPECIFIED PrSignal = 0
	PrSignal_PR_SIGNAL_GREEN       PrSignal = 1
	PrSignal_PR_SIGNAL_YELLOW      PrSignal = 2
	PrSignal_PR_SIGNAL_RED         PrSignal = 3
)

// Enum value maps for PrSignal.
var (
	PrSignal_name = map[int32]string{
		0: "PR_SIGNAL_UNSPECIFIED",
		1: "PR_SIGNAL_GREEN",
		2: "PR_SIGNAL_YELLOW",
		3: "PR_SIGNAL_RED",
	}
	PrSignal_value = map[string]int32{
		"PR_SIGNAL_UNSPECIFIED": 0,
		"PR_SIGNAL_GREEN":       1,
		"PR_SIGNAL_YELLOW":      2,
		"PR_SIGNAL_RED":         3,
	}
)

func (x PrSignal) Enum() *PrSignal {
	p := new(PrSignal)
	*p = x
	return p
}

func (x PrSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[3].Descriptor()
}

func (PrSignal) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[3]
}

func (x PrSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrSignal.Descriptor instead.
func (PrSignal) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

// PrReviewState is the aggregate review decision across an instance's open PRs,
// driving the review element of the auto tag. For an open PR it is always one of
// the three concrete states: APPROVED ("Accepted", green) when every PR is
// approved, CHANGES_REQUESTED ("Rejected", red) when any PR needs work, PENDING
// ("Pending", grey) otherwise. UNSPECIFIED is the zero value (no PRs) and
// renders nothing.
type PrReviewState int32

const (
	PrReviewState_PR_REVIEW_STATE_UNSPECIFIED       PrReviewState = 0
	PrReviewState_PR_REVIEW_STATE_APPROVED          PrReviewState = 1
	PrReviewState_PR_REVIEW_STATE_CHANGES_REQUESTED PrReviewState = 2
	PrReviewState_PR_REVIEW_STATE_PENDING           PrReviewState = 3
)

// Enum value maps for PrReviewState.
var (
	PrReviewState_name = map[int32]string{
		0: "PR_REVIEW_STATE_UNSPECIFIED",
		1: "PR_REVIEW_STATE_APPROVED",
		2: "PR_REVIEW_STATE_CHANGES_REQUESTED",
		3: "PR_REVIEW_STATE_PENDING",
	}
	PrReviewState_value = map[string]int32{
		"PR_REVIEW_STATE_UNSPECIFIED":       0,
		"PR_REVIEW_STATE_APPROVED":          1,
		"PR_REVIEW_STATE_CHANGES_REQUESTED": 2,
		"PR_REVIEW_STATE_PENDING":           3,
	}
)

func (x PrReviewState) Enum() *PrReviewState {
	p := new(PrReviewState)
	*p = x
	return p
}

func (x PrReviewState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrReviewState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[4].Descriptor()
}

func (PrReviewState) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[4]
}

func (x PrReviewState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrReviewState.Descriptor instead.
func (PrReviewState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

// ContainerStats mirrors internal/backend.ContainerStats (the dim mcpu/MB in the
// instance row).
type ContainerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores float64                `protobuf:"fixed64,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryMb      float64                `protobuf:"fixed64,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStats) Reset() {
	*x = ContainerStats{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStats) ProtoMessage() {}

func (x *ContainerStats) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStats.ProtoReflect.Descriptor instead.
func (*ContainerStats) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerStats) GetCpuMillicores() float64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ContainerStats) GetMemoryMb() float64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

// TmuxSession mirrors a discovered tmux session (tui/sessions.go tmuxSession:
// `tmux list-sessions -F "#{session_name}:#{session_windows}:#{session_attached}"`).
// Live per-instance discovery, only populated for running/expanded instances.
type TmuxSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Windows       int32                  `protobuf:"varint,2,opt,name=windows,proto3" json:"windows,omitempty"`
	Attached      bool                   `protobuf:"varint,3,opt,name=attached,proto3" json:"attached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TmuxSession) Reset() {
	*x = TmuxSession{}
	mi := &file_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TmuxSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmuxSession) ProtoMessage() {}

func (x *TmuxSession) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TmuxSession.ProtoReflect.Descriptor instead.
func (*TmuxSession) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *TmuxSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TmuxSession) GetWindows() int32 {
	if x != nil {
		return x.Windows
	}
	return 0
}

func (x *TmuxSession) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

// ForwardedPort describes an active port-forward the server set up for the
// instance (the ⇄ local:remote labels). Named ForwardedPort, NOT PortForward,
// to avoid colliding with the PortForward RPC family in exec.proto.
type ForwardedPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPort     int32                  `protobuf:"varint,1,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort    int32                  `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Label         *string                `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardedPort) Reset() {
	*x = ForwardedPort{}
	mi := &file_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedPort) ProtoMessage() {}

func (x *ForwardedPort) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedPort.ProtoReflect.Descriptor instead.
func (*ForwardedPort) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardedPort) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *ForwardedPort) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *ForwardedPort) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

// PrRef identifies one open PR so the TUI can navigate to it (open in a
// browser) and label it in the multi-PR chooser dialog.
type PrRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrRef) Reset() {
	*x = PrRef{}
	mi := &file_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrRef) ProtoMessage() {}

func (x *PrRef) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrRef.ProtoReflect.Descriptor instead.
func (*PrRef) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *PrRef) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PrRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PrRef) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// PrStatus is the aggregated GitHub pull-request state for an instance's
// workspace repo PLUS any nested subrepos, computed by running `gh` inside the
// container. It drives the "auto tag" the TUI renders in the tag slot when an
// instance has no user-set tag. It is absent (nil) when gh is missing or
// unauthenticated inside the instance, or when no PR is open — the TUI then
// shows no auto-tag, preserving today's behaviour.
type PrStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Open PRs counted across the workspace repo and every subrepo. The PR
	// indicator renders "PR" for 1 and "PRxN" for N>1; 0 means no auto-tag.
	OpenCount int32 `protobuf:"varint,1,opt,name=open_count,json=openCount,proto3" json:"open_count,omitempty"`
	// Colour for the [PR]/[PRxN] indicator: green when every PR is mergeable,
	// red on any check failure or changes-requested, yellow otherwise.
	PrSignal PrSignal `protobuf:"varint,2,opt,name=pr_signal,json=prSignal,proto3,enum=fleetgrpc.PrSignal" json:"pr_signal,omitempty"`
	// The [Changes Requested | Approved] element (UNSPECIFIED hides it).
	Review PrReviewState `protobuf:"varint,3,opt,name=review,proto3,enum=fleetgrpc.PrReviewState" json:"review,omitempty"`
	// Successful + total checks summed across all open PRs (the "x/x").
	ChecksPassed int32 `protobuf:"varint,4,opt,name=checks_passed,json=checksPassed,proto3" json:"checks_passed,omitempty"`
	ChecksTotal  int32 `protobuf:"varint,5,opt,name=checks_total,json=checksTotal,proto3" json:"checks_total,omitempty"`
	// Colour for the [Checks x/x] indicator: green when all passed, red on any
	// failure, yellow while any are still pending.
	ChecksSignal PrSignal `protobuf:"varint,6,opt,name=checks_signal,json=checksSignal,proto3,enum=fleetgrpc.PrSignal" json:"checks_signal,omitempty"`
	// The open PRs themselves, so the TUI can open one in a browser (or present a
	// chooser when there is more than one). Order follows discovery (workspace
	// repo first, then subrepos).
	Prs           []*PrRef `protobuf:"bytes,7,rep,name=prs,proto3" json:"prs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrStatus) Reset() {
	*x = PrStatus{}
	mi := &file_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrStatus) ProtoMessage() {}

func (x *PrStatus) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrStatus.ProtoReflect.Descriptor instead.
func (*PrStatus) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *PrStatus) GetOpenCount() int32 {
	if x != nil {
		return x.OpenCount
	}
	return 0
}

func (x *PrStatus) GetPrSignal() PrSignal {
	if x != nil {
		return x.PrSignal
	}
	return PrSignal_PR_SIGNAL_UNSPECIFIED
}

func (x *PrStatus) GetReview() PrReviewState {
	if x != nil {
		return x.Review
	}
	return PrReviewState_PR_REVIEW_STATE_UNSPECIFIED
}

func (x *PrStatus) GetChecksPassed() int32 {
	if x != nil {
		return x.ChecksPassed
	}
	return 0
}

func (x *PrStatus) GetChecksTotal() int32 {
	if x != nil {
		return x.ChecksTotal
	}
	return 0
}

func (x *PrStatus) GetChecksSignal() PrSignal {
	if x != nil {
		return x.ChecksSignal
	}
	return PrSignal_PR_SIGNAL_UNSPECIFIED
}

func (x *PrStatus) GetPrs() []*PrRef {
	if x != nil {
		return x.Prs
	}
	return nil
}

// InstanceRuntime is the live view of ONE instance: everything the TUI renders
// that isn't persisted. Keyed by (fleet, instance) so the client joins it to the
// persisted Instance of the same name. Any sub-field may be zero/absent until
// its first probe completes (e.g. stats unset before the first Stats() call).
type InstanceRuntime struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Fleet    string                 `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// Raw backend probe, vs the reconciled persisted Instance.status.
	LiveStatus LiveContainerStatus `protobuf:"varint,3,opt,name=live_status,json=liveStatus,proto3,enum=fleetgrpc.LiveContainerStatus" json:"live_status,omitempty"`
	// "Is a coding agent running, and what is it doing": which tool + its
	// activity. Together these drive the per-row throbber + agent label.
	AgentTool     AgentTool     `protobuf:"varint,4,opt,name=agent_tool,json=agentTool,proto3,enum=fleetgrpc.AgentTool" json:"agent_tool,omitempty"`
	AgentActivity AgentActivity `protobuf:"varint,5,opt,name=agent_activity,json=agentActivity,proto3,enum=fleetgrpc.AgentActivity" json:"agent_activity,omitempty"`
	// CPU/memory. Absent (nil message) until first probed.
	Stats *ContainerStats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	// Live tmux sessions inside the container (populated for running/expanded
	// instances). The persisted pane layout is GroupLayout in domain.proto;
	// this is the live session list.
	Sessions []*TmuxSession `protobuf:"bytes,7,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Active port-forwards (the ⇄ labels).
	ForwardedPorts []*ForwardedPort `protobuf:"bytes,8,rep,name=forwarded_ports,json=forwardedPorts,proto3" json:"forwarded_ports,omitempty"`
	// Actual git branch resolved from the workspace (resolveWorkspaceBranch) —
	// live because the user may switch branches inside the instance; distinct
	// from the persisted REQUESTED Instance.branch. Optional: absent when there
	// is no local workspace (cloud backends) or it hasn't been resolved yet.
	CurrentBranch *string `protobuf:"bytes,9,opt,name=current_branch,json=currentBranch,proto3,oneof" json:"current_branch,omitempty"`
	// When the server last refreshed this snapshot.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Aggregated GitHub PR state — the "auto tag" shown when the instance has no
	// user-set tag. nil until first probed, or when gh is unavailable / no PR is
	// open (see PrStatus).
	PrStatus      *PrStatus `protobuf:"bytes,11,opt,name=pr_status,json=prStatus,proto3" json:"pr_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRuntime) Reset() {
	*x = InstanceRuntime{}
	mi := &file_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRuntime) ProtoMessage() {}

func (x *InstanceRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRuntime.ProtoReflect.Descriptor instead.
func (*InstanceRuntime) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *InstanceRuntime) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *InstanceRuntime) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *InstanceRuntime) GetLiveStatus() LiveContainerStatus {
	if x != nil {
		return x.LiveStatus
	}
	return LiveContainerStatus_LIVE_CONTAINER_STATUS_UNSPECIFIED
}

func (x *InstanceRuntime) GetAgentTool() AgentTool {
	if x != nil {
		return x.AgentTool
	}
	return AgentTool_AGENT_TOOL_UNSPECIFIED
}

func (x *InstanceRuntime) GetAgentActivity() AgentActivity {
	if x != nil {
		return x.AgentActivity
	}
	return AgentActivity_AGENT_ACTIVITY_UNSPECIFIED
}

func (x *InstanceRuntime) GetStats() *ContainerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *InstanceRuntime) GetSessions() []*TmuxSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *InstanceRuntime) GetForwardedPorts() []*ForwardedPort {
	if x != nil {
		return x.ForwardedPorts
	}
	return nil
}

func (x *InstanceRuntime) GetCurrentBranch() string {
	if x != nil && x.CurrentBranch != nil {
		return *x.CurrentBranch
	}
	return ""
}

func (x *InstanceRuntime) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *InstanceRuntime) GetPrStatus() *PrStatus {
	if x != nil {
		return x.PrStatus
	}
	return nil
}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\tfleetgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x0eContainerStats\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x01R\rcpuMillicores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x01R\bmemoryMb\"W\n" +
	"\vTmuxSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\awindows\x18\x02 \x01(\x05R\awindows\x12\x1a\n" +
	"\battached\x18\x03 \x01(\bR\battached\"t\n" +
	"\rForwardedPort\x12\x1d\n" +
	"\n" +
	"local_port\x18\x01 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\x05R\n" +
	"remotePort\x12\x19\n" +
	"\x05label\x18\x03 \x01(\tH\x00R\x05label\x88\x01\x01B\b\n" +
	"\x06_label\"G\n" +
	"\x05PrRef\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"\xb3\x02\n" +
	"\bPrStatus\x12\x1d\n" +
	"\n" +
	"open_count\x18\x01 \x01(\x05R\topenCount\x120\n" +
	"\tpr_signal\x18\x02 \x01(\x0e2\x13.fleetgrpc.PrSignalR\bprSignal\x120\n" +
	"\x06review\x18\x03 \x01(\x0e2\x18.fleetgrpc.PrReviewStateR\x06review\x12#\n" +
	"\rchecks_passed\x18\x04 \x01(\x05R\fchecksPassed\x12!\n" +
	"\fchecks_total\x18\x05 \x01(\x05R\vchecksTotal\x128\n" +
	"\rchecks_signal\x18\x06 \x01(\x0e2\x13.fleetgrpc.PrSignalR\fchecksSignal\x12\"\n" +
	"\x03prs\x18\a \x03(\v2\x10.fleetgrpc.PrRefR\x03prs\"\xd4\x04\n" +
	"\x0fInstanceRuntime\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12?\n" +
	"\vlive_status\x18\x03 \x01(\x0e2\x1e.fleetgrpc.LiveContainerStatusR\n" +
	"liveStatus\x123\n" +
	"\n" +
	"agent_tool\x18\x04 \x01(\x0e2\x14.fleetgrpc.AgentToolR\tagentTool\x12?\n" +
	"\x0eagent_activity\x18\x05 \x01(\x0e2\x18.fleetgrpc.AgentActivityR\ragentActivity\x12/\n" +
	"\x05stats\x18\x06 \x01(\v2\x19.fleetgrpc.ContainerStatsR\x05stats\x122\n" +
	"\bsessions\x18\a \x03(\v2\x16.fleetgrpc.TmuxSessionR\bsessions\x12A\n" +
	"\x0fforwarded_ports\x18\b \x03(\v2\x18.fleetgrpc.ForwardedPortR\x0eforwardedPorts\x12*\n" +
	"\x0ecurrent_branch\x18\t \x01(\tH\x00R\rcurrentBranch\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\tpr_status\x18\v \x01(\v2\x13.fleetgrpc.PrStatusR\bprStatusB\x11\n" +
	"\x0f_current_branchJ\x04\b\f\x10\x15*\xc8\x01\n" +
	"\x13LiveContainerStatus\x12%\n" +
	"!LIVE_CONTAINER_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dLIVE_CONTAINER_STATUS_RUNNING\x10\x01\x12!\n" +
	"\x1dLIVE_CONTAINER_STATUS_STOPPED\x10\x02\x12!\n" +
	"\x1dLIVE_CONTAINER_STATUS_MISSING\x10\x03\x12!\n" +
	"\x1dLIVE_CONTAINER_STATUS_UNKNOWN\x10\x04*\xaf\x01\n" +
	"\tAgentTool\x12\x1a\n" +
	"\x16AGENT_TOOL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAGENT_TOOL_NONE\x10\x01\x12\x15\n" +
	"\x11AGENT_TOOL_CLAUDE\x10\x02\x12\x14\n" +
	"\x10AGENT_TOOL_CODEX\x10\x03\x12\x15\n" +
	"\x11AGENT_TOOL_GEMINI\x10\x04\x12\x16\n" +
	"\x12AGENT_TOOL_COPILOT\x10\x05\x12\x15\n" +
	"\x11AGENT_TOOL_AUGGIE\x10\x06*\x87\x01\n" +
	"\rAgentActivity\x12\x1e\n" +
	"\x1aAGENT_ACTIVITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAGENT_ACTIVITY_NOT_RUNNING\x10\x01\x12\x1a\n" +
	"\x16AGENT_ACTIVITY_WORKING\x10\x02\x12\x1a\n" +
	"\x16AGENT_ACTIVITY_WAITING\x10\x03*c\n" +
	"\bPrSignal\x12\x19\n" +
	"\x15PR_SIGNAL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPR_SIGNAL_GREEN\x10\x01\x12\x14\n" +
	"\x10PR_SIGNAL_YELLOW\x10\x02\x12\x11\n" +
	"\rPR_SIGNAL_RED\x10\x03*\x92\x01\n" +
	"\rPrReviewState\x12\x1f\n" +
	"\x1bPR_REVIEW_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PR_REVIEW_STATE_APPROVED\x10\x01\x12%\n" +
	"!PR_REVIEW_STATE_CHANGES_REQUESTED\x10\x02\x12\x1b\n" +
	"\x17PR_REVIEW_STATE_PENDING\x10\x03B:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runtime_proto_goTypes = []any{
	(LiveContainerStatus)(0),      // 0: fleetgrpc.LiveContainerStatus
	(AgentTool)(0),                // 1: fleetgrpc.AgentTool
	(AgentActivity)(0),            // 2: fleetgrpc.AgentActivity
	(PrSignal)(0),                 // 3: fleetgrpc.PrSignal
	(PrReviewState)(0),            // 4: fleetgrpc.PrReviewState
	(*ContainerStats)(nil),        // 5: fleetgrpc.ContainerStats
	(*TmuxSession)(nil),           // 6: fleetgrpc.TmuxSession
	(*ForwardedPort)(nil),         // 7: fleetgrpc.ForwardedPort
	(*PrRef)(nil),                 // 8: fleetgrpc.PrRef
	(*PrStatus)(nil),              // 9: fleetgrpc.PrStatus
	(*InstanceRuntime)(nil),       // 10: fleetgrpc.InstanceRuntime
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_runtime_proto_depIdxs = []int32{
	3,  // 0: fleetgrpc.PrStatus.pr_signal:type_name -> fleetgrpc.PrSignal
	4,  // 1: fleetgrpc.PrStatus.review:type_name -> fleetgrpc.PrReviewState
	3,  // 2: fleetgrpc.PrStatus.checks_signal:type_name -> fleetgrpc.PrSignal
	8,  // 3: fleetgrpc.PrStatus.prs:type_name -> fleetgrpc.PrRef
	0,  // 4: fleetgrpc.InstanceRuntime.live_status:type_name -> fleetgrpc.LiveContainerStatus
	1,  // 5: fleetgrpc.InstanceRuntime.agent_tool:type_name -> fleetgrpc.AgentTool
	2,  // 6: fleetgrpc.InstanceRuntime.agent_activity:type_name -> fleetgrpc.AgentActivity
	5,  // 7: fleetgrpc.InstanceRuntime.stats:type_name -> fleetgrpc.ContainerStats
	6,  // 8: fleetgrpc.InstanceRuntime.sessions:type_name -> fleetgrpc.TmuxSession
	7,  // 9: fleetgrpc.InstanceRuntime.forwarded_ports:type_name -> fleetgrpc.ForwardedPort
	11, // 10: fleetgrpc.InstanceRuntime.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 11: fleetgrpc.InstanceRuntime.pr_status:type_name -> fleetgrpc.PrStatus
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	file_runtime_proto_msgTypes[2].OneofWrappers = []any{}
	file_runtime_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		EnumInfos:         file_runtime_proto_enumTypes,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
