// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tfleetgrpc\x1a\farmada.proto\x1a\rcontrol.proto\x1a\vwatch.proto\x1a\n" +
	"jobs.proto\x1a\fconfig.proto\x1a\n" +
	"exec.proto\x1a\rinspect.proto2\xe1\x19\n" +
	"\fFleetService\x127\n" +
	"\x05Hello\x12\x17.fleetgrpc.HelloRequest\x1a\x15.fleetgrpc.HelloReply\x12@\n" +
	"\bShutdown\x12\x1a.fleetgrpc.ShutdownRequest\x1a\x18.fleetgrpc.ShutdownReply\x12[\n" +
	"\x11FleetTUIConnected\x12#.fleetgrpc.FleetTUIConnectedRequest\x1a!.fleetgrpc.FleetTUIConnectedReply\x12@\n" +
	"\bGetState\x12\x1a.fleetgrpc.GetStateRequest\x1a\x18.fleetgrpc.GetStateReply\x124\n" +
	"\x05Watch\x12\x17.fleetgrpc.WatchRequest\x1a\x10.fleetgrpc.Event0\x01\x12I\n" +
	"\x0eCreateInstance\x12 .fleetgrpc.CreateInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12K\n" +
	"\x0fDestroyInstance\x12!.fleetgrpc.DestroyInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12G\n" +
	"\rStartInstance\x12\x1f.fleetgrpc.StartInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12E\n" +
	"\fStopInstance\x12\x1e.fleetgrpc.StopInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12G\n" +
	"\rCloneInstance\x12\x1f.fleetgrpc.CloneInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12K\n" +
	"\x0fRebuildInstance\x12!.fleetgrpc.RebuildInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12F\n" +
	"\vCreateFleet\x12\x1d.fleetgrpc.CreateFleetRequest\x1a\x18.fleetgrpc.MutationReply\x12H\n" +
	"\fDestroyFleet\x12\x1e.fleetgrpc.DestroyFleetRequest\x1a\x18.fleetgrpc.MutationReply\x12P\n" +
	"\x10SetFleetSettings\x12\".fleetgrpc.SetFleetSettingsRequest\x1a\x18.fleetgrpc.MutationReply\x12a\n" +
	"\x13DeleteBuildkitCache\x12%.fleetgrpc.DeleteBuildkitCacheRequest\x1a#.fleetgrpc.DeleteBuildkitCacheReply\x12R\n" +
	"\x0eDeleteDebCache\x12 .fleetgrpc.DeleteDebCacheRequest\x1a\x1e.fleetgrpc.DeleteDebCacheReply\x12X\n" +
	"\x10DeleteImageCache\x12\".fleetgrpc.DeleteImageCacheRequest\x1a .fleetgrpc.DeleteImageCacheReply\x12V\n" +
	"\x13SetInstanceMetadata\x12%.fleetgrpc.SetInstanceMetadataRequest\x1a\x18.fleetgrpc.MutationReply\x12L\n" +
	"\x0eSetGroupLayout\x12 .fleetgrpc.SetGroupLayoutRequest\x1a\x18.fleetgrpc.MutationReply\x12R\n" +
	"\x11DeleteGroupLayout\x12#.fleetgrpc.DeleteGroupLayoutRequest\x1a\x18.fleetgrpc.MutationReply\x12T\n" +
	"\x12SetLastSeenVersion\x12$.fleetgrpc.SetLastSeenVersionRequest\x1a\x18.fleetgrpc.MutationReply\x12C\n" +
	"\tGetConfig\x12\x1b.fleetgrpc.GetConfigRequest\x1a\x19.fleetgrpc.GetConfigReply\x12C\n" +
	"\tSetConfig\x12\x1b.fleetgrpc.SetConfigRequest\x1a\x19.fleetgrpc.SetConfigReply\x12C\n" +
	"\tGetArmada\x12\x1b.fleetgrpc.GetArmadaRequest\x1a\x19.fleetgrpc.GetArmadaReply\x12C\n" +
	"\tSetArmada\x12\x1b.fleetgrpc.SetArmadaRequest\x1a\x19.fleetgrpc.SetArmadaReply\x12a\n" +
	"\x13ResolveArmadaRemote\x12%.fleetgrpc.ResolveArmadaRemoteRequest\x1a#.fleetgrpc.ResolveArmadaRemoteReply\x12U\n" +
	"\x0fTrustSSHHostKey\x12!.fleetgrpc.TrustSSHHostKeyRequest\x1a\x1f.fleetgrpc.TrustSSHHostKeyReply\x12K\n" +
	"\vGitHostKeys\x12\x1b.fleetgrpc.GitHostKeyAnswer\x1a\x1b.fleetgrpc.GitHostKeyPrompt(\x010\x01\x121\n" +
	"\x04Exec\x12\x11.fleetgrpc.ExecIn\x1a\x12.fleetgrpc.ExecOut(\x010\x01\x12^\n" +
	"\x12ResolveExecCommand\x12$.fleetgrpc.ResolveExecCommandRequest\x1a\".fleetgrpc.ResolveExecCommandReply\x12^\n" +
	"\x12ResolveLogsCommand\x12$.fleetgrpc.ResolveLogsCommandRequest\x1a\".fleetgrpc.ResolveLogsCommandReply\x124\n" +
	"\x04Logs\x12\x16.fleetgrpc.LogsRequest\x1a\x12.fleetgrpc.LogLine0\x01\x12I\n" +
	"\vTriggerLogs\x12\x1d.fleetgrpc.TriggerLogsRequest\x1a\x1b.fleetgrpc.TriggerLogsReply\x12?\n" +
	"\aForward\x12\x17.fleetgrpc.ForwardChunk\x1a\x17.fleetgrpc.ForwardChunk(\x010\x01\x12/\n" +
	"\x03Mic\x12\x10.fleetgrpc.MicUp\x1a\x12.fleetgrpc.MicDown(\x010\x01\x12R\n" +
	"\x0eListMicSources\x12 .fleetgrpc.ListMicSourcesRequest\x1a\x1e.fleetgrpc.ListMicSourcesReply\x12>\n" +
	"\bSSHAgent\x12\x15.fleetgrpc.SSHAgentUp\x1a\x17.fleetgrpc.SSHAgentDown(\x010\x01\x12B\n" +
	"\bCopyFile\x12\x1a.fleetgrpc.CopyFileRequest\x1a\x18.fleetgrpc.CopyFileChunk0\x01\x12@\n" +
	"\bCopyInto\x12\x18.fleetgrpc.CopyIntoChunk\x1a\x18.fleetgrpc.CopyIntoReply(\x01\x12I\n" +
	"\vInspectRepo\x12\x1d.fleetgrpc.InspectRepoRequest\x1a\x1b.fleetgrpc.InspectRepoReply\x12j\n" +
	"\x16GetCoderTemplateParams\x12(.fleetgrpc.GetCoderTemplateParamsRequest\x1a&.fleetgrpc.GetCoderTemplateParamsReply\x12X\n" +
	"\x10GetBrowserConfig\x12\".fleetgrpc.GetBrowserConfigRequest\x1a .fleetgrpc.GetBrowserConfigReply\x12R\n" +
	"\x0ePrepareBrowser\x12 .fleetgrpc.PrepareBrowserRequest\x1a\x1e.fleetgrpc.PrepareBrowserReplyB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var file_service_proto_goTypes = []any{
	(*HelloRequest)(nil),                  // 0: fleetgrpc.HelloRequest
	(*ShutdownRequest)(nil),               // 1: fleetgrpc.ShutdownRequest
	(*FleetTUIConnectedRequest)(nil),      // 2: fleetgrpc.FleetTUIConnectedRequest
	(*GetStateRequest)(nil),               // 3: fleetgrpc.GetStateRequest
	(*WatchRequest)(nil),                  // 4: fleetgrpc.WatchRequest
	(*CreateInstanceRequest)(nil),         // 5: fleetgrpc.CreateInstanceRequest
	(*DestroyInstanceRequest)(nil),        // 6: fleetgrpc.DestroyInstanceRequest
	(*StartInstanceRequest)(nil),          // 7: fleetgrpc.StartInstanceRequest
	(*StopInstanceRequest)(nil),           // 8: fleetgrpc.StopInstanceRequest
	(*CloneInstanceRequest)(nil),          // 9: fleetgrpc.CloneInstanceRequest
	(*RebuildInstanceRequest)(nil),        // 10: fleetgrpc.RebuildInstanceRequest
	(*CreateFleetRequest)(nil),            // 11: fleetgrpc.CreateFleetRequest
	(*DestroyFleetRequest)(nil),           // 12: fleetgrpc.DestroyFleetRequest
	(*SetFleetSettingsRequest)(nil),       // 13: fleetgrpc.SetFleetSettingsRequest
	(*DeleteBuildkitCacheRequest)(nil),    // 14: fleetgrpc.DeleteBuildkitCacheRequest
	(*DeleteDebCacheRequest)(nil),         // 15: fleetgrpc.DeleteDebCacheRequest
	(*DeleteImageCacheRequest)(nil),       // 16: fleetgrpc.DeleteImageCacheRequest
	(*SetInstanceMetadataRequest)(nil),    // 17: fleetgrpc.SetInstanceMetadataRequest
	(*SetGroupLayoutRequest)(nil),         // 18: fleetgrpc.SetGroupLayoutRequest
	(*DeleteGroupLayoutRequest)(nil),      // 19: fleetgrpc.DeleteGroupLayoutRequest
	(*SetLastSeenVersionRequest)(nil),     // 20: fleetgrpc.SetLastSeenVersionRequest
	(*GetConfigRequest)(nil),              // 21: fleetgrpc.GetConfigRequest
	(*SetConfigRequest)(nil),              // 22: fleetgrpc.SetConfigRequest
	(*GetArmadaRequest)(nil),              // 23: fleetgrpc.GetArmadaRequest
	(*SetArmadaRequest)(nil),              // 24: fleetgrpc.SetArmadaRequest
	(*ResolveArmadaRemoteRequest)(nil),    // 25: fleetgrpc.ResolveArmadaRemoteRequest
	(*TrustSSHHostKeyRequest)(nil),        // 26: fleetgrpc.TrustSSHHostKeyRequest
	(*GitHostKeyAnswer)(nil),              // 27: fleetgrpc.GitHostKeyAnswer
	(*ExecIn)(nil),                        // 28: fleetgrpc.ExecIn
	(*ResolveExecCommandRequest)(nil),     // 29: fleetgrpc.ResolveExecCommandRequest
	(*ResolveLogsCommandRequest)(nil),     // 30: fleetgrpc.ResolveLogsCommandRequest
	(*LogsRequest)(nil),                   // 31: fleetgrpc.LogsRequest
	(*TriggerLogsRequest)(nil),            // 32: fleetgrpc.TriggerLogsRequest
	(*ForwardChunk)(nil),                  // 33: fleetgrpc.ForwardChunk
	(*MicUp)(nil),                         // 34: fleetgrpc.MicUp
	(*ListMicSourcesRequest)(nil),         // 35: fleetgrpc.ListMicSourcesRequest
	(*SSHAgentUp)(nil),                    // 36: fleetgrpc.SSHAgentUp
	(*CopyFileRequest)(nil),               // 37: fleetgrpc.CopyFileRequest
	(*CopyIntoChunk)(nil),                 // 38: fleetgrpc.CopyIntoChunk
	(*InspectRepoRequest)(nil),            // 39: fleetgrpc.InspectRepoRequest
	(*GetCoderTemplateParamsRequest)(nil), // 40: fleetgrpc.GetCoderTemplateParamsRequest
	(*GetBrowserConfigRequest)(nil),       // 41: fleetgrpc.GetBrowserConfigRequest
	(*PrepareBrowserRequest)(nil),         // 42: fleetgrpc.PrepareBrowserRequest
	(*HelloReply)(nil),                    // 43: fleetgrpc.HelloReply
	(*ShutdownReply)(nil),                 // 44: fleetgrpc.ShutdownReply
	(*FleetTUIConnectedReply)(nil),        // 45: fleetgrpc.FleetTUIConnectedReply
	(*GetStateReply)(nil),                 // 46: fleetgrpc.GetStateReply
	(*Event)(nil),                         // 47: fleetgrpc.Event
	(*JobEvent)(nil),                      // 48: fleetgrpc.JobEvent
	(*MutationReply)(nil),                 // 49: fleetgrpc.MutationReply
	(*DeleteBuildkitCacheReply)(nil),      // 50: fleetgrpc.DeleteBuildkitCacheReply
	(*DeleteDebCacheReply)(nil),           // 51: fleetgrpc.DeleteDebCacheReply
	(*DeleteImageCacheReply)(nil),         // 52: fleetgrpc.DeleteImageCacheReply
	(*GetConfigReply)(nil),                // 53: fleetgrpc.GetConfigReply
	(*SetConfigReply)(nil),                // 54: fleetgrpc.SetConfigReply
	(*GetArmadaReply)(nil),                // 55: fleetgrpc.GetArmadaReply
	(*SetArmadaReply)(nil),                // 56: fleetgrpc.SetArmadaReply
	(*ResolveArmadaRemoteReply)(nil),      // 57: fleetgrpc.ResolveArmadaRemoteReply
	(*TrustSSHHostKeyReply)(nil),          // 58: fleetgrpc.TrustSSHHostKeyReply
	(*GitHostKeyPrompt)(nil),              // 59: fleetgrpc.GitHostKeyPrompt
	(*ExecOut)(nil),                       // 60: fleetgrpc.ExecOut
	(*ResolveExecCommandReply)(nil),       // 61: fleetgrpc.ResolveExecCommandReply
	(*ResolveLogsCommandReply)(nil),       // 62: fleetgrpc.ResolveLogsCommandReply
	(*LogLine)(nil),                       // 63: fleetgrpc.LogLine
	(*TriggerLogsReply)(nil),              // 64: fleetgrpc.TriggerLogsReply
	(*MicDown)(nil),                       // 65: fleetgrpc.MicDown
	(*ListMicSourcesReply)(nil),           // 66: fleetgrpc.ListMicSourcesReply
	(*SSHAgentDown)(nil),                  // 67: fleetgrpc.SSHAgentDown
	(*CopyFileChunk)(nil),                 // 68: fleetgrpc.CopyFileChunk
	(*CopyIntoReply)(nil),                 // 69: fleetgrpc.CopyIntoReply
	(*InspectRepoReply)(nil),              // 70: fleetgrpc.InspectRepoReply
	(*GetCoderTemplateParamsReply)(nil),   // 71: fleetgrpc.GetCoderTemplateParamsReply
	(*GetBrowserConfigReply)(nil),         // 72: fleetgrpc.GetBrowserConfigReply
	(*PrepareBrowserReply)(nil),           // 73: fleetgrpc.PrepareBrowserReply
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: fleetgrpc.FleetService.Hello:input_type -> fleetgrpc.HelloRequest
	1,  // 1: fleetgrpc.FleetService.Shutdown:input_type -> fleetgrpc.ShutdownRequest
	2,  // 2: fleetgrpc.FleetService.FleetTUIConnected:input_type -> fleetgrpc.FleetTUIConnectedRequest
	3,  // 3: fleetgrpc.FleetService.GetState:input_type -> fleetgrpc.GetStateRequest
	4,  // 4: fleetgrpc.FleetService.Watch:input_type -> fleetgrpc.WatchRequest
	5,  // 5: fleetgrpc.FleetService.CreateInstance:input_type -> fleetgrpc.CreateInstanceRequest
	6,  // 6: fleetgrpc.FleetService.DestroyInstance:input_type -> fleetgrpc.DestroyInstanceRequest
	7,  // 7: fleetgrpc.FleetService.StartInstance:input_type -> fleetgrpc.StartInstanceRequest
	8,  // 8: fleetgrpc.FleetService.StopInstance:input_type -> fleetgrpc.StopInstanceRequest
	9,  // 9: fleetgrpc.FleetService.CloneInstance:input_type -> fleetgrpc.CloneInstanceRequest
	10, // 10: fleetgrpc.FleetService.RebuildInstance:input_type -> fleetgrpc.RebuildInstanceRequest
	11, // 11: fleetgrpc.FleetService.CreateFleet:input_type -> fleetgrpc.CreateFleetRequest
	12, // 12: fleetgrpc.FleetService.DestroyFleet:input_type -> fleetgrpc.DestroyFleetRequest
	13, // 13: fleetgrpc.FleetService.SetFleetSettings:input_type -> fleetgrpc.SetFleetSettingsRequest
	14, // 14: fleetgrpc.FleetService.DeleteBuildkitCache:input_type -> fleetgrpc.DeleteBuildkitCacheRequest
	15, // 15: fleetgrpc.FleetService.DeleteDebCache:input_type -> fleetgrpc.DeleteDebCacheRequest
	16, // 16: fleetgrpc.FleetService.DeleteImageCache:input_type -> fleetgrpc.DeleteImageCacheRequest
	17, // 17: fleetgrpc.FleetService.SetInstanceMetadata:input_type -> fleetgrpc.SetInstanceMetadataRequest
	18, // 18: fleetgrpc.FleetService.SetGroupLayout:input_type -> fleetgrpc.SetGroupLayoutRequest
	19, // 19: fleetgrpc.FleetService.DeleteGroupLayout:input_type -> fleetgrpc.DeleteGroupLayoutRequest
	20, // 20: fleetgrpc.FleetService.SetLastSeenVersion:input_type -> fleetgrpc.SetLastSeenVersionRequest
	21, // 21: fleetgrpc.FleetService.GetConfig:input_type -> fleetgrpc.GetConfigRequest
	22, // 22: fleetgrpc.FleetService.SetConfig:input_type -> fleetgrpc.SetConfigRequest
	23, // 23: fleetgrpc.FleetService.GetArmada:input_type -> fleetgrpc.GetArmadaRequest
	24, // 24: fleetgrpc.FleetService.SetArmada:input_type -> fleetgrpc.SetArmadaRequest
	25, // 25: fleetgrpc.FleetService.ResolveArmadaRemote:input_type -> fleetgrpc.ResolveArmadaRemoteRequest
	26, // 26: fleetgrpc.FleetService.TrustSSHHostKey:input_type -> fleetgrpc.TrustSSHHostKeyRequest
	27, // 27: fleetgrpc.FleetService.GitHostKeys:input_type -> fleetgrpc.GitHostKeyAnswer
	28, // 28: fleetgrpc.FleetService.Exec:input_type -> fleetgrpc.ExecIn
	29, // 29: fleetgrpc.FleetService.ResolveExecCommand:input_type -> fleetgrpc.ResolveExecCommandRequest
	30, // 30: fleetgrpc.FleetService.ResolveLogsCommand:input_type -> fleetgrpc.ResolveLogsCommandRequest
	31, // 31: fleetgrpc.FleetService.Logs:input_type -> fleetgrpc.LogsRequest
	32, // 32: fleetgrpc.FleetService.TriggerLogs:input_type -> fleetgrpc.TriggerLogsRequest
	33, // 33: fleetgrpc.FleetService.Forward:input_type -> fleetgrpc.ForwardChunk
	34, // 34: fleetgrpc.FleetService.Mic:input_type -> fleetgrpc.MicUp
	35, // 35: fleetgrpc.FleetService.ListMicSources:input_type -> fleetgrpc.ListMicSourcesRequest
	36, // 36: fleetgrpc.FleetService.SSHAgent:input_type -> fleetgrpc.SSHAgentUp
	37, // 37: fleetgrpc.FleetService.CopyFile:input_type -> fleetgrpc.CopyFileRequest
	38, // 38: fleetgrpc.FleetService.CopyInto:input_type -> fleetgrpc.CopyIntoChunk
	39, // 39: fleetgrpc.FleetService.InspectRepo:input_type -> fleetgrpc.InspectRepoRequest
	40, // 40: fleetgrpc.FleetService.GetCoderTemplateParams:input_type -> fleetgrpc.GetCoderTemplateParamsRequest
	41, // 41: fleetgrpc.FleetService.GetBrowserConfig:input_type -> fleetgrpc.GetBrowserConfigRequest
	42, // 42: fleetgrpc.FleetService.PrepareBrowser:input_type -> fleetgrpc.PrepareBrowserRequest
	43, // 43: fleetgrpc.FleetService.Hello:output_type -> fleetgrpc.HelloReply
	44, // 44: fleetgrpc.FleetService.Shutdown:output_type -> fleetgrpc.ShutdownReply
	45, // 45: fleetgrpc.FleetService.FleetTUIConnected:output_type -> fleetgrpc.FleetTUIConnectedReply
	46, // 46: fleetgrpc.FleetService.GetState:output_type -> fleetgrpc.GetStateReply
	47, // 47: fleetgrpc.FleetService.Watch:output_type -> fleetgrpc.Event
	48, // 48: fleetgrpc.FleetService.CreateInstance:output_type -> fleetgrpc.JobEvent
	48, // 49: fleetgrpc.FleetService.DestroyInstance:output_type -> fleetgrpc.JobEvent
	48, // 50: fleetgrpc.FleetService.StartInstance:output_type -> fleetgrpc.JobEvent
	48, // 51: fleetgrpc.FleetService.StopInstance:output_type -> fleetgrpc.JobEvent
	48, // 52: fleetgrpc.FleetService.CloneInstance:output_type -> fleetgrpc.JobEvent
	48, // 53: fleetgrpc.FleetService.RebuildInstance:output_type -> fleetgrpc.JobEvent
	49, // 54: fleetgrpc.FleetService.CreateFleet:output_type -> fleetgrpc.MutationReply
	49, // 55: fleetgrpc.FleetService.DestroyFleet:output_type -> fleetgrpc.MutationReply
	49, // 56: fleetgrpc.FleetService.SetFleetSettings:output_type -> fleetgrpc.MutationReply
	50, // 57: fleetgrpc.FleetService.DeleteBuildkitCache:output_type -> fleetgrpc.DeleteBuildkitCacheReply
	51, // 58: fleetgrpc.FleetService.DeleteDebCache:output_type -> fleetgrpc.DeleteDebCacheReply
	52, // 59: fleetgrpc.FleetService.DeleteImageCache:output_type -> fleetgrpc.DeleteImageCacheReply
	49, // 60: fleetgrpc.FleetService.SetInstanceMetadata:output_type -> fleetgrpc.MutationReply
	49, // 61: fleetgrpc.FleetService.SetGroupLayout:output_type -> fleetgrpc.MutationReply
	49, // 62: fleetgrpc.FleetService.DeleteGroupLayout:output_type -> fleetgrpc.MutationReply
	49, // 63: fleetgrpc.FleetService.SetLastSeenVersion:output_type -> fleetgrpc.MutationReply
	53, // 64: fleetgrpc.FleetService.GetConfig:output_type -> fleetgrpc.GetConfigReply
	54, // 65: fleetgrpc.FleetService.SetConfig:output_type -> fleetgrpc.SetConfigReply
	55, // 66: fleetgrpc.FleetService.GetArmada:output_type -> fleetgrpc.GetArmadaReply
	56, // 67: fleetgrpc.FleetService.SetArmada:output_type -> fleetgrpc.SetArmadaReply
	57, // 68: fleetgrpc.FleetService.ResolveArmadaRemote:output_type -> fleetgrpc.ResolveArmadaRemoteReply
	58, // 69: fleetgrpc.FleetService.TrustSSHHostKey:output_type -> fleetgrpc.TrustSSHHostKeyReply
	59, // 70: fleetgrpc.FleetService.GitHostKeys:output_type -> fleetgrpc.GitHostKeyPrompt
	60, // 71: fleetgrpc.FleetService.Exec:output_type -> fleetgrpc.ExecOut
	61, // 72: fleetgrpc.FleetService.ResolveExecCommand:output_type -> fleetgrpc.ResolveExecCommandReply
	62, // 73: fleetgrpc.FleetService.ResolveLogsCommand:output_type -> fleetgrpc.ResolveLogsCommandReply
	63, // 74: fleetgrpc.FleetService.Logs:output_type -> fleetgrpc.LogLine
	64, // 75: fleetgrpc.FleetService.TriggerLogs:output_type -> fleetgrpc.TriggerLogsReply
	33, // 76: fleetgrpc.FleetService.Forward:output_type -> fleetgrpc.ForwardChunk
	65, // 77: fleetgrpc.FleetService.Mic:output_type -> fleetgrpc.MicDown
	66, // 78: fleetgrpc.FleetService.ListMicSources:output_type -> fleetgrpc.ListMicSourcesReply
	67, // 79: fleetgrpc.FleetService.SSHAgent:output_type -> fleetgrpc.SSHAgentDown
	68, // 80: fleetgrpc.FleetService.CopyFile:output_type -> fleetgrpc.CopyFileChunk
	69, // 81: fleetgrpc.FleetService.CopyInto:output_type -> fleetgrpc.CopyIntoReply
	70, // 82: fleetgrpc.FleetService.InspectRepo:output_type -> fleetgrpc.InspectRepoReply
	71, // 83: fleetgrpc.FleetService.GetCoderTemplateParams:output_type -> fleetgrpc.GetCoderTemplateParamsReply
	72, // 84: fleetgrpc.FleetService.GetBrowserConfig:output_type -> fleetgrpc.GetBrowserConfigReply
	73, // 85: fleetgrpc.FleetService.PrepareBrowser:output_type -> fleetgrpc.PrepareBrowserReply
	43, // [43:86] is the sub-list for method output_type
	0,  // [0:43] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_armada_proto_init()
	file_control_proto_init()
	file_watch_proto_init()
	file_jobs_proto_init()
	file_config_proto_init()
	file_exec_proto_init()
	file_inspect_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
