// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tfleetgrpc\x1a\rcontrol.proto\x1a\vwatch.proto\x1a\n" +
	"jobs.proto\x1a\fconfig.proto\x1a\n" +
	"exec.proto2\xe6\x12\n" +
	"\fFleetService\x127\n" +
	"\x05Hello\x12\x17.fleetgrpc.HelloRequest\x1a\x15.fleetgrpc.HelloReply\x12@\n" +
	"\bShutdown\x12\x1a.fleetgrpc.ShutdownRequest\x1a\x18.fleetgrpc.ShutdownReply\x12[\n" +
	"\x11FleetTUIConnected\x12#.fleetgrpc.FleetTUIConnectedRequest\x1a!.fleetgrpc.FleetTUIConnectedReply\x12@\n" +
	"\bGetState\x12\x1a.fleetgrpc.GetStateRequest\x1a\x18.fleetgrpc.GetStateReply\x124\n" +
	"\x05Watch\x12\x17.fleetgrpc.WatchRequest\x1a\x10.fleetgrpc.Event0\x01\x12I\n" +
	"\x0eCreateInstance\x12 .fleetgrpc.CreateInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12K\n" +
	"\x0fDestroyInstance\x12!.fleetgrpc.DestroyInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12G\n" +
	"\rStartInstance\x12\x1f.fleetgrpc.StartInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12E\n" +
	"\fStopInstance\x12\x1e.fleetgrpc.StopInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12G\n" +
	"\rCloneInstance\x12\x1f.fleetgrpc.CloneInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12F\n" +
	"\vCreateFleet\x12\x1d.fleetgrpc.CreateFleetRequest\x1a\x18.fleetgrpc.MutationReply\x12H\n" +
	"\fDestroyFleet\x12\x1e.fleetgrpc.DestroyFleetRequest\x1a\x18.fleetgrpc.MutationReply\x12P\n" +
	"\x10SetFleetSettings\x12\".fleetgrpc.SetFleetSettingsRequest\x1a\x18.fleetgrpc.MutationReply\x12a\n" +
	"\x13DeleteBuildkitCache\x12%.fleetgrpc.DeleteBuildkitCacheRequest\x1a#.fleetgrpc.DeleteBuildkitCacheReply\x12R\n" +
	"\x0eDeleteDebCache\x12 .fleetgrpc.DeleteDebCacheRequest\x1a\x1e.fleetgrpc.DeleteDebCacheReply\x12X\n" +
	"\x10DeleteImageCache\x12\".fleetgrpc.DeleteImageCacheRequest\x1a .fleetgrpc.DeleteImageCacheReply\x12V\n" +
	"\x13SetInstanceMetadata\x12%.fleetgrpc.SetInstanceMetadataRequest\x1a\x18.fleetgrpc.MutationReply\x12L\n" +
	"\x0eSetGroupLayout\x12 .fleetgrpc.SetGroupLayoutRequest\x1a\x18.fleetgrpc.MutationReply\x12R\n" +
	"\x11DeleteGroupLayout\x12#.fleetgrpc.DeleteGroupLayoutRequest\x1a\x18.fleetgrpc.MutationReply\x12T\n" +
	"\x12SetLastSeenVersion\x12$.fleetgrpc.SetLastSeenVersionRequest\x1a\x18.fleetgrpc.MutationReply\x12C\n" +
	"\tGetConfig\x12\x1b.fleetgrpc.GetConfigRequest\x1a\x19.fleetgrpc.GetConfigReply\x12C\n" +
	"\tSetConfig\x12\x1b.fleetgrpc.SetConfigRequest\x1a\x19.fleetgrpc.SetConfigReply\x121\n" +
	"\x04Exec\x12\x11.fleetgrpc.ExecIn\x1a\x12.fleetgrpc.ExecOut(\x010\x01\x12^\n" +
	"\x12ResolveExecCommand\x12$.fleetgrpc.ResolveExecCommandRequest\x1a\".fleetgrpc.ResolveExecCommandReply\x12^\n" +
	"\x12ResolveLogsCommand\x12$.fleetgrpc.ResolveLogsCommandRequest\x1a\".fleetgrpc.ResolveLogsCommandReply\x124\n" +
	"\x04Logs\x12\x16.fleetgrpc.LogsRequest\x1a\x12.fleetgrpc.LogLine0\x01\x12?\n" +
	"\aForward\x12\x17.fleetgrpc.ForwardChunk\x1a\x17.fleetgrpc.ForwardChunk(\x010\x01\x12B\n" +
	"\bCopyFile\x12\x1a.fleetgrpc.CopyFileRequest\x1a\x18.fleetgrpc.CopyFileChunk0\x01\x12j\n" +
	"\x16GetCoderTemplateParams\x12(.fleetgrpc.GetCoderTemplateParamsRequest\x1a&.fleetgrpc.GetCoderTemplateParamsReply\x12X\n" +
	"\x10GetBrowserConfig\x12\".fleetgrpc.GetBrowserConfigRequest\x1a .fleetgrpc.GetBrowserConfigReply\x12R\n" +
	"\x0ePrepareBrowser\x12 .fleetgrpc.PrepareBrowserRequest\x1a\x1e.fleetgrpc.PrepareBrowserReplyB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var file_service_proto_goTypes = []any{
	(*HelloRequest)(nil),                  // 0: fleetgrpc.HelloRequest
	(*ShutdownRequest)(nil),               // 1: fleetgrpc.ShutdownRequest
	(*FleetTUIConnectedRequest)(nil),      // 2: fleetgrpc.FleetTUIConnectedRequest
	(*GetStateRequest)(nil),               // 3: fleetgrpc.GetStateRequest
	(*WatchRequest)(nil),                  // 4: fleetgrpc.WatchRequest
	(*CreateInstanceRequest)(nil),         // 5: fleetgrpc.CreateInstanceRequest
	(*DestroyInstanceRequest)(nil),        // 6: fleetgrpc.DestroyInstanceRequest
	(*StartInstanceRequest)(nil),          // 7: fleetgrpc.StartInstanceRequest
	(*StopInstanceRequest)(nil),           // 8: fleetgrpc.StopInstanceRequest
	(*CloneInstanceRequest)(nil),          // 9: fleetgrpc.CloneInstanceRequest
	(*CreateFleetRequest)(nil),            // 10: fleetgrpc.CreateFleetRequest
	(*DestroyFleetRequest)(nil),           // 11: fleetgrpc.DestroyFleetRequest
	(*SetFleetSettingsRequest)(nil),       // 12: fleetgrpc.SetFleetSettingsRequest
	(*DeleteBuildkitCacheRequest)(nil),    // 13: fleetgrpc.DeleteBuildkitCacheRequest
	(*DeleteDebCacheRequest)(nil),         // 14: fleetgrpc.DeleteDebCacheRequest
	(*DeleteImageCacheRequest)(nil),       // 15: fleetgrpc.DeleteImageCacheRequest
	(*SetInstanceMetadataRequest)(nil),    // 16: fleetgrpc.SetInstanceMetadataRequest
	(*SetGroupLayoutRequest)(nil),         // 17: fleetgrpc.SetGroupLayoutRequest
	(*DeleteGroupLayoutRequest)(nil),      // 18: fleetgrpc.DeleteGroupLayoutRequest
	(*SetLastSeenVersionRequest)(nil),     // 19: fleetgrpc.SetLastSeenVersionRequest
	(*GetConfigRequest)(nil),              // 20: fleetgrpc.GetConfigRequest
	(*SetConfigRequest)(nil),              // 21: fleetgrpc.SetConfigRequest
	(*ExecIn)(nil),                        // 22: fleetgrpc.ExecIn
	(*ResolveExecCommandRequest)(nil),     // 23: fleetgrpc.ResolveExecCommandRequest
	(*ResolveLogsCommandRequest)(nil),     // 24: fleetgrpc.ResolveLogsCommandRequest
	(*LogsRequest)(nil),                   // 25: fleetgrpc.LogsRequest
	(*ForwardChunk)(nil),                  // 26: fleetgrpc.ForwardChunk
	(*CopyFileRequest)(nil),               // 27: fleetgrpc.CopyFileRequest
	(*GetCoderTemplateParamsRequest)(nil), // 28: fleetgrpc.GetCoderTemplateParamsRequest
	(*GetBrowserConfigRequest)(nil),       // 29: fleetgrpc.GetBrowserConfigRequest
	(*PrepareBrowserRequest)(nil),         // 30: fleetgrpc.PrepareBrowserRequest
	(*HelloReply)(nil),                    // 31: fleetgrpc.HelloReply
	(*ShutdownReply)(nil),                 // 32: fleetgrpc.ShutdownReply
	(*FleetTUIConnectedReply)(nil),        // 33: fleetgrpc.FleetTUIConnectedReply
	(*GetStateReply)(nil),                 // 34: fleetgrpc.GetStateReply
	(*Event)(nil),                         // 35: fleetgrpc.Event
	(*JobEvent)(nil),                      // 36: fleetgrpc.JobEvent
	(*MutationReply)(nil),                 // 37: fleetgrpc.MutationReply
	(*DeleteBuildkitCacheReply)(nil),      // 38: fleetgrpc.DeleteBuildkitCacheReply
	(*DeleteDebCacheReply)(nil),           // 39: fleetgrpc.DeleteDebCacheReply
	(*DeleteImageCacheReply)(nil),         // 40: fleetgrpc.DeleteImageCacheReply
	(*GetConfigReply)(nil),                // 41: fleetgrpc.GetConfigReply
	(*SetConfigReply)(nil),                // 42: fleetgrpc.SetConfigReply
	(*ExecOut)(nil),                       // 43: fleetgrpc.ExecOut
	(*ResolveExecCommandReply)(nil),       // 44: fleetgrpc.ResolveExecCommandReply
	(*ResolveLogsCommandReply)(nil),       // 45: fleetgrpc.ResolveLogsCommandReply
	(*LogLine)(nil),                       // 46: fleetgrpc.LogLine
	(*CopyFileChunk)(nil),                 // 47: fleetgrpc.CopyFileChunk
	(*GetCoderTemplateParamsReply)(nil),   // 48: fleetgrpc.GetCoderTemplateParamsReply
	(*GetBrowserConfigReply)(nil),         // 49: fleetgrpc.GetBrowserConfigReply
	(*PrepareBrowserReply)(nil),           // 50: fleetgrpc.PrepareBrowserReply
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: fleetgrpc.FleetService.Hello:input_type -> fleetgrpc.HelloRequest
	1,  // 1: fleetgrpc.FleetService.Shutdown:input_type -> fleetgrpc.ShutdownRequest
	2,  // 2: fleetgrpc.FleetService.FleetTUIConnected:input_type -> fleetgrpc.FleetTUIConnectedRequest
	3,  // 3: fleetgrpc.FleetService.GetState:input_type -> fleetgrpc.GetStateRequest
	4,  // 4: fleetgrpc.FleetService.Watch:input_type -> fleetgrpc.WatchRequest
	5,  // 5: fleetgrpc.FleetService.CreateInstance:input_type -> fleetgrpc.CreateInstanceRequest
	6,  // 6: fleetgrpc.FleetService.DestroyInstance:input_type -> fleetgrpc.DestroyInstanceRequest
	7,  // 7: fleetgrpc.FleetService.StartInstance:input_type -> fleetgrpc.StartInstanceRequest
	8,  // 8: fleetgrpc.FleetService.StopInstance:input_type -> fleetgrpc.StopInstanceRequest
	9,  // 9: fleetgrpc.FleetService.CloneInstance:input_type -> fleetgrpc.CloneInstanceRequest
	10, // 10: fleetgrpc.FleetService.CreateFleet:input_type -> fleetgrpc.CreateFleetRequest
	11, // 11: fleetgrpc.FleetService.DestroyFleet:input_type -> fleetgrpc.DestroyFleetRequest
	12, // 12: fleetgrpc.FleetService.SetFleetSettings:input_type -> fleetgrpc.SetFleetSettingsRequest
	13, // 13: fleetgrpc.FleetService.DeleteBuildkitCache:input_type -> fleetgrpc.DeleteBuildkitCacheRequest
	14, // 14: fleetgrpc.FleetService.DeleteDebCache:input_type -> fleetgrpc.DeleteDebCacheRequest
	15, // 15: fleetgrpc.FleetService.DeleteImageCache:input_type -> fleetgrpc.DeleteImageCacheRequest
	16, // 16: fleetgrpc.FleetService.SetInstanceMetadata:input_type -> fleetgrpc.SetInstanceMetadataRequest
	17, // 17: fleetgrpc.FleetService.SetGroupLayout:input_type -> fleetgrpc.SetGroupLayoutRequest
	18, // 18: fleetgrpc.FleetService.DeleteGroupLayout:input_type -> fleetgrpc.DeleteGroupLayoutRequest
	19, // 19: fleetgrpc.FleetService.SetLastSeenVersion:input_type -> fleetgrpc.SetLastSeenVersionRequest
	20, // 20: fleetgrpc.FleetService.GetConfig:input_type -> fleetgrpc.GetConfigRequest
	21, // 21: fleetgrpc.FleetService.SetConfig:input_type -> fleetgrpc.SetConfigRequest
	22, // 22: fleetgrpc.FleetService.Exec:input_type -> fleetgrpc.ExecIn
	23, // 23: fleetgrpc.FleetService.ResolveExecCommand:input_type -> fleetgrpc.ResolveExecCommandRequest
	24, // 24: fleetgrpc.FleetService.ResolveLogsCommand:input_type -> fleetgrpc.ResolveLogsCommandRequest
	25, // 25: fleetgrpc.FleetService.Logs:input_type -> fleetgrpc.LogsRequest
	26, // 26: fleetgrpc.FleetService.Forward:input_type -> fleetgrpc.ForwardChunk
	27, // 27: fleetgrpc.FleetService.CopyFile:input_type -> fleetgrpc.CopyFileRequest
	28, // 28: fleetgrpc.FleetService.GetCoderTemplateParams:input_type -> fleetgrpc.GetCoderTemplateParamsRequest
	29, // 29: fleetgrpc.FleetService.GetBrowserConfig:input_type -> fleetgrpc.GetBrowserConfigRequest
	30, // 30: fleetgrpc.FleetService.PrepareBrowser:input_type -> fleetgrpc.PrepareBrowserRequest
	31, // 31: fleetgrpc.FleetService.Hello:output_type -> fleetgrpc.HelloReply
	32, // 32: fleetgrpc.FleetService.Shutdown:output_type -> fleetgrpc.ShutdownReply
	33, // 33: fleetgrpc.FleetService.FleetTUIConnected:output_type -> fleetgrpc.FleetTUIConnectedReply
	34, // 34: fleetgrpc.FleetService.GetState:output_type -> fleetgrpc.GetStateReply
	35, // 35: fleetgrpc.FleetService.Watch:output_type -> fleetgrpc.Event
	36, // 36: fleetgrpc.FleetService.CreateInstance:output_type -> fleetgrpc.JobEvent
	36, // 37: fleetgrpc.FleetService.DestroyInstance:output_type -> fleetgrpc.JobEvent
	36, // 38: fleetgrpc.FleetService.StartInstance:output_type -> fleetgrpc.JobEvent
	36, // 39: fleetgrpc.FleetService.StopInstance:output_type -> fleetgrpc.JobEvent
	36, // 40: fleetgrpc.FleetService.CloneInstance:output_type -> fleetgrpc.JobEvent
	37, // 41: fleetgrpc.FleetService.CreateFleet:output_type -> fleetgrpc.MutationReply
	37, // 42: fleetgrpc.FleetService.DestroyFleet:output_type -> fleetgrpc.MutationReply
	37, // 43: fleetgrpc.FleetService.SetFleetSettings:output_type -> fleetgrpc.MutationReply
	38, // 44: fleetgrpc.FleetService.DeleteBuildkitCache:output_type -> fleetgrpc.DeleteBuildkitCacheReply
	39, // 45: fleetgrpc.FleetService.DeleteDebCache:output_type -> fleetgrpc.DeleteDebCacheReply
	40, // 46: fleetgrpc.FleetService.DeleteImageCache:output_type -> fleetgrpc.DeleteImageCacheReply
	37, // 47: fleetgrpc.FleetService.SetInstanceMetadata:output_type -> fleetgrpc.MutationReply
	37, // 48: fleetgrpc.FleetService.SetGroupLayout:output_type -> fleetgrpc.MutationReply
	37, // 49: fleetgrpc.FleetService.DeleteGroupLayout:output_type -> fleetgrpc.MutationReply
	37, // 50: fleetgrpc.FleetService.SetLastSeenVersion:output_type -> fleetgrpc.MutationReply
	41, // 51: fleetgrpc.FleetService.GetConfig:output_type -> fleetgrpc.GetConfigReply
	42, // 52: fleetgrpc.FleetService.SetConfig:output_type -> fleetgrpc.SetConfigReply
	43, // 53: fleetgrpc.FleetService.Exec:output_type -> fleetgrpc.ExecOut
	44, // 54: fleetgrpc.FleetService.ResolveExecCommand:output_type -> fleetgrpc.ResolveExecCommandReply
	45, // 55: fleetgrpc.FleetService.ResolveLogsCommand:output_type -> fleetgrpc.ResolveLogsCommandReply
	46, // 56: fleetgrpc.FleetService.Logs:output_type -> fleetgrpc.LogLine
	26, // 57: fleetgrpc.FleetService.Forward:output_type -> fleetgrpc.ForwardChunk
	47, // 58: fleetgrpc.FleetService.CopyFile:output_type -> fleetgrpc.CopyFileChunk
	48, // 59: fleetgrpc.FleetService.GetCoderTemplateParams:output_type -> fleetgrpc.GetCoderTemplateParamsReply
	49, // 60: fleetgrpc.FleetService.GetBrowserConfig:output_type -> fleetgrpc.GetBrowserConfigReply
	50, // 61: fleetgrpc.FleetService.PrepareBrowser:output_type -> fleetgrpc.PrepareBrowserReply
	31, // [31:62] is the sub-list for method output_type
	0,  // [0:31] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_control_proto_init()
	file_watch_proto_init()
	file_jobs_proto_init()
	file_config_proto_init()
	file_exec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
