// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: service.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tfleetgrpc\x1a\rcontrol.proto\x1a\vwatch.proto\x1a\n" +
	"jobs.proto\x1a\fconfig.proto\x1a\n" +
	"exec.proto2\xbe\x0f\n" +
	"\fFleetService\x127\n" +
	"\x05Hello\x12\x17.fleetgrpc.HelloRequest\x1a\x15.fleetgrpc.HelloReply\x12@\n" +
	"\bShutdown\x12\x1a.fleetgrpc.ShutdownRequest\x1a\x18.fleetgrpc.ShutdownReply\x12@\n" +
	"\bGetState\x12\x1a.fleetgrpc.GetStateRequest\x1a\x18.fleetgrpc.GetStateReply\x124\n" +
	"\x05Watch\x12\x17.fleetgrpc.WatchRequest\x1a\x10.fleetgrpc.Event0\x01\x12I\n" +
	"\x0eCreateInstance\x12 .fleetgrpc.CreateInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12K\n" +
	"\x0fDestroyInstance\x12!.fleetgrpc.DestroyInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12G\n" +
	"\rStartInstance\x12\x1f.fleetgrpc.StartInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12E\n" +
	"\fStopInstance\x12\x1e.fleetgrpc.StopInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12G\n" +
	"\rCloneInstance\x12\x1f.fleetgrpc.CloneInstanceRequest\x1a\x13.fleetgrpc.JobEvent0\x01\x12F\n" +
	"\vCreateFleet\x12\x1d.fleetgrpc.CreateFleetRequest\x1a\x18.fleetgrpc.MutationReply\x12H\n" +
	"\fDestroyFleet\x12\x1e.fleetgrpc.DestroyFleetRequest\x1a\x18.fleetgrpc.MutationReply\x12P\n" +
	"\x10SetFleetSettings\x12\".fleetgrpc.SetFleetSettingsRequest\x1a\x18.fleetgrpc.MutationReply\x12V\n" +
	"\x13SetInstanceMetadata\x12%.fleetgrpc.SetInstanceMetadataRequest\x1a\x18.fleetgrpc.MutationReply\x12L\n" +
	"\x0eSetGroupLayout\x12 .fleetgrpc.SetGroupLayoutRequest\x1a\x18.fleetgrpc.MutationReply\x12R\n" +
	"\x11DeleteGroupLayout\x12#.fleetgrpc.DeleteGroupLayoutRequest\x1a\x18.fleetgrpc.MutationReply\x12T\n" +
	"\x12SetLastSeenVersion\x12$.fleetgrpc.SetLastSeenVersionRequest\x1a\x18.fleetgrpc.MutationReply\x12C\n" +
	"\tGetConfig\x12\x1b.fleetgrpc.GetConfigRequest\x1a\x19.fleetgrpc.GetConfigReply\x12C\n" +
	"\tSetConfig\x12\x1b.fleetgrpc.SetConfigRequest\x1a\x19.fleetgrpc.SetConfigReply\x121\n" +
	"\x04Exec\x12\x11.fleetgrpc.ExecIn\x1a\x12.fleetgrpc.ExecOut(\x010\x01\x12^\n" +
	"\x12ResolveExecCommand\x12$.fleetgrpc.ResolveExecCommandRequest\x1a\".fleetgrpc.ResolveExecCommandReply\x12^\n" +
	"\x12ResolveLogsCommand\x12$.fleetgrpc.ResolveLogsCommandRequest\x1a\".fleetgrpc.ResolveLogsCommandReply\x124\n" +
	"\x04Logs\x12\x16.fleetgrpc.LogsRequest\x1a\x12.fleetgrpc.LogLine0\x01\x12I\n" +
	"\vPortForward\x12\x1d.fleetgrpc.PortForwardRequest\x1a\x1b.fleetgrpc.PortForwardReply\x12j\n" +
	"\x16GetCoderTemplateParams\x12(.fleetgrpc.GetCoderTemplateParamsRequest\x1a&.fleetgrpc.GetCoderTemplateParamsReply\x12X\n" +
	"\x10GetBrowserConfig\x12\".fleetgrpc.GetBrowserConfigRequest\x1a .fleetgrpc.GetBrowserConfigReply\x12R\n" +
	"\x0ePrepareBrowser\x12 .fleetgrpc.PrepareBrowserRequest\x1a\x1e.fleetgrpc.PrepareBrowserReplyB:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var file_service_proto_goTypes = []any{
	(*HelloRequest)(nil),                  // 0: fleetgrpc.HelloRequest
	(*ShutdownRequest)(nil),               // 1: fleetgrpc.ShutdownRequest
	(*GetStateRequest)(nil),               // 2: fleetgrpc.GetStateRequest
	(*WatchRequest)(nil),                  // 3: fleetgrpc.WatchRequest
	(*CreateInstanceRequest)(nil),         // 4: fleetgrpc.CreateInstanceRequest
	(*DestroyInstanceRequest)(nil),        // 5: fleetgrpc.DestroyInstanceRequest
	(*StartInstanceRequest)(nil),          // 6: fleetgrpc.StartInstanceRequest
	(*StopInstanceRequest)(nil),           // 7: fleetgrpc.StopInstanceRequest
	(*CloneInstanceRequest)(nil),          // 8: fleetgrpc.CloneInstanceRequest
	(*CreateFleetRequest)(nil),            // 9: fleetgrpc.CreateFleetRequest
	(*DestroyFleetRequest)(nil),           // 10: fleetgrpc.DestroyFleetRequest
	(*SetFleetSettingsRequest)(nil),       // 11: fleetgrpc.SetFleetSettingsRequest
	(*SetInstanceMetadataRequest)(nil),    // 12: fleetgrpc.SetInstanceMetadataRequest
	(*SetGroupLayoutRequest)(nil),         // 13: fleetgrpc.SetGroupLayoutRequest
	(*DeleteGroupLayoutRequest)(nil),      // 14: fleetgrpc.DeleteGroupLayoutRequest
	(*SetLastSeenVersionRequest)(nil),     // 15: fleetgrpc.SetLastSeenVersionRequest
	(*GetConfigRequest)(nil),              // 16: fleetgrpc.GetConfigRequest
	(*SetConfigRequest)(nil),              // 17: fleetgrpc.SetConfigRequest
	(*ExecIn)(nil),                        // 18: fleetgrpc.ExecIn
	(*ResolveExecCommandRequest)(nil),     // 19: fleetgrpc.ResolveExecCommandRequest
	(*ResolveLogsCommandRequest)(nil),     // 20: fleetgrpc.ResolveLogsCommandRequest
	(*LogsRequest)(nil),                   // 21: fleetgrpc.LogsRequest
	(*PortForwardRequest)(nil),            // 22: fleetgrpc.PortForwardRequest
	(*GetCoderTemplateParamsRequest)(nil), // 23: fleetgrpc.GetCoderTemplateParamsRequest
	(*GetBrowserConfigRequest)(nil),       // 24: fleetgrpc.GetBrowserConfigRequest
	(*PrepareBrowserRequest)(nil),         // 25: fleetgrpc.PrepareBrowserRequest
	(*HelloReply)(nil),                    // 26: fleetgrpc.HelloReply
	(*ShutdownReply)(nil),                 // 27: fleetgrpc.ShutdownReply
	(*GetStateReply)(nil),                 // 28: fleetgrpc.GetStateReply
	(*Event)(nil),                         // 29: fleetgrpc.Event
	(*JobEvent)(nil),                      // 30: fleetgrpc.JobEvent
	(*MutationReply)(nil),                 // 31: fleetgrpc.MutationReply
	(*GetConfigReply)(nil),                // 32: fleetgrpc.GetConfigReply
	(*SetConfigReply)(nil),                // 33: fleetgrpc.SetConfigReply
	(*ExecOut)(nil),                       // 34: fleetgrpc.ExecOut
	(*ResolveExecCommandReply)(nil),       // 35: fleetgrpc.ResolveExecCommandReply
	(*ResolveLogsCommandReply)(nil),       // 36: fleetgrpc.ResolveLogsCommandReply
	(*LogLine)(nil),                       // 37: fleetgrpc.LogLine
	(*PortForwardReply)(nil),              // 38: fleetgrpc.PortForwardReply
	(*GetCoderTemplateParamsReply)(nil),   // 39: fleetgrpc.GetCoderTemplateParamsReply
	(*GetBrowserConfigReply)(nil),         // 40: fleetgrpc.GetBrowserConfigReply
	(*PrepareBrowserReply)(nil),           // 41: fleetgrpc.PrepareBrowserReply
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: fleetgrpc.FleetService.Hello:input_type -> fleetgrpc.HelloRequest
	1,  // 1: fleetgrpc.FleetService.Shutdown:input_type -> fleetgrpc.ShutdownRequest
	2,  // 2: fleetgrpc.FleetService.GetState:input_type -> fleetgrpc.GetStateRequest
	3,  // 3: fleetgrpc.FleetService.Watch:input_type -> fleetgrpc.WatchRequest
	4,  // 4: fleetgrpc.FleetService.CreateInstance:input_type -> fleetgrpc.CreateInstanceRequest
	5,  // 5: fleetgrpc.FleetService.DestroyInstance:input_type -> fleetgrpc.DestroyInstanceRequest
	6,  // 6: fleetgrpc.FleetService.StartInstance:input_type -> fleetgrpc.StartInstanceRequest
	7,  // 7: fleetgrpc.FleetService.StopInstance:input_type -> fleetgrpc.StopInstanceRequest
	8,  // 8: fleetgrpc.FleetService.CloneInstance:input_type -> fleetgrpc.CloneInstanceRequest
	9,  // 9: fleetgrpc.FleetService.CreateFleet:input_type -> fleetgrpc.CreateFleetRequest
	10, // 10: fleetgrpc.FleetService.DestroyFleet:input_type -> fleetgrpc.DestroyFleetRequest
	11, // 11: fleetgrpc.FleetService.SetFleetSettings:input_type -> fleetgrpc.SetFleetSettingsRequest
	12, // 12: fleetgrpc.FleetService.SetInstanceMetadata:input_type -> fleetgrpc.SetInstanceMetadataRequest
	13, // 13: fleetgrpc.FleetService.SetGroupLayout:input_type -> fleetgrpc.SetGroupLayoutRequest
	14, // 14: fleetgrpc.FleetService.DeleteGroupLayout:input_type -> fleetgrpc.DeleteGroupLayoutRequest
	15, // 15: fleetgrpc.FleetService.SetLastSeenVersion:input_type -> fleetgrpc.SetLastSeenVersionRequest
	16, // 16: fleetgrpc.FleetService.GetConfig:input_type -> fleetgrpc.GetConfigRequest
	17, // 17: fleetgrpc.FleetService.SetConfig:input_type -> fleetgrpc.SetConfigRequest
	18, // 18: fleetgrpc.FleetService.Exec:input_type -> fleetgrpc.ExecIn
	19, // 19: fleetgrpc.FleetService.ResolveExecCommand:input_type -> fleetgrpc.ResolveExecCommandRequest
	20, // 20: fleetgrpc.FleetService.ResolveLogsCommand:input_type -> fleetgrpc.ResolveLogsCommandRequest
	21, // 21: fleetgrpc.FleetService.Logs:input_type -> fleetgrpc.LogsRequest
	22, // 22: fleetgrpc.FleetService.PortForward:input_type -> fleetgrpc.PortForwardRequest
	23, // 23: fleetgrpc.FleetService.GetCoderTemplateParams:input_type -> fleetgrpc.GetCoderTemplateParamsRequest
	24, // 24: fleetgrpc.FleetService.GetBrowserConfig:input_type -> fleetgrpc.GetBrowserConfigRequest
	25, // 25: fleetgrpc.FleetService.PrepareBrowser:input_type -> fleetgrpc.PrepareBrowserRequest
	26, // 26: fleetgrpc.FleetService.Hello:output_type -> fleetgrpc.HelloReply
	27, // 27: fleetgrpc.FleetService.Shutdown:output_type -> fleetgrpc.ShutdownReply
	28, // 28: fleetgrpc.FleetService.GetState:output_type -> fleetgrpc.GetStateReply
	29, // 29: fleetgrpc.FleetService.Watch:output_type -> fleetgrpc.Event
	30, // 30: fleetgrpc.FleetService.CreateInstance:output_type -> fleetgrpc.JobEvent
	30, // 31: fleetgrpc.FleetService.DestroyInstance:output_type -> fleetgrpc.JobEvent
	30, // 32: fleetgrpc.FleetService.StartInstance:output_type -> fleetgrpc.JobEvent
	30, // 33: fleetgrpc.FleetService.StopInstance:output_type -> fleetgrpc.JobEvent
	30, // 34: fleetgrpc.FleetService.CloneInstance:output_type -> fleetgrpc.JobEvent
	31, // 35: fleetgrpc.FleetService.CreateFleet:output_type -> fleetgrpc.MutationReply
	31, // 36: fleetgrpc.FleetService.DestroyFleet:output_type -> fleetgrpc.MutationReply
	31, // 37: fleetgrpc.FleetService.SetFleetSettings:output_type -> fleetgrpc.MutationReply
	31, // 38: fleetgrpc.FleetService.SetInstanceMetadata:output_type -> fleetgrpc.MutationReply
	31, // 39: fleetgrpc.FleetService.SetGroupLayout:output_type -> fleetgrpc.MutationReply
	31, // 40: fleetgrpc.FleetService.DeleteGroupLayout:output_type -> fleetgrpc.MutationReply
	31, // 41: fleetgrpc.FleetService.SetLastSeenVersion:output_type -> fleetgrpc.MutationReply
	32, // 42: fleetgrpc.FleetService.GetConfig:output_type -> fleetgrpc.GetConfigReply
	33, // 43: fleetgrpc.FleetService.SetConfig:output_type -> fleetgrpc.SetConfigReply
	34, // 44: fleetgrpc.FleetService.Exec:output_type -> fleetgrpc.ExecOut
	35, // 45: fleetgrpc.FleetService.ResolveExecCommand:output_type -> fleetgrpc.ResolveExecCommandReply
	36, // 46: fleetgrpc.FleetService.ResolveLogsCommand:output_type -> fleetgrpc.ResolveLogsCommandReply
	37, // 47: fleetgrpc.FleetService.Logs:output_type -> fleetgrpc.LogLine
	38, // 48: fleetgrpc.FleetService.PortForward:output_type -> fleetgrpc.PortForwardReply
	39, // 49: fleetgrpc.FleetService.GetCoderTemplateParams:output_type -> fleetgrpc.GetCoderTemplateParamsReply
	40, // 50: fleetgrpc.FleetService.GetBrowserConfig:output_type -> fleetgrpc.GetBrowserConfigReply
	41, // 51: fleetgrpc.FleetService.PrepareBrowser:output_type -> fleetgrpc.PrepareBrowserReply
	26, // [26:52] is the sub-list for method output_type
	0,  // [0:26] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_control_proto_init()
	file_watch_proto_init()
	file_jobs_proto_init()
	file_config_proto_init()
	file_exec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
