// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: service.proto

package fleetgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_Hello_FullMethodName                  = "/fleetgrpc.FleetService/Hello"
	FleetService_Shutdown_FullMethodName               = "/fleetgrpc.FleetService/Shutdown"
	FleetService_FleetTUIConnected_FullMethodName      = "/fleetgrpc.FleetService/FleetTUIConnected"
	FleetService_GetState_FullMethodName               = "/fleetgrpc.FleetService/GetState"
	FleetService_Watch_FullMethodName                  = "/fleetgrpc.FleetService/Watch"
	FleetService_CreateInstance_FullMethodName         = "/fleetgrpc.FleetService/CreateInstance"
	FleetService_DestroyInstance_FullMethodName        = "/fleetgrpc.FleetService/DestroyInstance"
	FleetService_StartInstance_FullMethodName          = "/fleetgrpc.FleetService/StartInstance"
	FleetService_StopInstance_FullMethodName           = "/fleetgrpc.FleetService/StopInstance"
	FleetService_CloneInstance_FullMethodName          = "/fleetgrpc.FleetService/CloneInstance"
	FleetService_RebuildInstance_FullMethodName        = "/fleetgrpc.FleetService/RebuildInstance"
	FleetService_CreateFleet_FullMethodName            = "/fleetgrpc.FleetService/CreateFleet"
	FleetService_DestroyFleet_FullMethodName           = "/fleetgrpc.FleetService/DestroyFleet"
	FleetService_SetFleetSettings_FullMethodName       = "/fleetgrpc.FleetService/SetFleetSettings"
	FleetService_DeleteBuildkitCache_FullMethodName    = "/fleetgrpc.FleetService/DeleteBuildkitCache"
	FleetService_DeleteDebCache_FullMethodName         = "/fleetgrpc.FleetService/DeleteDebCache"
	FleetService_DeleteImageCache_FullMethodName       = "/fleetgrpc.FleetService/DeleteImageCache"
	FleetService_SetInstanceMetadata_FullMethodName    = "/fleetgrpc.FleetService/SetInstanceMetadata"
	FleetService_SetGroupLayout_FullMethodName         = "/fleetgrpc.FleetService/SetGroupLayout"
	FleetService_DeleteGroupLayout_FullMethodName      = "/fleetgrpc.FleetService/DeleteGroupLayout"
	FleetService_SetLastSeenVersion_FullMethodName     = "/fleetgrpc.FleetService/SetLastSeenVersion"
	FleetService_GetConfig_FullMethodName              = "/fleetgrpc.FleetService/GetConfig"
	FleetService_SetConfig_FullMethodName              = "/fleetgrpc.FleetService/SetConfig"
	FleetService_GetArmada_FullMethodName              = "/fleetgrpc.FleetService/GetArmada"
	FleetService_SetArmada_FullMethodName              = "/fleetgrpc.FleetService/SetArmada"
	FleetService_Exec_FullMethodName                   = "/fleetgrpc.FleetService/Exec"
	FleetService_ResolveExecCommand_FullMethodName     = "/fleetgrpc.FleetService/ResolveExecCommand"
	FleetService_ResolveLogsCommand_FullMethodName     = "/fleetgrpc.FleetService/ResolveLogsCommand"
	FleetService_Logs_FullMethodName                   = "/fleetgrpc.FleetService/Logs"
	FleetService_Forward_FullMethodName                = "/fleetgrpc.FleetService/Forward"
	FleetService_CopyFile_FullMethodName               = "/fleetgrpc.FleetService/CopyFile"
	FleetService_CopyInto_FullMethodName               = "/fleetgrpc.FleetService/CopyInto"
	FleetService_InspectRepo_FullMethodName            = "/fleetgrpc.FleetService/InspectRepo"
	FleetService_GetCoderTemplateParams_FullMethodName = "/fleetgrpc.FleetService/GetCoderTemplateParams"
	FleetService_GetBrowserConfig_FullMethodName       = "/fleetgrpc.FleetService/GetBrowserConfig"
	FleetService_PrepareBrowser_FullMethodName         = "/fleetgrpc.FleetService/PrepareBrowser"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetService is the single contract for CLI + TUI clients. It is designed
// transport-agnostically: served over a unix socket today (~/.fleet/fleet.sock)
// with NO localhost/uds assumptions, so the SAME service can be exposed over
// TCP+TLS for a remote TUI later. All inputs identify resources by name
// (fleet/instance), never by host-local paths.
type FleetServiceClient interface {
	// ---- Lifecycle / handshake ----
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error)
	// FleetTUIConnected is sent ONCE when a TUI opens (not by CLI commands): a
	// hook for once-per-open, fire-and-forget server-side state reconciliation
	// (e.g. re-ensuring configured shared buildkit servers after an external
	// kill / reboot). Kept off Hello so a burst of CLI Hellos can't trigger it.
	FleetTUIConnected(ctx context.Context, in *FleetTUIConnectedRequest, opts ...grpc.CallOption) (*FleetTUIConnectedReply, error)
	// GetState is the one-stop snapshot of everything the TUI renders (persisted
	// State + live runtime + active jobs).
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateReply, error)
	// Watch is the server-streaming subscription that replaces TUI polling and its
	// direct backend/filesystem access. Emits Events until the client cancels or
	// the server shuts down.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// ---- Jobs: each streams JobEvents; first event carries job_id ----
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	DestroyInstance(ctx context.Context, in *DestroyInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	CloneInstance(ctx context.Context, in *CloneInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	RebuildInstance(ctx context.Context, in *RebuildInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// ---- Synchronous (non-job) state mutations ----
	CreateFleet(ctx context.Context, in *CreateFleetRequest, opts ...grpc.CallOption) (*MutationReply, error)
	DestroyFleet(ctx context.Context, in *DestroyFleetRequest, opts ...grpc.CallOption) (*MutationReply, error)
	SetFleetSettings(ctx context.Context, in *SetFleetSettingsRequest, opts ...grpc.CallOption) (*MutationReply, error)
	// DeleteBuildkitCache wipes a fleet's shared build cache and restarts the
	// (empty) buildkit server. A synchronous host-docker action — clients use a
	// longer deadline and show progress.
	DeleteBuildkitCache(ctx context.Context, in *DeleteBuildkitCacheRequest, opts ...grpc.CallOption) (*DeleteBuildkitCacheReply, error)
	// DeleteDebCache / DeleteImageCache wipe a fleet's shared deb / docker-image
	// cache and restart the (empty) server. Synchronous host-docker actions —
	// clients use the same longer deadline as DeleteBuildkitCache.
	DeleteDebCache(ctx context.Context, in *DeleteDebCacheRequest, opts ...grpc.CallOption) (*DeleteDebCacheReply, error)
	DeleteImageCache(ctx context.Context, in *DeleteImageCacheRequest, opts ...grpc.CallOption) (*DeleteImageCacheReply, error)
	SetInstanceMetadata(ctx context.Context, in *SetInstanceMetadataRequest, opts ...grpc.CallOption) (*MutationReply, error)
	SetGroupLayout(ctx context.Context, in *SetGroupLayoutRequest, opts ...grpc.CallOption) (*MutationReply, error)
	DeleteGroupLayout(ctx context.Context, in *DeleteGroupLayoutRequest, opts ...grpc.CallOption) (*MutationReply, error)
	SetLastSeenVersion(ctx context.Context, in *SetLastSeenVersionRequest, opts ...grpc.CallOption) (*MutationReply, error)
	// ---- Config (server-owned config.json) ----
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error)
	// ---- Fleet Armada (the registry of remote fleets, armada.json) ----
	// Always served by the user's LOCAL daemon: the TUI routes these over a
	// dedicated local dial even while its main connection points at a remote
	// fleet (see armada.proto).
	GetArmada(ctx context.Context, in *GetArmadaRequest, opts ...grpc.CallOption) (*GetArmadaReply, error)
	SetArmada(ctx context.Context, in *SetArmadaRequest, opts ...grpc.CallOption) (*SetArmadaReply, error)
	// ---- Interactive backend operations ----
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecIn, ExecOut], error)
	ResolveExecCommand(ctx context.Context, in *ResolveExecCommandRequest, opts ...grpc.CallOption) (*ResolveExecCommandReply, error)
	ResolveLogsCommand(ctx context.Context, in *ResolveLogsCommandRequest, opts ...grpc.CallOption) (*ResolveLogsCommandReply, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	// Forward is the port-forward data plane: one bidi stream per forwarded TCP
	// connection (first frame is the ForwardOpen header, the rest raw bytes).
	// The client listens locally and pipes each accepted connection through this
	// stream; the server bridges it to remote_port inside the instance.
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardChunk, ForwardChunk], error)
	// CopyFile streams a single file out of an instance: first chunk is metadata,
	// the rest are data. Backs `fleet copy` and the in-instance `fc` shorthand.
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyFileChunk], error)
	// CopyInto streams a single file INTO an instance — the reverse of CopyFile.
	// Client-streaming: first chunk is the open header, the rest are data. Backs
	// the scp-style upload (and instance→instance relay) direction of `fleet copy`.
	CopyInto(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyIntoChunk, CopyIntoReply], error)
	// ---- Repo inspection (server-side clone + checks) ----
	// InspectRepo shallow-clones remote_url on the DAEMON's host and reports
	// devcontainer presence (and optionally the detected container home dir).
	// Inspection runs where provisioning runs, so the verdict is authoritative
	// for local and remote clients alike.
	InspectRepo(ctx context.Context, in *InspectRepoRequest, opts ...grpc.CallOption) (*InspectRepoReply, error)
	// ---- Coder template parameters (Coder API, read server-side) ----
	GetCoderTemplateParams(ctx context.Context, in *GetCoderTemplateParamsRequest, opts ...grpc.CallOption) (*GetCoderTemplateParamsReply, error)
	// ---- Browser (container-side half of the host browser feature) ----
	GetBrowserConfig(ctx context.Context, in *GetBrowserConfigRequest, opts ...grpc.CallOption) (*GetBrowserConfigReply, error)
	PrepareBrowser(ctx context.Context, in *PrepareBrowserRequest, opts ...grpc.CallOption) (*PrepareBrowserReply, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, FleetService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, FleetService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) FleetTUIConnected(ctx context.Context, in *FleetTUIConnectedRequest, opts ...grpc.CallOption) (*FleetTUIConnectedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FleetTUIConnectedReply)
	err := c.cc.Invoke(ctx, FleetService_FleetTUIConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateReply)
	err := c.cc.Invoke(ctx, FleetService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[0], FleetService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_WatchClient = grpc.ServerStreamingClient[Event]

func (c *fleetServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[1], FleetService_CreateInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateInstanceRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CreateInstanceClient = grpc.ServerStreamingClient[JobEvent]

func (c *fleetServiceClient) DestroyInstance(ctx context.Context, in *DestroyInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[2], FleetService_DestroyInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DestroyInstanceRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_DestroyInstanceClient = grpc.ServerStreamingClient[JobEvent]

func (c *fleetServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[3], FleetService_StartInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartInstanceRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_StartInstanceClient = grpc.ServerStreamingClient[JobEvent]

func (c *fleetServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[4], FleetService_StopInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StopInstanceRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_StopInstanceClient = grpc.ServerStreamingClient[JobEvent]

func (c *fleetServiceClient) CloneInstance(ctx context.Context, in *CloneInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[5], FleetService_CloneInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CloneInstanceRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CloneInstanceClient = grpc.ServerStreamingClient[JobEvent]

func (c *fleetServiceClient) RebuildInstance(ctx context.Context, in *RebuildInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[6], FleetService_RebuildInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RebuildInstanceRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_RebuildInstanceClient = grpc.ServerStreamingClient[JobEvent]

func (c *fleetServiceClient) CreateFleet(ctx context.Context, in *CreateFleetRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_CreateFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DestroyFleet(ctx context.Context, in *DestroyFleetRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_DestroyFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetFleetSettings(ctx context.Context, in *SetFleetSettingsRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_SetFleetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteBuildkitCache(ctx context.Context, in *DeleteBuildkitCacheRequest, opts ...grpc.CallOption) (*DeleteBuildkitCacheReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBuildkitCacheReply)
	err := c.cc.Invoke(ctx, FleetService_DeleteBuildkitCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteDebCache(ctx context.Context, in *DeleteDebCacheRequest, opts ...grpc.CallOption) (*DeleteDebCacheReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDebCacheReply)
	err := c.cc.Invoke(ctx, FleetService_DeleteDebCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteImageCache(ctx context.Context, in *DeleteImageCacheRequest, opts ...grpc.CallOption) (*DeleteImageCacheReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImageCacheReply)
	err := c.cc.Invoke(ctx, FleetService_DeleteImageCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetInstanceMetadata(ctx context.Context, in *SetInstanceMetadataRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_SetInstanceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetGroupLayout(ctx context.Context, in *SetGroupLayoutRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_SetGroupLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteGroupLayout(ctx context.Context, in *DeleteGroupLayoutRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_DeleteGroupLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetLastSeenVersion(ctx context.Context, in *SetLastSeenVersionRequest, opts ...grpc.CallOption) (*MutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationReply)
	err := c.cc.Invoke(ctx, FleetService_SetLastSeenVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, FleetService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigReply)
	err := c.cc.Invoke(ctx, FleetService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetArmada(ctx context.Context, in *GetArmadaRequest, opts ...grpc.CallOption) (*GetArmadaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArmadaReply)
	err := c.cc.Invoke(ctx, FleetService_GetArmada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetArmada(ctx context.Context, in *SetArmadaRequest, opts ...grpc.CallOption) (*SetArmadaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetArmadaReply)
	err := c.cc.Invoke(ctx, FleetService_SetArmada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecIn, ExecOut], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[7], FleetService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecIn, ExecOut]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_ExecClient = grpc.BidiStreamingClient[ExecIn, ExecOut]

func (c *fleetServiceClient) ResolveExecCommand(ctx context.Context, in *ResolveExecCommandRequest, opts ...grpc.CallOption) (*ResolveExecCommandReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveExecCommandReply)
	err := c.cc.Invoke(ctx, FleetService_ResolveExecCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ResolveLogsCommand(ctx context.Context, in *ResolveLogsCommandRequest, opts ...grpc.CallOption) (*ResolveLogsCommandReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveLogsCommandReply)
	err := c.cc.Invoke(ctx, FleetService_ResolveLogsCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[8], FleetService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_LogsClient = grpc.ServerStreamingClient[LogLine]

func (c *fleetServiceClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardChunk, ForwardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[9], FleetService_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardChunk, ForwardChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_ForwardClient = grpc.BidiStreamingClient[ForwardChunk, ForwardChunk]

func (c *fleetServiceClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[10], FleetService_CopyFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyFileRequest, CopyFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CopyFileClient = grpc.ServerStreamingClient[CopyFileChunk]

func (c *fleetServiceClient) CopyInto(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyIntoChunk, CopyIntoReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[11], FleetService_CopyInto_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyIntoChunk, CopyIntoReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CopyIntoClient = grpc.ClientStreamingClient[CopyIntoChunk, CopyIntoReply]

func (c *fleetServiceClient) InspectRepo(ctx context.Context, in *InspectRepoRequest, opts ...grpc.CallOption) (*InspectRepoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectRepoReply)
	err := c.cc.Invoke(ctx, FleetService_InspectRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetCoderTemplateParams(ctx context.Context, in *GetCoderTemplateParamsRequest, opts ...grpc.CallOption) (*GetCoderTemplateParamsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoderTemplateParamsReply)
	err := c.cc.Invoke(ctx, FleetService_GetCoderTemplateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetBrowserConfig(ctx context.Context, in *GetBrowserConfigRequest, opts ...grpc.CallOption) (*GetBrowserConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrowserConfigReply)
	err := c.cc.Invoke(ctx, FleetService_GetBrowserConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) PrepareBrowser(ctx context.Context, in *PrepareBrowserRequest, opts ...grpc.CallOption) (*PrepareBrowserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareBrowserReply)
	err := c.cc.Invoke(ctx, FleetService_PrepareBrowser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
//
// FleetService is the single contract for CLI + TUI clients. It is designed
// transport-agnostically: served over a unix socket today (~/.fleet/fleet.sock)
// with NO localhost/uds assumptions, so the SAME service can be exposed over
// TCP+TLS for a remote TUI later. All inputs identify resources by name
// (fleet/instance), never by host-local paths.
type FleetServiceServer interface {
	// ---- Lifecycle / handshake ----
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error)
	// FleetTUIConnected is sent ONCE when a TUI opens (not by CLI commands): a
	// hook for once-per-open, fire-and-forget server-side state reconciliation
	// (e.g. re-ensuring configured shared buildkit servers after an external
	// kill / reboot). Kept off Hello so a burst of CLI Hellos can't trigger it.
	FleetTUIConnected(context.Context, *FleetTUIConnectedRequest) (*FleetTUIConnectedReply, error)
	// GetState is the one-stop snapshot of everything the TUI renders (persisted
	// State + live runtime + active jobs).
	GetState(context.Context, *GetStateRequest) (*GetStateReply, error)
	// Watch is the server-streaming subscription that replaces TUI polling and its
	// direct backend/filesystem access. Emits Events until the client cancels or
	// the server shuts down.
	Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	// ---- Jobs: each streams JobEvents; first event carries job_id ----
	CreateInstance(*CreateInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error
	DestroyInstance(*DestroyInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error
	StartInstance(*StartInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error
	StopInstance(*StopInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error
	CloneInstance(*CloneInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error
	RebuildInstance(*RebuildInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error
	// ---- Synchronous (non-job) state mutations ----
	CreateFleet(context.Context, *CreateFleetRequest) (*MutationReply, error)
	DestroyFleet(context.Context, *DestroyFleetRequest) (*MutationReply, error)
	SetFleetSettings(context.Context, *SetFleetSettingsRequest) (*MutationReply, error)
	// DeleteBuildkitCache wipes a fleet's shared build cache and restarts the
	// (empty) buildkit server. A synchronous host-docker action — clients use a
	// longer deadline and show progress.
	DeleteBuildkitCache(context.Context, *DeleteBuildkitCacheRequest) (*DeleteBuildkitCacheReply, error)
	// DeleteDebCache / DeleteImageCache wipe a fleet's shared deb / docker-image
	// cache and restart the (empty) server. Synchronous host-docker actions —
	// clients use the same longer deadline as DeleteBuildkitCache.
	DeleteDebCache(context.Context, *DeleteDebCacheRequest) (*DeleteDebCacheReply, error)
	DeleteImageCache(context.Context, *DeleteImageCacheRequest) (*DeleteImageCacheReply, error)
	SetInstanceMetadata(context.Context, *SetInstanceMetadataRequest) (*MutationReply, error)
	SetGroupLayout(context.Context, *SetGroupLayoutRequest) (*MutationReply, error)
	DeleteGroupLayout(context.Context, *DeleteGroupLayoutRequest) (*MutationReply, error)
	SetLastSeenVersion(context.Context, *SetLastSeenVersionRequest) (*MutationReply, error)
	// ---- Config (server-owned config.json) ----
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigReply, error)
	// ---- Fleet Armada (the registry of remote fleets, armada.json) ----
	// Always served by the user's LOCAL daemon: the TUI routes these over a
	// dedicated local dial even while its main connection points at a remote
	// fleet (see armada.proto).
	GetArmada(context.Context, *GetArmadaRequest) (*GetArmadaReply, error)
	SetArmada(context.Context, *SetArmadaRequest) (*SetArmadaReply, error)
	// ---- Interactive backend operations ----
	Exec(grpc.BidiStreamingServer[ExecIn, ExecOut]) error
	ResolveExecCommand(context.Context, *ResolveExecCommandRequest) (*ResolveExecCommandReply, error)
	ResolveLogsCommand(context.Context, *ResolveLogsCommandRequest) (*ResolveLogsCommandReply, error)
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogLine]) error
	// Forward is the port-forward data plane: one bidi stream per forwarded TCP
	// connection (first frame is the ForwardOpen header, the rest raw bytes).
	// The client listens locally and pipes each accepted connection through this
	// stream; the server bridges it to remote_port inside the instance.
	Forward(grpc.BidiStreamingServer[ForwardChunk, ForwardChunk]) error
	// CopyFile streams a single file out of an instance: first chunk is metadata,
	// the rest are data. Backs `fleet copy` and the in-instance `fc` shorthand.
	CopyFile(*CopyFileRequest, grpc.ServerStreamingServer[CopyFileChunk]) error
	// CopyInto streams a single file INTO an instance — the reverse of CopyFile.
	// Client-streaming: first chunk is the open header, the rest are data. Backs
	// the scp-style upload (and instance→instance relay) direction of `fleet copy`.
	CopyInto(grpc.ClientStreamingServer[CopyIntoChunk, CopyIntoReply]) error
	// ---- Repo inspection (server-side clone + checks) ----
	// InspectRepo shallow-clones remote_url on the DAEMON's host and reports
	// devcontainer presence (and optionally the detected container home dir).
	// Inspection runs where provisioning runs, so the verdict is authoritative
	// for local and remote clients alike.
	InspectRepo(context.Context, *InspectRepoRequest) (*InspectRepoReply, error)
	// ---- Coder template parameters (Coder API, read server-side) ----
	GetCoderTemplateParams(context.Context, *GetCoderTemplateParamsRequest) (*GetCoderTemplateParamsReply, error)
	// ---- Browser (container-side half of the host browser feature) ----
	GetBrowserConfig(context.Context, *GetBrowserConfigRequest) (*GetBrowserConfigReply, error)
	PrepareBrowser(context.Context, *PrepareBrowserRequest) (*PrepareBrowserReply, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) Hello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedFleetServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedFleetServiceServer) FleetTUIConnected(context.Context, *FleetTUIConnectedRequest) (*FleetTUIConnectedReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FleetTUIConnected not implemented")
}
func (UnimplementedFleetServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedFleetServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedFleetServiceServer) CreateInstance(*CreateInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedFleetServiceServer) DestroyInstance(*DestroyInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method DestroyInstance not implemented")
}
func (UnimplementedFleetServiceServer) StartInstance(*StartInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedFleetServiceServer) StopInstance(*StopInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedFleetServiceServer) CloneInstance(*CloneInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method CloneInstance not implemented")
}
func (UnimplementedFleetServiceServer) RebuildInstance(*RebuildInstanceRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method RebuildInstance not implemented")
}
func (UnimplementedFleetServiceServer) CreateFleet(context.Context, *CreateFleetRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFleet not implemented")
}
func (UnimplementedFleetServiceServer) DestroyFleet(context.Context, *DestroyFleetRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyFleet not implemented")
}
func (UnimplementedFleetServiceServer) SetFleetSettings(context.Context, *SetFleetSettingsRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFleetSettings not implemented")
}
func (UnimplementedFleetServiceServer) DeleteBuildkitCache(context.Context, *DeleteBuildkitCacheRequest) (*DeleteBuildkitCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBuildkitCache not implemented")
}
func (UnimplementedFleetServiceServer) DeleteDebCache(context.Context, *DeleteDebCacheRequest) (*DeleteDebCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDebCache not implemented")
}
func (UnimplementedFleetServiceServer) DeleteImageCache(context.Context, *DeleteImageCacheRequest) (*DeleteImageCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImageCache not implemented")
}
func (UnimplementedFleetServiceServer) SetInstanceMetadata(context.Context, *SetInstanceMetadataRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInstanceMetadata not implemented")
}
func (UnimplementedFleetServiceServer) SetGroupLayout(context.Context, *SetGroupLayoutRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGroupLayout not implemented")
}
func (UnimplementedFleetServiceServer) DeleteGroupLayout(context.Context, *DeleteGroupLayoutRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroupLayout not implemented")
}
func (UnimplementedFleetServiceServer) SetLastSeenVersion(context.Context, *SetLastSeenVersionRequest) (*MutationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLastSeenVersion not implemented")
}
func (UnimplementedFleetServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedFleetServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedFleetServiceServer) GetArmada(context.Context, *GetArmadaRequest) (*GetArmadaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArmada not implemented")
}
func (UnimplementedFleetServiceServer) SetArmada(context.Context, *SetArmadaRequest) (*SetArmadaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetArmada not implemented")
}
func (UnimplementedFleetServiceServer) Exec(grpc.BidiStreamingServer[ExecIn, ExecOut]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedFleetServiceServer) ResolveExecCommand(context.Context, *ResolveExecCommandRequest) (*ResolveExecCommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveExecCommand not implemented")
}
func (UnimplementedFleetServiceServer) ResolveLogsCommand(context.Context, *ResolveLogsCommandRequest) (*ResolveLogsCommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveLogsCommand not implemented")
}
func (UnimplementedFleetServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Errorf(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedFleetServiceServer) Forward(grpc.BidiStreamingServer[ForwardChunk, ForwardChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedFleetServiceServer) CopyFile(*CopyFileRequest, grpc.ServerStreamingServer[CopyFileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedFleetServiceServer) CopyInto(grpc.ClientStreamingServer[CopyIntoChunk, CopyIntoReply]) error {
	return status.Errorf(codes.Unimplemented, "method CopyInto not implemented")
}
func (UnimplementedFleetServiceServer) InspectRepo(context.Context, *InspectRepoRequest) (*InspectRepoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectRepo not implemented")
}
func (UnimplementedFleetServiceServer) GetCoderTemplateParams(context.Context, *GetCoderTemplateParamsRequest) (*GetCoderTemplateParamsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoderTemplateParams not implemented")
}
func (UnimplementedFleetServiceServer) GetBrowserConfig(context.Context, *GetBrowserConfigRequest) (*GetBrowserConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrowserConfig not implemented")
}
func (UnimplementedFleetServiceServer) PrepareBrowser(context.Context, *PrepareBrowserRequest) (*PrepareBrowserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareBrowser not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call pancis, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_FleetTUIConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetTUIConnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).FleetTUIConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_FleetTUIConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).FleetTUIConnected(ctx, req.(*FleetTUIConnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_WatchServer = grpc.ServerStreamingServer[Event]

func _FleetService_CreateInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).CreateInstance(m, &grpc.GenericServerStream[CreateInstanceRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CreateInstanceServer = grpc.ServerStreamingServer[JobEvent]

func _FleetService_DestroyInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DestroyInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).DestroyInstance(m, &grpc.GenericServerStream[DestroyInstanceRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_DestroyInstanceServer = grpc.ServerStreamingServer[JobEvent]

func _FleetService_StartInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).StartInstance(m, &grpc.GenericServerStream[StartInstanceRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_StartInstanceServer = grpc.ServerStreamingServer[JobEvent]

func _FleetService_StopInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).StopInstance(m, &grpc.GenericServerStream[StopInstanceRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_StopInstanceServer = grpc.ServerStreamingServer[JobEvent]

func _FleetService_CloneInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CloneInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).CloneInstance(m, &grpc.GenericServerStream[CloneInstanceRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CloneInstanceServer = grpc.ServerStreamingServer[JobEvent]

func _FleetService_RebuildInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RebuildInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).RebuildInstance(m, &grpc.GenericServerStream[RebuildInstanceRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_RebuildInstanceServer = grpc.ServerStreamingServer[JobEvent]

func _FleetService_CreateFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateFleet(ctx, req.(*CreateFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DestroyFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DestroyFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DestroyFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DestroyFleet(ctx, req.(*DestroyFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetFleetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFleetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetFleetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetFleetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetFleetSettings(ctx, req.(*SetFleetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteBuildkitCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBuildkitCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteBuildkitCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteBuildkitCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteBuildkitCache(ctx, req.(*DeleteBuildkitCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteDebCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDebCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteDebCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteDebCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteDebCache(ctx, req.(*DeleteDebCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteImageCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteImageCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteImageCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteImageCache(ctx, req.(*DeleteImageCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetInstanceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetInstanceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetInstanceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetInstanceMetadata(ctx, req.(*SetInstanceMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetGroupLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetGroupLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetGroupLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetGroupLayout(ctx, req.(*SetGroupLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteGroupLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteGroupLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteGroupLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteGroupLayout(ctx, req.(*DeleteGroupLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetLastSeenVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLastSeenVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetLastSeenVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetLastSeenVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetLastSeenVersion(ctx, req.(*SetLastSeenVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetArmada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArmadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetArmada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetArmada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetArmada(ctx, req.(*GetArmadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetArmada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetArmadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetArmada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetArmada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetArmada(ctx, req.(*SetArmadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetServiceServer).Exec(&grpc.GenericServerStream[ExecIn, ExecOut]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_ExecServer = grpc.BidiStreamingServer[ExecIn, ExecOut]

func _FleetService_ResolveExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveExecCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ResolveExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ResolveExecCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ResolveExecCommand(ctx, req.(*ResolveExecCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ResolveLogsCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLogsCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ResolveLogsCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ResolveLogsCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ResolveLogsCommand(ctx, req.(*ResolveLogsCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_LogsServer = grpc.ServerStreamingServer[LogLine]

func _FleetService_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetServiceServer).Forward(&grpc.GenericServerStream[ForwardChunk, ForwardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_ForwardServer = grpc.BidiStreamingServer[ForwardChunk, ForwardChunk]

func _FleetService_CopyFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).CopyFile(m, &grpc.GenericServerStream[CopyFileRequest, CopyFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CopyFileServer = grpc.ServerStreamingServer[CopyFileChunk]

func _FleetService_CopyInto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetServiceServer).CopyInto(&grpc.GenericServerStream[CopyIntoChunk, CopyIntoReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_CopyIntoServer = grpc.ClientStreamingServer[CopyIntoChunk, CopyIntoReply]

func _FleetService_InspectRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).InspectRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_InspectRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).InspectRepo(ctx, req.(*InspectRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetCoderTemplateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoderTemplateParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetCoderTemplateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetCoderTemplateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetCoderTemplateParams(ctx, req.(*GetCoderTemplateParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetBrowserConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrowserConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetBrowserConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetBrowserConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetBrowserConfig(ctx, req.(*GetBrowserConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_PrepareBrowser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareBrowserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).PrepareBrowser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_PrepareBrowser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).PrepareBrowser(ctx, req.(*PrepareBrowserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetgrpc.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _FleetService_Hello_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _FleetService_Shutdown_Handler,
		},
		{
			MethodName: "FleetTUIConnected",
			Handler:    _FleetService_FleetTUIConnected_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _FleetService_GetState_Handler,
		},
		{
			MethodName: "CreateFleet",
			Handler:    _FleetService_CreateFleet_Handler,
		},
		{
			MethodName: "DestroyFleet",
			Handler:    _FleetService_DestroyFleet_Handler,
		},
		{
			MethodName: "SetFleetSettings",
			Handler:    _FleetService_SetFleetSettings_Handler,
		},
		{
			MethodName: "DeleteBuildkitCache",
			Handler:    _FleetService_DeleteBuildkitCache_Handler,
		},
		{
			MethodName: "DeleteDebCache",
			Handler:    _FleetService_DeleteDebCache_Handler,
		},
		{
			MethodName: "DeleteImageCache",
			Handler:    _FleetService_DeleteImageCache_Handler,
		},
		{
			MethodName: "SetInstanceMetadata",
			Handler:    _FleetService_SetInstanceMetadata_Handler,
		},
		{
			MethodName: "SetGroupLayout",
			Handler:    _FleetService_SetGroupLayout_Handler,
		},
		{
			MethodName: "DeleteGroupLayout",
			Handler:    _FleetService_DeleteGroupLayout_Handler,
		},
		{
			MethodName: "SetLastSeenVersion",
			Handler:    _FleetService_SetLastSeenVersion_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _FleetService_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _FleetService_SetConfig_Handler,
		},
		{
			MethodName: "GetArmada",
			Handler:    _FleetService_GetArmada_Handler,
		},
		{
			MethodName: "SetArmada",
			Handler:    _FleetService_SetArmada_Handler,
		},
		{
			MethodName: "ResolveExecCommand",
			Handler:    _FleetService_ResolveExecCommand_Handler,
		},
		{
			MethodName: "ResolveLogsCommand",
			Handler:    _FleetService_ResolveLogsCommand_Handler,
		},
		{
			MethodName: "InspectRepo",
			Handler:    _FleetService_InspectRepo_Handler,
		},
		{
			MethodName: "GetCoderTemplateParams",
			Handler:    _FleetService_GetCoderTemplateParams_Handler,
		},
		{
			MethodName: "GetBrowserConfig",
			Handler:    _FleetService_GetBrowserConfig_Handler,
		},
		{
			MethodName: "PrepareBrowser",
			Handler:    _FleetService_PrepareBrowser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _FleetService_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateInstance",
			Handler:       _FleetService_CreateInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DestroyInstance",
			Handler:       _FleetService_DestroyInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartInstance",
			Handler:       _FleetService_StartInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StopInstance",
			Handler:       _FleetService_StopInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CloneInstance",
			Handler:       _FleetService_CloneInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RebuildInstance",
			Handler:       _FleetService_RebuildInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _FleetService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _FleetService_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _FleetService_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyFile",
			Handler:       _FleetService_CopyFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CopyInto",
			Handler:       _FleetService_CopyInto_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
