// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: watch.proto

package fleetgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RemoteMcpConn is the connection state of the outbound MCP gateway tunnel.
type RemoteMcpConn int32

const (
	RemoteMcpConn_REMOTE_MCP_CONN_UNSPECIFIED RemoteMcpConn = 0 // feature off / not connected (the default)
	RemoteMcpConn_REMOTE_MCP_CONN_CONNECTING  RemoteMcpConn = 1 // enabled, dialing/registering with the gateway
	RemoteMcpConn_REMOTE_MCP_CONN_CONNECTED   RemoteMcpConn = 2 // tunnel up; public_url is live
	RemoteMcpConn_REMOTE_MCP_CONN_ERROR       RemoteMcpConn = 3 // enabled but the last attempt failed; error is set
)

// Enum value maps for RemoteMcpConn.
var (
	RemoteMcpConn_name = map[int32]string{
		0: "REMOTE_MCP_CONN_UNSPECIFIED",
		1: "REMOTE_MCP_CONN_CONNECTING",
		2: "REMOTE_MCP_CONN_CONNECTED",
		3: "REMOTE_MCP_CONN_ERROR",
	}
	RemoteMcpConn_value = map[string]int32{
		"REMOTE_MCP_CONN_UNSPECIFIED": 0,
		"REMOTE_MCP_CONN_CONNECTING":  1,
		"REMOTE_MCP_CONN_CONNECTED":   2,
		"REMOTE_MCP_CONN_ERROR":       3,
	}
)

func (x RemoteMcpConn) Enum() *RemoteMcpConn {
	p := new(RemoteMcpConn)
	*p = x
	return p
}

func (x RemoteMcpConn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteMcpConn) Descriptor() protoreflect.EnumDescriptor {
	return file_watch_proto_enumTypes[0].Descriptor()
}

func (RemoteMcpConn) Type() protoreflect.EnumType {
	return &file_watch_proto_enumTypes[0]
}

func (x RemoteMcpConn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteMcpConn.Descriptor instead.
func (RemoteMcpConn) EnumDescriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{0}
}

// WatchRequest opens a subscription.
//
// include_initial_state: emit one StateChanged snapshot, one RuntimeChanged
// snapshot (if subscribe_runtime), and one JobStarted per in-flight job up
// front — all taken in the SAME model-loop turn that registers the subscriber,
// so they reflect every mutation up to that instant and arrive before any live
// event.
//
// subscribe_runtime: opt in to the high-frequency InstanceRuntime stream
// (RuntimeChanged). The server only runs the expensive backend pollers (stats,
// agent probe, session list) while at least one subscriber wants runtime, so a
// plain `fleet ls`-style client leaves it false and the server stays quiet.
//
// reattach_job_ids: re-attach to specific jobs after a client restart. With
// include_initial_state the server advertises all in-flight jobs via JobStarted
// anyway, so this is optional convenience.
type WatchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncludeInitialState bool                   `protobuf:"varint,1,opt,name=include_initial_state,json=includeInitialState,proto3" json:"include_initial_state,omitempty"`
	SubscribeRuntime    bool                   `protobuf:"varint,2,opt,name=subscribe_runtime,json=subscribeRuntime,proto3" json:"subscribe_runtime,omitempty"`
	ReattachJobIds      []string               `protobuf:"bytes,3,rep,name=reattach_job_ids,json=reattachJobIds,proto3" json:"reattach_job_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetIncludeInitialState() bool {
	if x != nil {
		return x.IncludeInitialState
	}
	return false
}

func (x *WatchRequest) GetSubscribeRuntime() bool {
	if x != nil {
		return x.SubscribeRuntime
	}
	return false
}

func (x *WatchRequest) GetReattachJobIds() []string {
	if x != nil {
		return x.ReattachJobIds
	}
	return nil
}

// Event is the single Watch stream item. A oneof models the taxonomy so the
// stream is one ordered channel and the client switches on the active field.
//
// StateChanged carries authoritative PERSISTED snapshots (replacing state.Load
// polling) and is CONFLATABLE — for a slow consumer the server overwrites the
// pending snapshot with the newest full State rather than dropping it, so a slow
// TUI can never permanently desync.
//
// RuntimeChanged carries the high-frequency LIVE deltas (agent activity, stats,
// sessions, ports), kept SEPARATE from StateChanged so a 3s stat tick doesn't
// resend the whole persisted State. Only sent when subscribe_runtime is set.
//
// The Job* variants surface job activity to a watcher that did not itself start
// the job. JobStarted is here (not only on the job RPC) so a Watch-only client
// learns a job's identity/kind/target/started_at.
//
// BrowserOpen is pushed when the server's per-instance control listener receives
// a browser.open envelope from inside a container; the SERVER owns the control
// socket and resolves the URL, the CLIENT execs its local browser — the correct
// split for the remote-TUI goal.
//
// RemoteMcpStatus carries the live state of the outbound MCP gateway tunnel,
// including the gateway-assigned Public MCP URL. It is a server-owned, push-only
// COMPUTED value (never a Config field), so the settings page renders whatever
// the latest pushed status says without any SetConfig read-back. Conflatable
// (newest status wins) and cached by the hub for the initial snapshot.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_StateChanged
	//	*Event_JobStarted
	//	*Event_JobProgress
	//	*Event_JobLog
	//	*Event_JobDone
	//	*Event_BrowserOpen
	//	*Event_RuntimeChanged
	//	*Event_RemoteMcpStatus
	//	*Event_FileCopy
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetStateChanged() *StateChanged {
	if x != nil {
		if x, ok := x.Kind.(*Event_StateChanged); ok {
			return x.StateChanged
		}
	}
	return nil
}

func (x *Event) GetJobStarted() *JobStarted {
	if x != nil {
		if x, ok := x.Kind.(*Event_JobStarted); ok {
			return x.JobStarted
		}
	}
	return nil
}

func (x *Event) GetJobProgress() *JobProgress {
	if x != nil {
		if x, ok := x.Kind.(*Event_JobProgress); ok {
			return x.JobProgress
		}
	}
	return nil
}

func (x *Event) GetJobLog() *JobLog {
	if x != nil {
		if x, ok := x.Kind.(*Event_JobLog); ok {
			return x.JobLog
		}
	}
	return nil
}

func (x *Event) GetJobDone() *JobDone {
	if x != nil {
		if x, ok := x.Kind.(*Event_JobDone); ok {
			return x.JobDone
		}
	}
	return nil
}

func (x *Event) GetBrowserOpen() *BrowserOpen {
	if x != nil {
		if x, ok := x.Kind.(*Event_BrowserOpen); ok {
			return x.BrowserOpen
		}
	}
	return nil
}

func (x *Event) GetRuntimeChanged() *RuntimeChanged {
	if x != nil {
		if x, ok := x.Kind.(*Event_RuntimeChanged); ok {
			return x.RuntimeChanged
		}
	}
	return nil
}

func (x *Event) GetRemoteMcpStatus() *RemoteMcpStatus {
	if x != nil {
		if x, ok := x.Kind.(*Event_RemoteMcpStatus); ok {
			return x.RemoteMcpStatus
		}
	}
	return nil
}

func (x *Event) GetFileCopy() *FileCopy {
	if x != nil {
		if x, ok := x.Kind.(*Event_FileCopy); ok {
			return x.FileCopy
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_StateChanged struct {
	StateChanged *StateChanged `protobuf:"bytes,1,opt,name=state_changed,json=stateChanged,proto3,oneof"`
}

type Event_JobStarted struct {
	JobStarted *JobStarted `protobuf:"bytes,2,opt,name=job_started,json=jobStarted,proto3,oneof"`
}

type Event_JobProgress struct {
	JobProgress *JobProgress `protobuf:"bytes,3,opt,name=job_progress,json=jobProgress,proto3,oneof"`
}

type Event_JobLog struct {
	JobLog *JobLog `protobuf:"bytes,4,opt,name=job_log,json=jobLog,proto3,oneof"`
}

type Event_JobDone struct {
	JobDone *JobDone `protobuf:"bytes,5,opt,name=job_done,json=jobDone,proto3,oneof"`
}

type Event_BrowserOpen struct {
	BrowserOpen *BrowserOpen `protobuf:"bytes,6,opt,name=browser_open,json=browserOpen,proto3,oneof"`
}

type Event_RuntimeChanged struct {
	RuntimeChanged *RuntimeChanged `protobuf:"bytes,7,opt,name=runtime_changed,json=runtimeChanged,proto3,oneof"`
}

type Event_RemoteMcpStatus struct {
	RemoteMcpStatus *RemoteMcpStatus `protobuf:"bytes,8,opt,name=remote_mcp_status,json=remoteMcpStatus,proto3,oneof"`
}

type Event_FileCopy struct {
	FileCopy *FileCopy `protobuf:"bytes,9,opt,name=file_copy,json=fileCopy,proto3,oneof"`
}

func (*Event_StateChanged) isEvent_Kind() {}

func (*Event_JobStarted) isEvent_Kind() {}

func (*Event_JobProgress) isEvent_Kind() {}

func (*Event_JobLog) isEvent_Kind() {}

func (*Event_JobDone) isEvent_Kind() {}

func (*Event_BrowserOpen) isEvent_Kind() {}

func (*Event_RuntimeChanged) isEvent_Kind() {}

func (*Event_RemoteMcpStatus) isEvent_Kind() {}

func (*Event_FileCopy) isEvent_Kind() {}

// RemoteMcpStatus is the computed status the settings page shows after the user
// enables remote MCP and/or remote fleet (both share the one gateway tunnel, so
// one status describes them). public_url is the gateway-assigned Public MCP URL
// and public_grpc_url the Public GRPC URL a remote `fleet` dials (each only
// meaningful when state is CONNECTED; public_grpc_url is empty unless the grpc
// feature was negotiated and the gateway runs with --public-grpc-url); error
// carries the last failure (when state is ERROR).
type RemoteMcpStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RemoteMcpConn          `protobuf:"varint,1,opt,name=state,proto3,enum=fleetgrpc.RemoteMcpConn" json:"state,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	PublicGrpcUrl string                 `protobuf:"bytes,4,opt,name=public_grpc_url,json=publicGrpcUrl,proto3" json:"public_grpc_url,omitempty"`
	// gateway_version is the build version the gateway reported in its register
	// reply (empty from an old gateway that predates the field, or while not
	// CONNECTED). Surfaced so a remote TUI can render the version of every hop in
	// the control chain (tui -> gateway -> fleetd) and spot version skew.
	GatewayVersion string `protobuf:"bytes,5,opt,name=gateway_version,json=gatewayVersion,proto3" json:"gateway_version,omitempty"`
	// public_webhook_url is the gateway-assigned base URL for this daemon's
	// automation webhooks (<public-url>/webhook/<id>). A webhook trigger's full
	// URL is this base + "/" + the trigger's webhook name. Only set when state is
	// CONNECTED and the webhook feature was negotiated (the user enabled "Enable
	// Webhook"); empty otherwise (incl. from an old gateway).
	PublicWebhookUrl string `protobuf:"bytes,6,opt,name=public_webhook_url,json=publicWebhookUrl,proto3" json:"public_webhook_url,omitempty"`
	// ssh_addr is the loopback address (127.0.0.1:<port>) the daemon's
	// token-gated gRPC server listens on while remote fleet is enabled in SSH
	// mode — the port a remote client's SSH tunnel forwards to. Independent of
	// `state` (which describes the gateway tunnel): empty when the SSH listener is
	// off or failed. Stamped onto every status by the hub, so it survives the
	// gateway manager's own status pushes.
	SshAddr string `protobuf:"bytes,7,opt,name=ssh_addr,json=sshAddr,proto3" json:"ssh_addr,omitempty"`
	// ssh_error carries the SSH listener's last failure (bind error, missing
	// token) while it is enabled but not listening; empty otherwise.
	SshError      string `protobuf:"bytes,8,opt,name=ssh_error,json=sshError,proto3" json:"ssh_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteMcpStatus) Reset() {
	*x = RemoteMcpStatus{}
	mi := &file_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMcpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMcpStatus) ProtoMessage() {}

func (x *RemoteMcpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMcpStatus.ProtoReflect.Descriptor instead.
func (*RemoteMcpStatus) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteMcpStatus) GetState() RemoteMcpConn {
	if x != nil {
		return x.State
	}
	return RemoteMcpConn_REMOTE_MCP_CONN_UNSPECIFIED
}

func (x *RemoteMcpStatus) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *RemoteMcpStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RemoteMcpStatus) GetPublicGrpcUrl() string {
	if x != nil {
		return x.PublicGrpcUrl
	}
	return ""
}

func (x *RemoteMcpStatus) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

func (x *RemoteMcpStatus) GetPublicWebhookUrl() string {
	if x != nil {
		return x.PublicWebhookUrl
	}
	return ""
}

func (x *RemoteMcpStatus) GetSshAddr() string {
	if x != nil {
		return x.SshAddr
	}
	return ""
}

func (x *RemoteMcpStatus) GetSshError() string {
	if x != nil {
		return x.SshError
	}
	return ""
}

// StateChanged is pushed whenever the authoritative PERSISTED model mutates. It
// carries the full State (simple, race-free for a small model) so the client
// never reconciles partial deltas — directly replacing state.Load reloads.
type StateChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChanged) Reset() {
	*x = StateChanged{}
	mi := &file_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChanged) ProtoMessage() {}

func (x *StateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChanged.ProtoReflect.Descriptor instead.
func (*StateChanged) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{3}
}

func (x *StateChanged) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

// RuntimeChanged carries refreshed live runtime for one or more instances. Like
// StateChanged it is conflatable (the server coalesces per-instance updates for
// a slow consumer). May carry a single instance (a 3s stat tick) or the full set
// (the initial snapshot).
type RuntimeChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       []*InstanceRuntime     `protobuf:"bytes,1,rep,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeChanged) Reset() {
	*x = RuntimeChanged{}
	mi := &file_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeChanged) ProtoMessage() {}

func (x *RuntimeChanged) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeChanged.ProtoReflect.Descriptor instead.
func (*RuntimeChanged) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeChanged) GetRuntime() []*InstanceRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

// BrowserOpen asks the receiving client to open a URL in its local browser. The
// server computes url + the customization hints the TUI's browser layer used
// (data dir / profile) so the client just launches the browser.
type BrowserOpen struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Url     string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	DataDir *string                `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3,oneof" json:"data_dir,omitempty"`
	// fleet/instance label which workspace requested the open.
	Fleet         string `protobuf:"bytes,3,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance      string `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserOpen) Reset() {
	*x = BrowserOpen{}
	mi := &file_watch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserOpen) ProtoMessage() {}

func (x *BrowserOpen) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserOpen.ProtoReflect.Descriptor instead.
func (*BrowserOpen) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{5}
}

func (x *BrowserOpen) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BrowserOpen) GetDataDir() string {
	if x != nil && x.DataDir != nil {
		return *x.DataDir
	}
	return ""
}

func (x *BrowserOpen) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *BrowserOpen) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// FileCopy asks the receiving client (the connected TUI) to PERFORM a scp-style
// copy on the in-container sender's behalf. Pushed when the server's per-instance
// control listener receives a file.copy envelope from an in-container `fleet
// copy` (fc): the in-instance process cannot reach the host fleetd over gRPC
// (only the control socket is bind-mounted), so it delegates the whole copy to
// the TUI, which runs the generic copy engine against the host fleet with its
// own disk as the "local" side. Same control-socket → Watch → client-action
// split as BrowserOpen, which is what makes fc work for fully remote deployments.
//
// src and dst are the two scp endpoints AS TYPED inside the instance, verbatim.
// Each is either `[fleet/]instance:path` (an instance), a plain path (a file on
// the TUI machine — the human's disk), or `:path` (the CURRENT instance: the TUI
// substitutes the originating fleet/instance below). Direction is inferred from
// which side is local vs an instance.
type FileCopy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fleet/instance label of the instance that requested the copy. Also the value
	// the TUI substitutes for a `:path` (self) endpoint in src/dst.
	Fleet    string `protobuf:"bytes,1,opt,name=fleet,proto3" json:"fleet,omitempty"`
	Instance string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// src is the source endpoint as typed inside the instance.
	Src string `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	// dst is the destination endpoint as typed inside the instance. Empty is the
	// 1-arg download shorthand: the TUI delivers to its downloads folder.
	Dst           string `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCopy) Reset() {
	*x = FileCopy{}
	mi := &file_watch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCopy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCopy) ProtoMessage() {}

func (x *FileCopy) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCopy.ProtoReflect.Descriptor instead.
func (*FileCopy) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{6}
}

func (x *FileCopy) GetFleet() string {
	if x != nil {
		return x.Fleet
	}
	return ""
}

func (x *FileCopy) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *FileCopy) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *FileCopy) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

var File_watch_proto protoreflect.FileDescriptor

const file_watch_proto_rawDesc = "" +
	"\n" +
	"\vwatch.proto\x12\tfleetgrpc\x1a\fdomain.proto\x1a\rruntime.proto\x1a\n" +
	"jobs.proto\"\x99\x01\n" +
	"\fWatchRequest\x122\n" +
	"\x15include_initial_state\x18\x01 \x01(\bR\x13includeInitialState\x12+\n" +
	"\x11subscribe_runtime\x18\x02 \x01(\bR\x10subscribeRuntime\x12(\n" +
	"\x10reattach_job_ids\x18\x03 \x03(\tR\x0ereattachJobIds\"\xa6\x04\n" +
	"\x05Event\x12>\n" +
	"\rstate_changed\x18\x01 \x01(\v2\x17.fleetgrpc.StateChangedH\x00R\fstateChanged\x128\n" +
	"\vjob_started\x18\x02 \x01(\v2\x15.fleetgrpc.JobStartedH\x00R\n" +
	"jobStarted\x12;\n" +
	"\fjob_progress\x18\x03 \x01(\v2\x16.fleetgrpc.JobProgressH\x00R\vjobProgress\x12,\n" +
	"\ajob_log\x18\x04 \x01(\v2\x11.fleetgrpc.JobLogH\x00R\x06jobLog\x12/\n" +
	"\bjob_done\x18\x05 \x01(\v2\x12.fleetgrpc.JobDoneH\x00R\ajobDone\x12;\n" +
	"\fbrowser_open\x18\x06 \x01(\v2\x16.fleetgrpc.BrowserOpenH\x00R\vbrowserOpen\x12D\n" +
	"\x0fruntime_changed\x18\a \x01(\v2\x19.fleetgrpc.RuntimeChangedH\x00R\x0eruntimeChanged\x12H\n" +
	"\x11remote_mcp_status\x18\b \x01(\v2\x1a.fleetgrpc.RemoteMcpStatusH\x00R\x0fremoteMcpStatus\x122\n" +
	"\tfile_copy\x18\t \x01(\v2\x13.fleetgrpc.FileCopyH\x00R\bfileCopyB\x06\n" +
	"\x04kind\"\xad\x02\n" +
	"\x0fRemoteMcpStatus\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.fleetgrpc.RemoteMcpConnR\x05state\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12&\n" +
	"\x0fpublic_grpc_url\x18\x04 \x01(\tR\rpublicGrpcUrl\x12'\n" +
	"\x0fgateway_version\x18\x05 \x01(\tR\x0egatewayVersion\x12,\n" +
	"\x12public_webhook_url\x18\x06 \x01(\tR\x10publicWebhookUrl\x12\x19\n" +
	"\bssh_addr\x18\a \x01(\tR\asshAddr\x12\x1b\n" +
	"\tssh_error\x18\b \x01(\tR\bsshError\"6\n" +
	"\fStateChanged\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.fleetgrpc.StateR\x05state\"F\n" +
	"\x0eRuntimeChanged\x124\n" +
	"\aruntime\x18\x01 \x03(\v2\x1a.fleetgrpc.InstanceRuntimeR\aruntime\"~\n" +
	"\vBrowserOpen\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1e\n" +
	"\bdata_dir\x18\x02 \x01(\tH\x00R\adataDir\x88\x01\x01\x12\x14\n" +
	"\x05fleet\x18\x03 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstanceB\v\n" +
	"\t_data_dir\"`\n" +
	"\bFileCopy\x12\x14\n" +
	"\x05fleet\x18\x01 \x01(\tR\x05fleet\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x10\n" +
	"\x03src\x18\x03 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x04 \x01(\tR\x03dst*\x8a\x01\n" +
	"\rRemoteMcpConn\x12\x1f\n" +
	"\x1bREMOTE_MCP_CONN_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREMOTE_MCP_CONN_CONNECTING\x10\x01\x12\x1d\n" +
	"\x19REMOTE_MCP_CONN_CONNECTED\x10\x02\x12\x19\n" +
	"\x15REMOTE_MCP_CONN_ERROR\x10\x03B:Z8github.com/BenjaminBenetti/fleet-man/fleetgrpc;fleetgrpcb\x06proto3"

var (
	file_watch_proto_rawDescOnce sync.Once
	file_watch_proto_rawDescData []byte
)

func file_watch_proto_rawDescGZIP() []byte {
	file_watch_proto_rawDescOnce.Do(func() {
		file_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watch_proto_rawDesc), len(file_watch_proto_rawDesc)))
	})
	return file_watch_proto_rawDescData
}

var file_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_watch_proto_goTypes = []any{
	(RemoteMcpConn)(0),      // 0: fleetgrpc.RemoteMcpConn
	(*WatchRequest)(nil),    // 1: fleetgrpc.WatchRequest
	(*Event)(nil),           // 2: fleetgrpc.Event
	(*RemoteMcpStatus)(nil), // 3: fleetgrpc.RemoteMcpStatus
	(*StateChanged)(nil),    // 4: fleetgrpc.StateChanged
	(*RuntimeChanged)(nil),  // 5: fleetgrpc.RuntimeChanged
	(*BrowserOpen)(nil),     // 6: fleetgrpc.BrowserOpen
	(*FileCopy)(nil),        // 7: fleetgrpc.FileCopy
	(*JobStarted)(nil),      // 8: fleetgrpc.JobStarted
	(*JobProgress)(nil),     // 9: fleetgrpc.JobProgress
	(*JobLog)(nil),          // 10: fleetgrpc.JobLog
	(*JobDone)(nil),         // 11: fleetgrpc.JobDone
	(*State)(nil),           // 12: fleetgrpc.State
	(*InstanceRuntime)(nil), // 13: fleetgrpc.InstanceRuntime
}
var file_watch_proto_depIdxs = []int32{
	4,  // 0: fleetgrpc.Event.state_changed:type_name -> fleetgrpc.StateChanged
	8,  // 1: fleetgrpc.Event.job_started:type_name -> fleetgrpc.JobStarted
	9,  // 2: fleetgrpc.Event.job_progress:type_name -> fleetgrpc.JobProgress
	10, // 3: fleetgrpc.Event.job_log:type_name -> fleetgrpc.JobLog
	11, // 4: fleetgrpc.Event.job_done:type_name -> fleetgrpc.JobDone
	6,  // 5: fleetgrpc.Event.browser_open:type_name -> fleetgrpc.BrowserOpen
	5,  // 6: fleetgrpc.Event.runtime_changed:type_name -> fleetgrpc.RuntimeChanged
	3,  // 7: fleetgrpc.Event.remote_mcp_status:type_name -> fleetgrpc.RemoteMcpStatus
	7,  // 8: fleetgrpc.Event.file_copy:type_name -> fleetgrpc.FileCopy
	0,  // 9: fleetgrpc.RemoteMcpStatus.state:type_name -> fleetgrpc.RemoteMcpConn
	12, // 10: fleetgrpc.StateChanged.state:type_name -> fleetgrpc.State
	13, // 11: fleetgrpc.RuntimeChanged.runtime:type_name -> fleetgrpc.InstanceRuntime
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_watch_proto_init() }
func file_watch_proto_init() {
	if File_watch_proto != nil {
		return
	}
	file_domain_proto_init()
	file_runtime_proto_init()
	file_jobs_proto_init()
	file_watch_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_StateChanged)(nil),
		(*Event_JobStarted)(nil),
		(*Event_JobProgress)(nil),
		(*Event_JobLog)(nil),
		(*Event_JobDone)(nil),
		(*Event_BrowserOpen)(nil),
		(*Event_RuntimeChanged)(nil),
		(*Event_RemoteMcpStatus)(nil),
		(*Event_FileCopy)(nil),
	}
	file_watch_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watch_proto_rawDesc), len(file_watch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watch_proto_goTypes,
		DependencyIndexes: file_watch_proto_depIdxs,
		EnumInfos:         file_watch_proto_enumTypes,
		MessageInfos:      file_watch_proto_msgTypes,
	}.Build()
	File_watch_proto = out.File
	file_watch_proto_goTypes = nil
	file_watch_proto_depIdxs = nil
}
